### ISSUE TITLE
Merge Default & User Settings

### ISSUE THREAD

**Issue by sonaye** [jonlabelle/SublimeJsPrettier#10]
After a fresh installation of the plug-in and a fresh installation of prettier (0.11.0) as well, executing the formatting command doesn't work, the code is not formatted at all. This has nothing to do with finding prettier path, I am pretty sure of it.

The following message is displayed in the sublime console:
```
Traceback (most recent call last):
  File "/Applications/Sublime.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/a/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 60, in run
    prettier_options)
  File "/Users/a/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 98, in run_prettier
    prettier_cli_opts = self.parse_prettier_option_cli_map(prettier_options)
  File "/Users/a/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 222, in parse_prettier_option_cli_map
    option = prettier_options[mapping['option']]
KeyError: 'printWidth'
```

**Comment by jonlabelle** [comment]
Prettier v0.11.0 definitely has issues (#8, #9, #11). I would suggest using the a stable release, in particular **v0.0.10**.

    npm install -g prettier@0.0.10

Also... and it cannot be over-stated:

> "[*Warning: This is a beta, and the format may change over time. If you aren't OK with the format changing, wait for a more stable version.*"](https://github.com/jlongster/prettier) - *Prettier README.md*

**Comment by sonaye** [comment]
Switching back to 0.0.10 didn't fix the issue i am afraid. The problem seems to be related to the python code itself, from the console message, it is still appearing.

**Comment by jonlabelle** [comment]
Can you provide more information about your system, and versions. Also, include your entire ***User*** `JsPrettier.sublime-settings` file.

**Comment by sonaye** [comment]
macOS Sierra 10.12.3
Sublime Text Build 3126
```
{
  "auto_format_on_save" : true,
  "prettier_options": {
    "singleQuote": true,
  }
}
```

**Comment by jonlabelle** [comment]
Try copying the entire contents of the Default `JsPrettier.sublime-settings`, into your User `JsPrettier.sublime-settings` file. Then adjust your `"singleQuote": true` setting.

**Comment by sonaye** [comment]
that fixed it, it seems that the user settings completely overwrite the defaults, hence the plugin wouldn't receive the full configuration if only one setting was changed, works with 0.11.0 too.

**Comment by sonaye** [comment]
![screen shot 2017-01-28 at 5 32 58 pm](https://cloud.githubusercontent.com/assets/23000873/22397322/060e9f76-e580-11e6-813b-696e1da1232a.png)

Any ideas on why would the plugin distort the code in such a way?

**Comment by sonaye** [comment]
Actually the spaces added eventually cause sublime to completely crash.

**Comment by jonlabelle** [comment]
Just pushed [1.1.2](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.1.2) that includes merging the defaults with selective settings.

**Comment by sonaye** [comment]
the spaces distorting the code are no longer present with the new version as well.
