### ISSUE TITLE
Single quotes replaced by double quotes

### ISSUE THREAD

**Issue by mathieug** [jonlabelle/SublimeJsPrettier#100]
I use those settings:

package.json:
```
  "prettier": {
    "singleQuote": true,
    "arrowParens": "always"
  },
```

.sublime-project
```
  "settings": {
    "js_prettier": {
      "auto_format_on_save": true
    }
  }
```

Sometimes when I save, all the single quotes are replaced by double quotes.
I don't know if it comes from the plugin or from prettier but I guess the plugin.

Here are my versions:
- prettier 1.10.2
- Sublime Text 3156
- Mac OS High Sierra
- JsPrettier 1.19.0

**Comment by jonlabelle** [comment]
Enable the [debug](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14) setting and inspect the output for the generated command.

**Comment by oliviertassinari** [comment]
I have a similar issue. I'm only experiencing it since latest release:
**prettier.config.js**
```jsx
// @flow

module.exports = {
  printWidth: 100,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  parser: 'babylon',
  semi: true,
};
```

**console**
> /Users/o.tassinari/material-ui-next/node_modules/.bin/prettier --stdin --no-config --print-width 100 --single-quote true --trailing-comma all --bracket-spacing true --jsx-bracket-same-line false --parser babylon --semi false --require-pragma false --prose-wrap preserve --arrow-parens avoid --tab-width 2 --use-tabs false --stdin-filepath /Users/o.tassinari/material-ui-next/docs/scripts/buildServiceWorker.js

**Comment by MatthewKosloski** [comment]
This worked for me in the user preference's file of the package (Preferences > Package Settings > JSPrettier > Settings — User):

    {
	    "prettier_options": {
		"singleQuote": true
	    }
    }

**Comment by mathieug** [comment]
It also worked for me but it appears sometimes so I have to Undo then Save again.
