### ISSUE TITLE
Option request: Only autosave when a .prettierrc is defined

### ISSUE THREAD

**Issue by rodri042** [jonlabelle/SublimeJsPrettier#101]
It would be great to have an option to only enable autoformat when a .prettierrc is defined on the root of the project.

I use Sublime Text with a lot of projects and many of them don't use Prettier, so currently **every time I switch between projects I have to go to the settings file to disable/enable autoformat**. Example:

```
{
  "auto_format_on_save": true,
  "auto_format_only_if_prettierrc_found": true
}
```

**Prettier version**:
1.10.2

**Platform Details**:
Sublime Text 3 Build 3126, Linux.

**Comment by jonlabelle** [comment]
@rodri042: Sounds similar to #96. Can you verify?

**Comment by rodri042** [comment]
Yeah, looks pretty similar, but I didn't understand why "disabling autoformat if a prettier config isn't found" solves the problem with @dliuzzi's old files. So I thought maybe we were talking about different things.

**Comment by jonlabelle** [comment]
See #96

**Comment by rodri042** [comment]
@jonlabelle there are some problems too if this is not implemented.

Users who have `prettier` locally installed in every project (and NOT global), and use autosave, will see this annoying message **everytime they save a file** in a non-prettier project:

![screenshot1](https://user-images.githubusercontent.com/1631752/35816423-582cc3ca-0aa3-11e8-9a01-3c6b276012b6.png)

**Comment by rodri042** [comment]
Maybe we could have an option for ignoring 'command not found' errors? :)

**Comment by jonlabelle** [comment]
Why don't use just install prettier globally? When applicable, your local prettier will always resolve first.

**Comment by rodri042** [comment]
If I install prettier globally, JsPrettier formats the file on projects where I don't want to (the reason of this issue), which is much worse than the error popup.
