### ISSUE TITLE
My prettierrc is not found

### ISSUE THREAD

**Issue by antoinerousseau** [jonlabelle/SublimeJsPrettier#102]
### Explain the Issue and Expected Behavior

I have a `.prettierrc.yml` at the root of my ST3 project with some rules, including `semi: false`.

But once JsPrettier upgraded itself to 1.20, saving a JS file would add semicolons again. Adding `debug: true` would tell me that no config was found.

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.10.2

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.20.1",
    ...

### Platform Details

Provide your Sublime Text version and Platform details.

    - Sublime Text Version: 3
    - Sublime Text Build: 3143
    - Sublime Text Architecture: ?
    - Operating System Name: macOS
    - Operating System Version: 10.13.3
    - Operating System Architecture: x64

### Generated Prettier command line arguments

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/antoine/Sites/strategia/yangoPharma/node_modules/.bin/prettier --stdin --no-config --print-width 80 --single-quote false --trailing-comma none --bracket-spacing true --jsx-bracket-same-line false --parser babylon --semi true --require-pragma false --prose-wrap preserve --arrow-parens avoid --tab-width 4 --use-tabs false --stdin-filepath /Users/antoine/Sites/strategia/yangoPharma/app/components/Programs.js --ignore-path /Users/antoine/Sites/strategia/yangoPharma/.prettierignore
```

### Is the same behavior observed when run against Prettier directly?

N/A

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

None
    
### The contents of your `<project_name>.sublime-project` file (if applicable)

The entire contents of your ***User*** overridden JsPretter Project-level Settings, excluding the comments.

```json
"js_prettier": {
	"auto_format_on_save": true,
	"auto_format_on_save_excludes": [
		"*/node_modules/*",
	]
}
```

**Comment by antoinerousseau** [comment]
Fyi I added this as a temporary fix in my sublime-project's `settings.js_prettier`:
```json
"additional_cli_args": {
  "--config": ".prettierrc.yml"
}
```

**Comment by willsoto** [comment]
Same here with `prettier.config.js`

**Comment by jonlabelle** [comment]
I'll try and get this fixed later this evening. In the meantime, trying removing the `--config` option all together from `additional_cli_args`. Your Prettier config file *should* implicitly resolve when it's in your project root.

Let me know.

**Comment by antoinerousseau** [comment]
I added `additional_cli_args` as a temporary fix but not having it or having an empty object makes it fall in this issue case

**Comment by thezimmee** [comment]
I have the same issue, using `.prettierrc.js` as my config.

> In the meantime, trying removing the --config option all together from additional_cli_args. Your Prettier config file should implicitly resolve when it's in your project root.

That didn't work for me. (Sidenote: If I recall correctly I don't think the prettier config has ever resolved for me... which I believe is why I had to add `"--config-precedence": "file-override"`).

As a workaround, @antoinerousseau's suggestion worked for me as well:

```
"additional_cli_args": {
	"--config": ".prettierrc.js"
}
```

**Comment by ryami333** [comment]
Same here. In my instance, `.prettierrc` is not at the project-root, but nested one directory deep (using a monorepo).

**Comment by pablen** [comment]
Same here after updating today to v1.20
My `.prettierrc.json` under the root directory of my project was resolving correctly before.

**Comment by gh640** [comment]
@jonlabelle  I'm sorry for interference. I tried adjusting the code to address this issue in PR #103 . I'd like you to review the PR if you don't mind.

Thank you in advance.

**Comment by aronwoost** [comment]
Same here with `.prettierrc`.

**Comment by dukeflyheli** [comment]
Same for me. `.prettierrc` in the project dir is not found so it is using defaults.

**Comment by hyperh** [comment]
Same issue

**Comment by oliviertassinari** [comment]
My workaround:
**JsPrettier.sublime-settings**
```json
{
  "prettier_options": {
  },
  "additional_cli_args": {
    "--config": "prettier.config.js"
  }
}
```
