### ISSUE TITLE
JsPrettier showing as disabled (grayed out) in context menu

### ISSUE THREAD

**Issue by cybenauts** [jonlabelle/SublimeJsPrettier#107]
JsPrettier not showing up in Pallet/Grayed Out in context menu.
Even after typing format

**Comment by tricinel** [comment]
I had the same issue. What worked for me was updating my version of prettier.

```
prettier -v # 1.4.4
yarn global upgrade prettier
prettier -v # 1.10.2
```
JSPrettier works again now for me. Hope it helps you too!

Cheers,
Bogdan

**Comment by andrew-culver** [comment]
I had to update eslint to 4.18.1 as well
