### ISSUE TITLE
Fails to find Prettier with multiple folders open

### ISSUE THREAD

**Issue by ianstormtaylor** [jonlabelle/SublimeJsPrettier#110]
In Sublime, if I do **Project > Add Folder to Project…**, then JsPrettier suddenly stops working because it can no longer find the `prettier` CLI.

For example, if I open Sublime with a folder like:

```
/folder-a
```

And save the file (with the auto-save on), it works. Because it finds `prettier` via `/folder-a/node_modules/.bin/prettier`.

But if I instead open up `folder-b` and then also open up `folder-a` via **Project > Add Folder to Project…**, like so...

```
/folder-b
/folder-a
```

Then if I save any file in `folder-a` JsPrettier says that it can no longer find the `prettier` CLI, even though it still existing in `/folder-a/node_modules/.bin/prettier` and even though I'm saving a file inside `folder-a`.

Shouldn't it look relative to the current file you're saving?

My settings are:

```json
{
  "debug": true,
  "auto_format_on_save": true,
  "auto_format_on_save_requires_prettier_config": true,
}
```
```
Prettier: 1.10.2
JsPrettier: 1.20.13
```

**Comment by jonlabelle** [comment]
Seems logical. I'll have a look this wknd.

**Comment by jonlabelle** [comment]
I think I can borrow what SublimeLinter's doing in their advanced `$folder` expansion implementation. From the [docs](http://www.sublimelinter.com/en/stable/settings.html#settings-expansion)...

> *We enhanced the expansion for folder. It now attempts to guess the correct folder if you have multiple folders open in a window.*

And here it is [in code](https://github.com/SublimeLinter/SublimeLinter/blob/9a837d23f093611d12af4328352ef73723dd4a35/lint/linter.py#L454).

**Comment by jonlabelle** [comment]
@ianstormtaylor So I've been trying to reproduce this scenario (a couple days now), but w/out any luck.

Any time I save a file back to `/folder-a` (represented as the first folder `.` below), after adding subsequent  folders, e.g. `/folder-b` (represented as the second folder `/Users/jon/Downloads` below) - going back and saving files in `forlder-a`... `prettier_cli_path` always resolves according to the relative source file being edited (and formatting is triggered).

**Here's what my Sublime Text Project file** (`project.sublime-project`) **looks like:**

```json
{
    "folders": [
        {
            "path": "."
        },
        {
            "path": "/Users/jon/Downloads"
        }
    ],
    "settings": {
        "js_prettier": {
            "additional_cli_args": {},
            "allow_inline_formatting": false,
            "auto_format_on_save": true,
            "auto_format_on_save_excludes": [],
            "auto_format_on_save_requires_prettier_config": true,
            "custom_file_extensions": [],
            "debug": true,
            "max_file_size_limit": -1,
            "node_path": "",
            "prettier_cli_path": "",
            "prettier_options": {
                "arrowParens": "avoid",
                "bracketSpacing": true,
                "jsxBracketSameLine": false,
                "parser": "babylon",
                "printWidth": 80,
                "proseWrap": "preserve",
                "requirePragma": false,
                "semi": false,
                "singleQuote": false,
                "trailingComma": "none"
            }
        }
    }
}
```

... and the resolved prettier path is `./node_modules/.bin/prettier`.

**Comment by Rayraegah** [comment]
I never noticed this error because I have prettier installed globally. I removed all my global npm modules and started seeing it.

**Comment by ianstormtaylor** [comment]
@Rayraegah yup same here. I never noticed it, then one day I cleaned out my global and later that day I noticed that this package broke. 

@jonlabelle it’s the order that matters. F you add `a` after opening `b` then saving a file inside `a` fails.

**Comment by jonlabelle** [comment]
Can someone post-back and attach a minimum working set of files required (single zip archive) in order to reproduce the issue? I can't seem to reproduce the problem on my end - but need to make sure our configurations are aligned (or not).

Please include the following files with their *entire contents*... bearing anything deemed identifiable (to you), private, or secure.

- [ ] Sublime Text 3/Packages/***User***/`JsPrettier.sublime-settings`
- [ ] Sublime Text File Project file (if applicable). e.g.: `MyProject.sublime-project`.
- [ ] The complete contents (files and directories) - of ***at least 2 of the project folders***  involved.

... or anything in the project that allows me to reproduce the issue, not necessarily listed above.

> **IMPORTANT** Please do NOT include the contents of your packages directory (`./node_modules/`), just *your* project's `package.json` file.
