### ISSUE TITLE
TypeError: resolve_prettier_cli_path() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by fraserxu** [jonlabelle/SublimeJsPrettier#112]
## Reporting an Issue

- [x] **JsPrettier Plug-in**

---

### Explain the Issue and Expected Behavior

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/fraserxu/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 245, in run
    prettier_cli_path = resolve_prettier_cli_path(view, PLUGIN_PATH, st_project_path)
TypeError: resolve_prettier_cli_path() takes 2 positional arguments but 3 were given
```

### Prettier version

```
1.10.2
```

This commit seems related https://github.com/jonlabelle/SublimeJsPrettier/commit/c1b5eb304060ece13b1b3a7440bfe9494b2bfee5

**Comment by jonlabelle** [comment]
Hard for me to really investigate this because you didn't follow the [issue template](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md).

Try closing/opening Sublime Text.

**Comment by laugri** [comment]
For people Googling and finding this error: I ran into the same error today, killing Sublime resolved the issue as suggested.

**Comment by fraserxu** [comment]
Thanks @jonlabelle @laugri I did try to reinstall the package and restart Sublime yesterday but it was not working. Just try to kill all Sublime process and it seems resolve the issue.

**Comment by andfaulkner** [comment]
I had the same problem, and reinstalling the package then restarting Sublime didn't fix it. However, I eventually did manage to get it running again by:

1) Uninstalling the package
2) Restarting sublime
3) Installing the package
4) Restarting Sublime again

I'm not sure why it was important to restart between uninstall and install, but it was the only thing that worked for me.

Thanks @jonlabelle, @laugri, and @fraserxu! (you set me on the right path)
