### ISSUE TITLE
Autosave not working

### ISSUE THREAD

**Issue by bemyhre** [jonlabelle/SublimeJsPrettier#113]
ISSUE: When I save a javascript file, nothing is prettified or changed. If I have two tabs, I would expect it to remove a tab. If I don't include a semicolon, I would expect it to add. It does neither.

I had a similar issue previously and ended up uninstalling everything and reinstalling it. Through an unprecise sequence of steps, I 'fixed' it. Now, it is happening again. 

Steps to reproduce: 

Open any js file in sublime. Save. Nothing corrects.

Prettier version 1.8.2
JsPrettier Plugin Version: 1.20.0
Platform: macOs Sierra 10.12.6 - sublime text 2 - ohmyzsh
If I run prettier fro Cli, it works fine. 
The sublime console displays on error:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/bmyhre/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 245, in run
    prettier_cli_path = resolve_prettier_cli_path(view, PLUGIN_PATH, st_project_path)
TypeError: resolve_prettier_cli_path() takes 2 positional arguments but 3 were given

In the User Settings:

{
	"prettier_cli_path": "/usr/local/bin/prettier",
	"node_path": "/usr/local/bin/node",
	"auto_format_on_save": true,
	"prettier_options": {
		"printWidth": 120,
		"tabWidth": 2,
		"singleQuote": true,
		"trailingComma": "none",
		"bracketSpacing": true,
		"jsxBracketSameLine": false,
		"parser": "flow",
		"semi": true,
		"tabs": false
	}
}

**Comment by pobed2** [comment]
I also just started seeing this issue.

**Comment by ramosquito5** [comment]
Same, checking the code version 1.20.14 has resolve_prettier_cli_path(param1,param2) while
resolve_prettier_cli_path(param1,param2,param3).

Solution use Version 1.20.14
instead of 1.20.15+

**Comment by esbanarango** [comment]
Same issue here ☝️

**Comment by esbanarango** [comment]
@ramosquito5 how do you use an specific version of a package? 🤔

**Comment by mattbrictson** [comment]
@esbanarango Remove the package using Package Control's "Remove Package" command first. Then you can download a ZIP of the specific version you want from the [releases list on GitHub](https://github.com/jonlabelle/SublimeJsPrettier/releases) and follow the [manual install instructions](https://github.com/jonlabelle/SublimeJsPrettier#install-jsprettier-manually).

**Comment by jonlabelle** [comment]
Try reinstalling the package from package control. Close/open Sublime Text.

**Comment by mattbrictson** [comment]
Thanks @jonlabelle. I reinstalled from Package Control and then quit/restarted Sublime Text and that fixed it!
