### ISSUE TITLE
is it possible to override default settings from a non-"Sublime project" folder?

### ISSUE THREAD

**Issue by mezod** [jonlabelle/SublimeJsPrettier#115]
Hi, thanks for this lib and sorry if this isn't the right place to ask.

I have installed JsPrettier and set the default "auto_format_on_save": false, so that it doesn't affect my other folder projects. I have read that you can override the default settings for a specific project, but I also found out that I never really used Sublime Text projects, I simply open a folder and that's my "project". So, before getting into creating ST projects, I wonder, is it possible to somehow add a config file inside my folder root that overrides the default settings? Something similar to .gitignore or .eslintrc.

Thank you!

**Comment by jonlabelle** [comment]
Yup! Please see the [docs](https://github.com/jonlabelle/SublimeJsPrettier#prettier-configuration-files).

**Comment by mezod** [comment]
For anyone stumbling across this question, the answer is actually "No, it's not possible. You need to create a Sublime Text Project first out of your project folder."
