### ISSUE TITLE
It doesn't work on Ubuntu sublime3

### ISSUE THREAD

**Issue by white112** [jonlabelle/SublimeJsPrettier#119]
I am using Ubuntu 18.04 and sublime 3.1.1
I installed JsPrettier successfully.
When I click 'JsPrettier Format Code' on right menu, nothing happens.
It doesn't work.

**Comment by jonlabelle** [comment]
Please follow the directions outlined in the [ISSUE TEMPLATE](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md).
