### ISSUE TITLE
Formatting is Incorrect

### ISSUE THREAD

**Issue by itsmesuresh** [jonlabelle/SublimeJsPrettier#12]
Sublime Text 3 (Build 3126), default JsPrettier.sublime-settings are used

1. Two newlines are added to the EOF.
2. `console.log()` formatted incorrectly.

![prettier git](https://cloud.githubusercontent.com/assets/23494332/22394741/6631eab6-e54e-11e6-8eb3-c347b5cd0000.gif)

**Note**: 
To make sure this was not a prettier issue i tried from the CLI it's formatting the file correctly.

**Comment by jonlabelle** [comment]
Try installing `npm install -g prettier@0.0.10` and see what happens.

**Comment by itsmesuresh** [comment]
Formatting works fine now but still 2 new lines are added to the EOF.

**Comment by jonlabelle** [comment]
It's not JsPrettier plugin. You can try the latest version:

`npm install -g prettier@0.13.1`
