### ISSUE TITLE
After Sublime Text 3.1.1 update, not prettifying anymore

### ISSUE THREAD

**Issue by EqipInc** [jonlabelle/SublimeJsPrettier#121]
### Explain the Issue and Expected Behavior

JSPrettify is no longer prettifying as of today May 31 2018, where previously everything was fine. The only thing I did today was upgrade SublimeText to version 3.1.1 (which came out May 14th, 2018) and installed another package (PlainNotes - https://github.com/aziz/PlainNotes) and now it's not working. 

- The option to "prettify" from the context menu when right/double clicking is grayed out. The hotkey does not work. Format on save, when set to true in .sublime-settings, does not format either. 
- The debug console in sublime does not mention anything even when settings debug is set to true.

I noticed that all of my User/*.sublime-settings files are not appearing anymore after the update (which is more like a Sublime 3.1.1 issue), but otherwise the default JSPrettier settings file is still present and editable. 

I uninstalled the new PlainNotes package, I tried uninstalling and reinstalling JSPrettier too and reopening sublime like mentioned in #106 , but still nothing works.

### Prettier version

1.13.3

### JsPrettier Plug-in Version

`The JsPrettier Sublime Text Plug-in version is located in the package.json file.`

This is vague... what package.json file is this located in? Where is this file on MacOs? 

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3.1.1
    - Sublime Text Build: 3176
    - Sublime Text Architecture: ?
    - Operating System Name: Osx
    - Operating System Version: 10.13.4
    - Operating System Architecture: High Sierra

### Generated Prettier command line arguments

Like mentioned above, no console output is presented even when debug = true

### Is the same behavior observed when run against Prettier directly?

???

### The contents of your `User/JsPrettier.sublime-settings` file

empty (but before sublime text's update it had stuff)
    
### The contents of your `<project_name>.sublime-project` file (if applicable)

Essentially the same as the default from a fresh install.

### Steps to reproduce the behavior

Unsure, but maybe is upgrading to Sublime 3.1.1 the problem? 

Happy to answer any other questions! Thanks. Hope this was enoughl

**Comment by infotexture** [comment]
I have the same issue: after upgrading to Sublime Text 3.1.1, the context menu option is disabled:

> JsPrettier Format Code

The command no longer appears in the command palette, although the package is still enabled.

**Comment by jonlabelle** [comment]
Can you try re-installing the package from [Package Control](https://packagecontrol.io/packages/JsPrettier).... and restart Sublime Text.

**Comment by 0xStarcat** [comment]
Yes, I've removed JsPrettier and re-installed as well as restarted SublimeText a couple times but that's not fixing it for me.

**Comment by EqipInc** [comment]
Yes, I've tried to remove and reinstall JsPrettier as well as restart Sublime but it doesn't seem to fix it.

**Comment by EqipInc** [comment]
Ah! It got fixed when I restarted my *computer* for whatever reason.

**Comment by infotexture** [comment]
@jonlabelle Thanks, re-installing & restarting worked for me.
