### ISSUE TITLE
SublimeJsPrettier remove the closing html tag by default

### ISSUE THREAD

**Issue by danglisheng** [jonlabelle/SublimeJsPrettier#124]
SublimeJsPrettier remove the closing html tag by default

**Comment by jonlabelle** [comment]
I'm guessing you're referring to the way the *undocumented* (or officially supported) HTML5 parser ([parse5](https://github.com/inikulin/parse5)) is formatting your HTML tags. But unfortunately, I can only redirect you over to Prettier's [issue board](https://github.com/prettier/prettier/issues) - and where you're more likely to find a workable solution.
