### ISSUE TITLE
useTabs setting ignored

### ISSUE THREAD

**Issue by JannieT** [jonlabelle/SublimeJsPrettier#125]
- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

### Explain the Issue and Expected Behavior

The package seems to ignore my custom Prettier setting for `useTabs` and `tabWidth`

### Prettier version

1.13.5

### JsPrettier Plug-in Version

1.20.24

### Platform Details

    - Sublime Text Version: 3.1.1
    - Sublime Text Build: 3176
    - Operating System Name: macOS
    - Operating System Version: 10.13.5

### Generated Prettier command line arguments

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier  \
  --stdin  \
  --no-config  \
  --print-width 80  \
  --single-quote false  \
  --trailing-comma es5  \
  --bracket-spacing true  \
  --jsx-bracket-same-line false  \
  --parser babylon  \
  --semi true  \
  --require-pragma false  \
  --prose-wrap preserve  \
  --arrow-parens avoid  \
  --tab-width 4  \
  --use-tabs true  \
  --stdin-filepath /Users/jannie/Desktop/uccf/src/js/index.js

```

### Is the same behavior observed when run against Prettier directly?

If I run it manually with `--use-tabs false` and `--tab-width 2` I get the desired result, otherwise it is the same

### The contents of your `User/JsPrettier.sublime-settings` file

```
{
	"debug": true,
	"auto_format_on_save": true,
	"prettier_options": {
		"useTabs": false,
		"tabWidth": 2,
		"trailingComma": "es5"
	}
}

```
### The contents of your `<project_name>.sublime-project` file (if applicable)

Not applicable

### Steps to reproduce the behavior

1. Create a javascript file with this contents:

`setTimeout(function(){ console.log('test')},1000)`

2. Save the file

### Expect to see

--tab-width 2 --use-tabs false
in the debug log and the console.log('test') line indented with 2 spaces

### Actually have

--tab-width 4 --use-tabs true 
in the debug log and the console.log('test') line indented with 1 tab

NOTE: as you can see the other custom overrides are respected, like trailingComma, for example.

**Comment by jonlabelle** [comment]
This is the intended behavior. `tabWidth` is always set using Sublime Text's `tab_size` setting for the current view/syntax.

**Comment by spacesuitdiver** [comment]
@jonlabelle I find this behavior when creating a new file in a project undesired as it ends up using the Sublime default until you reopen the file. Is it possible for us to flip the preference toward the `.prettierrc.js` in this scenario? I can make a feature request maybe if this is more appropriate. Thanks!
