### ISSUE TITLE
Making changes to css styled components inside jsx file causes cursor to jump to top of file

### ISSUE THREAD

**Issue by mitdemrad** [jonlabelle/SublimeJsPrettier#126]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

### Explain the Issue and Expected Behavior

Inside my *.jsx files I have code such as this utilizing styled-components:

```
const FloatMenu = styled.div`
  background-color: blue;
`
```

I also have the naomi sublime plugin installed so that css syntax highlighting inside these blocks works.

If I make a change such that my cursor is within the FloatMenu css when I save, the cursor always jumps to the top of the file. More specifically it jumps to the first import line. I get the following error in the sublime console:

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] stdin: SyntaxError: (postcss) CssSyntaxError Unknown word (3:17)
[error]   1 | // @flow
[error]   2 | 
[error] > 3 | import React, { Component } from "react";
[error]     |                 ^
[error]   4 | import type { RouterHistory } from "react-router-dom";
[error]   5 | import { Link } from "react-router-dom";
[error]   6 | import styled from "styled-components";

```
If I save with the cursor outside the styled component css my cursor will remain in the correct place.
If I change the file type to Babel > Javascript instead of Naomi > Javascript and save with cursor inside css my cursor remains in the correct place.

I noticed that JsPrettier runs with --parser **css** in failing scenario and with --parser **babel** in the cases that work as expected. 

Seems like the css translation is failing when trying to transform the javascript and then the following lines in JsPrettier.py is advancing the cursor to the first error:

```
if error_line != -1 and error_col != -1:
  scroll_view_to(view, error_line, error_col) 
```

I tried overriding parser option in prettier config files but looks like it is determined dynamically and takes precedence over the value in the config file.

In summary I would like to have both the functionality of Naomi and SublimeJsPrettier without having to scroll back down to the code I am changing every time I make a modification and save. 

### Prettier version

1.13.7

### JsPrettier Plug-in Version

1.20.24

### Platform Details

    - Sublime Text Version: 3.1.1
    - Sublime Text Build: 3176
    - Operating System Name: MacOS High Sierra
    - Operating System Version: 10.13.5
    

### Generated Prettier command line arguments
```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier 
  --stdin  \
  --config /Users/me/Projects/iaw/iaw-node/.prettierrc \
  --config-precedence cli-override \
  --parser css \
  --tab-width 2 \
  --use-tabs false \
  --stdin-filepath /Users/me/Projects/iaw/iaw-node/src/SessionPhotos.jsx

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] stdin: SyntaxError: (postcss) CssSyntaxError Unknown word (3:17)
[error]   1 | // @flow
[error]   2 | 
[error] > 3 | import React, { Component } from "react";
[error]     |                 ^
[error]   4 | import type { RouterHistory } from "react-router-dom";
[error]   5 | import { Link } from "react-router-dom";
[error]   6 | import styled from "styled-components";

Process finished with exit code 2
```

### Is the same behavior observed when run against Prettier directly?

Yes if --parser set to css

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

**Example JsPrettier.sublime-settings**

  ```
{
    "auto_format_on_save": true,
    "debug": true,
    "prettier_options": {
        "printWidth": 120,
        "tabWidth": 2,
        "singleQuote": true,
        "trailingComma": "none",
        "bracketSpacing": true,
        "jsxBracketSameLine": false,
        "parser": "babylon",
        "semi": true,
        "tabs": false
    }
}
    
```
### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Install SublimeJsPrettier plugin
    2. Install Naomi Sublime plugin
    3. Write a .jsx file with a mix of react components and styled component declarations
    4. Set the file type to Naomi > Javascript
    5. Place cursor inside styled component block
    6. Save file and cursor should jump to first line import React, { Component } from "react";

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
This is the intended behavior... scroll to the first detected syntax error.

**Comment by mitdemrad** [comment]
Got it. Intended behavior is for SublimeJsPrettier not to work on .jsx files that have a combination of javascript and css (styled components).

For My purposes I will hack a fix that works for me:

line 445 JsPrettier.py:

prettier_options.append('css') => prettier_options.append('css')
