### ISSUE TITLE
Add option to format entire file only?

### ISSUE THREAD

**Issue by sonaye** [jonlabelle/SublimeJsPrettier#13]
When saving a js file while having the auto-format-on-save flag set to true, the plug-in does its job wonderfully.

Now, if the save action was initiated while having a piece of code selected/highlighted, the plug-in for some reason overwrite the whole thing before formatting it and cause it to break. I find this issue to be very frustrating, it would be great if there was a workaround it.

Example:

Before:
![screen shot 2017-02-02 at 4 52 15 am](https://cloud.githubusercontent.com/assets/23000873/22534199/70b2394c-e903-11e6-9834-8321b2c85a51.png)
After:
![screen shot 2017-02-02 at 4 52 23 am](https://cloud.githubusercontent.com/assets/23000873/22534203/79d004f0-e903-11e6-984a-d2dbc74adba6.png)

This is specific to the plug-in and not to the formatter itself.

**Comment by jonlabelle** [comment]
will add to backlog... clear selections before save.

**Comment by sentience** [comment]
Clearing selections on save is probably a bit aggressive. I can think of many situations where I’d like to save the file but keep my selection(s).

I note that the [elm-format command](https://github.com/elm-community/Elm.tmLanguage/blob/master/elm_format.py) in the Elm Language Support package leaves active text selections alone when formatting on save, and it does not have this code corruption issue.

If possible, I’d suggest it would be preferable to get to the bottom of what’s causing the code corruption when invoking Prettier with an active text selection and fix the root cause.

**Comment by jonlabelle** [comment]
@sentience: At this time, I'm not able to reproduce this particular issue. Selections format perfectly on save for me, leaving the rest of the file in tact. Not saying that you haven't discovered an issue, but at this point it sounds like an edge case, possibly from a particular version of [prettier](https://github.com/jlongster/prettier).

> **NOTE:** I'm running ST3, macOS and prettier v0.13.1.

**Comment by sonaye** [comment]
I am using the exact same setup and the issue is still there. It is not related to prettier itself because when no text is selected no code is broken and formatting works perfectly, it has to be the plugin, do you have auto format on save enabled?

**Comment by jonlabelle** [comment]
Here's a demo... 
![ss](https://cloud.githubusercontent.com/assets/226837/22841323/be72950c-ef96-11e6-8021-f34728c6f254.gif)

**Comment by jonlabelle** [comment]
Can you create a [Gist](https://gist.github.com) of the code you're attempting to format... I'll try and reproduce on my end.

**Comment by sonaye** [comment]
The problem is present with any js code, it is not specific to any particular syntax. Here is a demo from my end:
![untitled](https://cloud.githubusercontent.com/assets/23000873/22841529/03552c6a-efe3-11e6-917e-29425dadc28e.gif)

maybe @sentience can confirm weather he is still having this issue as well?

**Comment by jonlabelle** [comment]
@sonaye: see my *js* [demo](https://github.com/jonlabelle/SublimeJsPrettier/issues/13#issuecomment-279046411) above.

**Comment by sonaye** [comment]
I did, i tried selecting multiple lines and the code indeed didn't break, it seems that only the selection of a portion of a line would break the code on save. Try selecting a word and format on save.

**Comment by jonlabelle** [comment]
That is the expected behavior. You need to at least have valid JavaScript code in your selection(s) for the formatting to work properly.

**Comment by sonaye** [comment]
Why would it be the expected behavior of the formatter to break the code? does the plugin also format on select-basis? if so, having the option to disable that would resolve this issue. right now every five minutes I would break my own code just because I clicked save and for some reason a word or a portion was selected, say I changed the hex of a color or something. not practical at all, to the extent that you would be better off running the formatter through the cli from time to time instead of having to deal with these interruptions.

**Comment by jonlabelle** [comment]
I can only suggest setting the [auto-format on save](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L23) setting back to the default value of  `false`.

**Comment by sonaye** [comment]
does the plugin also format on select-basis?

**Comment by jonlabelle** [comment]
@sonaye: Yup.

**Comment by sonaye** [comment]
Why not add an option to disable that feature to offer formatting the complete file only? convenient, no?

**Comment by jonlabelle** [comment]
I guess that would be an option.

**Comment by jonlabelle** [comment]
@sonaye, @sentience:  I just pushed [v1.1.5](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.1.5). It addresses the issue of extra line-breaks being carried over from the prettier cli on each selected region.

Let me know...

**Comment by sonaye** [comment]
Just tested it, no more new lines, but a semi-colon is still being added. even in the previous version, the piece that broke the code was mainly the semi-colon and not the new line.

**1.1.5**
before:
![screen shot 2017-02-11 at 12 45 03 am](https://cloud.githubusercontent.com/assets/23000873/22845405/767eac6a-eff3-11e6-8e6d-8115a7872f6b.png)

after:
![screen shot 2017-02-11 at 12 44 43 am](https://cloud.githubusercontent.com/assets/23000873/22845413/7f7e6d8c-eff3-11e6-910e-923d56a2d90d.png)

i appreciate the effort.

**Comment by jonlabelle** [comment]
Right... because it assumes the end of the selection is not terminated (with a `;`).

**Comment by jonlabelle** [comment]
@sonaye: [This release](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.1.7) should resolve the issue.

Let me know.

**Comment by sonaye** [comment]
Works great now, thanks!

**Comment by sonaye** [comment]
I should point out that with this new update (introduced with 1.1.5), sometimes the formatter would remove the last empty line in the file, which could cause some issues for some users.

**Comment by sonaye** [comment]
I am only pointing this out because my guess is that eventually someone will open an issue about it, i think if there was a way to restore the lines formatting to its previous state while preserving the new patch for the semi-colon thingy, we would have addressed it all.

**Comment by sonaye** [comment]
before:
![screen shot 2017-02-11 at 4 16 58 am](https://cloud.githubusercontent.com/assets/23000873/22849737/f968b16c-f010-11e6-8544-1a1ff97498e9.png)

after:
![screen shot 2017-02-11 at 4 16 40 am](https://cloud.githubusercontent.com/assets/23000873/22849742/fce4c8da-f010-11e6-944f-02f6e0b91794.png)

**Comment by sonaye** [comment]
Was this particular case addressed in 1.1.8? my observation was on 1.1.7.

**Comment by sentience** [comment]
Wonderful! Everything seems to be working for me on 1.1.8, and I can’t reproduce the missing newline issue that you were seeing, @sonaye.

I do think that formatting the entire file is definitely the way to go. Formatting just selection(s) is an interesting capability, but not very practical IMO.

Thanks for all your work on this, @jonlabelle!

**Comment by jonlabelle** [comment]
Anytime. And thanks for the feedback @sonaye and @sentience.

**Comment by sonaye** [comment]
@sentience for me it is still present in v1.1.9, [eol-last](http://eslint.org/docs/rules/eol-last).

**Comment by jonlabelle** [comment]
@sonaye: what is your Sublime Text setting for `ensure_newline_at_eof_on_save` set to?

**Comment by sonaye** [comment]
true

**Comment by jonlabelle** [comment]
so to confirm... there's an extra line break being added to then end of your selection(s), and or file?

**Comment by sonaye** [comment]
No, this has nothing to do with selection now. saving the file triggers the formatter which i found in some cases that it removes the last empty line in the file (see https://github.com/jonlabelle/SublimeJsPrettier/issues/13#issuecomment-279108633).

**Comment by jonlabelle** [comment]
Right, because the prettier cli will always return a line break at the end of the output (since prettier cli assumes the content being processed is an entire file); so I had to strip it to avoid duplicate line-breaks being inserted at EOF. Given the `ensure_newline_at_eof_on_save` setting is `true` for the working file, Sublime Text will handle inserting the final line-break if not present.

**Comment by sonaye** [comment]
the plugin overrides the `ensure_newline_at_eof_on_save` option in most cases, ending up many times with a file with no empty last line

**Comment by jonlabelle** [comment]
Works perfectly for me. Check this for me, and post back your response...

1. open or create a new JavaScript file in Sublime Text.
2. navigate to **Preferences** -> **Settings - Syntax Specific**.

> What is your specified value for **`ensure_newline_at_eof_on_save`**?

**Comment by sonaye** [comment]
I added it, `"ensure_newline_at_eof_on_save": true` was set under user settings not syntax specific. Thanks!
