### ISSUE TITLE
Add support for prettier-stylelint

### ISSUE THREAD

**Issue by seanders** [jonlabelle/SublimeJsPrettier#130]
It would be great if this plugin supported [Prettier-stylelint](https://github.com/hugomrdias/prettier-stylelint). I would be happy to take a stab at this if I can find some time.

**Comment by jonlabelle** [comment]
Sure... go ahead and create a PR.

**Comment by saltcod** [comment]
@seanders you haven't been able to find some time by chance have you?   :^(
