### ISSUE TITLE
Jsprettier does not format document when cursor is on same line as unformatted text

### ISSUE THREAD

**Issue by kaiser101** [jonlabelle/SublimeJsPrettier#134]
If the cursor is on the same line as the unformatted text, jsprettier:format code does not work.

Prettier version - 1.11.1
JsPrettier version - 1.20.0
Sublime Text version - 3.1.1 (Build 3176)
OS - Windows 7 64 bit

My JsPrettier user settings
`
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "js_prettier": {
      "debug": false,
      "prettier_cli_path": "C:/Users/amey/AppData/Roaming/npm/prettier",
      "node_path": "",
      "auto_format_on_save": false,
      "auto_format_on_save_excludes": [],
      "auto_format_on_save_requires_prettier_config": false,
      "allow_inline_formatting": false,
      "custom_file_extensions": [],
      "max_file_size_limit": -1,
      "additional_cli_args": {},
      "prettier_options": {
        "printWidth": 80,
        "singleQuote": false,
        "trailingComma": "none",
        "bracketSpacing": true,
        "jsxBracketSameLine": false,
        "parser": "babylon",
        "semi": true,
        "requirePragma": false,
        "proseWrap": "preserve",
        "arrowParens": "avoid"
      }
    }
  }
}
`

Is the same behaviour observed when running prettier from command line - NA

Steps to reproduce
1.
1. Add a derefencing statement like follows
`
const {comments,comment} = this.state
`
2. Run JsPrettier: Format Code from command palette with the cursor after the comma (i.e. comma after comments within the curly braces)
3. Expected output
`
const { comments, comment } = this.state;
`
4. Actual output, the content is not formatted.
`
const {comments,comment} = this.state
`

Same behaviour is observed for JSX elements.

**Comment by kaste** [comment]
Unfortunately, I cannot reproduce this (I followed the steps, and copy-pasted above 'prettier-options'). You could enable debug mode in the settings, and see what it prints in the Sublime console. Maybe updating prettier helps. I'm on v1.13.4 which is of course also outdated.

**Comment by kaiser101** [comment]
My bad, updating the prettier version resolved it. Thanks.
