### ISSUE TITLE
Missing Support for JSX Fragment Syntax

### ISSUE THREAD

**Issue by kyleshevlin** [jonlabelle/SublimeJsPrettier#136]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

### Explain the Issue and Expected Behavior

JsPrettier gets stuck on JSX's Fragment syntax

```
const Foo = () => (
	<>
		<div>foo</div>
		<div>bar</div>
	</>
)
```

Leads to the error:

```
stdin: SyntaxError: Unexpected token (23:8)
const Foo = () => (
       <>
        ^
			<div>foo</div>

Process finished with exit code 2
```

### Prettier version

1.14.2

### JsPrettier Plug-in Version

1.20.27

### Platform Details

ST3 on Mac OSX

### Generated Prettier command line arguments

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/kyle/.nvm/versions/node/v6.9.1/bin/node /Users/kyle/.nvm/versions/node/v6.9.1/bin/prettier --stdin --config /Library/WebServer/Documents/Work/secondcareerdevs/website-new/.prettierrc --config-precedence cli-override --parser babylon --tab-width 2 --use-tabs false --stdin-filepath /Library/WebServer/Documents/Work/secondcareerdevs/website-new/src/components/layout.js --cursor-offset 302

### Is the same behavior observed when run against Prettier directly?

Prettier supports the fragment syntax

### The contents of your `User/JsPrettier.sublime-settings` file

```
{
  "debug": false,
  "prettier_cli_path": "/Users/kyle/.nvm/versions/node/v6.9.1/bin/prettier",
  "node_path": "/Users/kyle/.nvm/versions/node/v6.9.1/bin/node",
  "auto_format_on_save": true,
  "auto_format_on_save_excludes": [
    "*/node_modules/*",
    "*/.git/*",
    "*.json",
    "*.scss",
    "*.md"
  ],
  "allow_inline_formatting": false,
  "custom_file_extensions": [],
  "additional_cli_args": {},
  "max_file_size_limit": -1,
  "prettier_options": {
    "printWidth": 80,
    "tabWidth": 2,
    "singleQuote": true,
    "trailingComma": "none",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "parser": "babylon",
    "semi": false
  }
}
```

### Steps to reproduce the behavior

1. Have some JSX, like my Foo component above, with Fragment syntax
2. Try to format, get error.

**Comment by jonlabelle** [comment]
I observed the same error when running the mentioned JSX fragment snippet from the command-line (no integration/JSPrettier).

**fragment-syntax-issue-136.js** file contents:

```jsx
const Foo = () => (
    <>
        <div>foo</div>
        <div>bar</div>
    </>
```

**Prettier CLI Command:**

```bash
prettier \
    --stdin \
    --no-config \
    --print-width 80 \
    --single-quote false \
    --trailing-comma none \
    --bracket-spacing true \
    --jsx-bracket-same-line false \
    --parser babylon \
    --semi true \
    --require-pragma false \
    --prose-wrap always \
    --arrow-parens avoid \
    --tab-width 4 \
    --use-tabs false \
    --stdin-filepath fragment-syntax-issue-136.js \
    < fragment-syntax-issue-136.js
```

**Result**

```
[error] stdin: SyntaxError: Unexpected token, expected "," (6:1)
[error]   4 |         <div>bar</div>
[error]   5 |     </>
[error] > 6 |
[error]     | ^
```

**Comment by jonlabelle** [comment]
@kyleshevlin... [your suggestion](https://github.com/jonlabelle/SublimeJsPrettier/issues/136#issuecomment-418812423) fixed the syntax error - however, I'm not able to reproduce the issue. Formatting works perfectly for me.

**Comment by kyleshevlin** [comment]
Well, that's a bummer. I guess I can try the classic, remove the package, reinstall the package, see what happens. Will report back when I do.

**Comment by kyleshevlin** [comment]
Sorry about that. I did try uninstalling and reinstalling JsPrettier and it still failed on this issue. However, I'm beginning to suspect it has to do with Babel. It appears that the syntax requires Babel 7 https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#babel and so it seems that this issue should be closed anyways.
