### ISSUE TITLE
Add support for Markdown

### ISSUE THREAD

**Issue by nikitavoloboev** [jonlabelle/SublimeJsPrettier#137]
I would like to add to have Sublime Text automatically format Markdown code I write on each save with Prettier.

**Comment by jonlabelle** [comment]
You just need to enable [auto_format_on_save](https://github.com/jonlabelle/SublimeJsPrettier/blob/1f1e1457a0cc68bb3e4a107cf4354f114420a529/JsPrettier.sublime-settings#L85).
