### ISSUE TITLE
Extra newlines are not removed

### ISSUE THREAD

**Issue by nip3o** [jonlabelle/SublimeJsPrettier#138]
### How to reproduce
* Format the file. 
* Add any number of newlines to the end of the file. 
* Re-format the file.

### Expected result
Any additional newlines are removed by the re-format (taking `ensure_newline_at_eof` into account), just as when running `prettier` on the file manually.

### Actual result
Newlines are not removed.

## Some thoughts
The cause lies somewhere around here:
https://github.com/jonlabelle/SublimeJsPrettier/blob/115864ebcdd46d3b9cb635f3fec8f7539e779120/JsPrettier.py#L300

The comparison between transformed code and the source are done without taking newlines into account, and newlines is the only thing that has changed/been removed in this case. I tried to shamelessly insert a `view.replace(edit, region, transformed)` in that case which solves the problem for me, but I don't fully understand the reason of doing this check in the first place so I feel that wouldn't be a very good fix.

**Comment by jonlabelle** [comment]
I cannot re-produce the issue you're having (extra lines not being removed at eof)... and you didn't follow the [ISSUE TEMPLATE](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md) when opening your issue.
