### ISSUE TITLE
Cannot find dyld library

### ISSUE THREAD

**Issue by jsheffers** [jonlabelle/SublimeJsPrettier#139]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [ ] **Explain the Issue and Expected Behavior**
- [ ] **Prettier version**
- [ ] **JsPrettier Plug-in Version**
- [ ] **Platform Details**
- [ ] **Generated Prettier command line arguments**
- [ ] **Is the same behavior observed when run against Prettier directly?**
- [ ] **Steps to reproduce the behavior**

---

### Explain the Issue and Expected Behavior

I'm getting a `dyld Library not loaded error`.  If I use the prettier cli it works properly, just not from sublime.  Here is the full error:

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.61.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found

Process finished with exit code -6

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.14.2

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.20.27",
    ...

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3
    - Sublime Text Build: 3175
    - Sublime Text Architecture: <SUBLIME_TEXT_ARCHITECTURE>
    - Operating System Name: Mac
    - Operating System Version: Mojave

### Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

**Example**

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command 
    -----------------------------------------

    /usr/local/bin/prettier           \
        --stdin                       \
        --color=false                 \
        --print-width 80              \
        --single-quote=true           \
        --trailing-comma none         \
        --bracket-spacing=true        \
        --jsx-bracket-same-line=false \
        --parser babylon              \
        --semi=true                   \
        --tab-width 4                 \
        --use-tabs=true
        
> **NOTE:** The back-slashes (`\`) in the example above will not be printed to the Console... and only provided here for legibility purposes. The full prettier command will be output to the Console with no line-breaks.

### Is the same behavior observed when run against Prettier directly?

**It works fine with the CLI, just not Sublime.**

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

**Empty**

### The contents of your `<project_name>.sublime-project` file (if applicable)

The entire contents of your ***User*** overridden JsPretter Project-level Settings, excluding the comments.

**Don't have a project file**

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Open a js file 
    2. Run the prettier formatter
    3. Open console to see the error.

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
Not sure on this one. Maybe something to do with Mojave (macOS preview) and Sublime Text?

**Comment by jsheffers** [comment]
Mojave is now released and I'm off beta, still have this issue.

**Comment by jsheffers** [comment]
For anyone who sees this, this was a symptom of using NVM for my node setup.   Sublime was looking for node at the following path `/usr/local/bin/node`, which was not there.  Updated in the JSPrettier settings and it worked.
