### ISSUE TITLE
Add support for project-specific "prettier_options"

### ISSUE THREAD

**Issue by sentience** [jonlabelle/SublimeJsPrettier#14]
Code style standards vary from project to project, so it would be helpful for the `"prettier_options"` setting to be configurable per-project, by including the settings in the .sublime-project file.

Example:
```js
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		// not here - this section overrides core Sublime Text settings
	},
	"prettier_options": {
		"singleQuote": true,
		"trailingComma": true
	}
}
```

Settings in the project file should override both the package default settings and the user settings file.

The JSON of the project file may be accessed via the Sublime Text API with `window.project_data()`.

**Comment by jonlabelle** [comment]
[Now available](https://github.com/jonlabelle/SublimeJsPrettier#project-level-settings).

**Comment by sentience** [comment]
Awesome! Thanks so much.
