### ISSUE TITLE
Closing tag position

### ISSUE THREAD

**Issue by firattale** [jonlabelle/SublimeJsPrettier#140]
hello, I have the latest jsprettier and sublime text 3 and I didnt change any default setting.

But it would be better for me if I can put the closing tag to the nearest attributes. let me show you.

When I use Jsprettier my input code goes like this:

						<input
							type="text"
							className="form-control"
							placeholder="Username"
							/>

But I think the below looks better.

						<input
							type="text"
							className="form-control"
							placeholder="Username"/>

Is there any way to change position of closing tag by default, otherwise I am doing it manually.

Thank a lot.

**Comment by jonlabelle** [comment]
Hi @firattale. You will need to submit your request for [Prettier](https://github.com/prettier/prettier/issues) for review. JsPrettier is only a SublimeText plug-in/integration for Prettier - and simply passes commands to Prettier (CLI) for formatting.
