### ISSUE TITLE
Prettier not found in project node_modules when using --no-bin-links

### ISSUE THREAD

**Issue by edmorley** [jonlabelle/SublimeJsPrettier#146]
### Explain the Issue and Expected Behavior
In some scenarios [0] it is necessary to use the `--no-bin-links` option with yarn (and similar for npm) to prevent the creation of symlinks in the `node_modules/.bin/` directory. 

For projects that have to do this, SublimeJsPrettier currently fails to find Prettier in the project's `node_modules` directory, since it currently relies on the presence of `node_modules/.bin/prettier` rather than looking for `node_modules/prettier/prettier-bin.js`.

It would be great to either:
1. Check for `node_modules/prettier/prettier-bin.js` instead of `node_modules/.bin/prettier`
2. Check for `node_modules/prettier/prettier-bin.js` as well as `node_modules/.bin/prettier`

Option (2) would likely mean a redundant check most of the time, but would be more resilient in case Prettier ever changed the [location of their bin script](https://github.com/prettier/prettier/blob/835f4c05b061ac93d36b3323ce261e842e2f6445/scripts/build/build.js#L79) within the package.

### Prettier version
1.15.2

### JsPrettier Plug-in Version
1.21.3

### Platform Details
    - Sublime Text Version: 3
    - Sublime Text Build: Dev channel 3180
    - Sublime Text Architecture: None shown on the ST about dialogue; not clear where to find
    - Operating System Name: Windows
    - Operating System Version: 10
    - Operating System Architecture: x64

### Generated Prettier command line arguments
N/A since:
```
JsPrettier [ERROR]: Ensure 'prettier' is installed in your environment PATH, or manually specify an absolute path in your 'JsPrettier.sublime-settings' file and the 'prettier_cli_path' setting.
```

### Is the same behavior observed when run against Prettier directly?
N/A since this is about the plugin specifically.

### The contents of your `User/JsPrettier.sublime-settings` file
No custom user settings.
    
### The contents of your `<project_name>.sublime-project` file (if applicable)
No custom project settings.

### Steps to reproduce the behavior
1. `mkdir test && cd test`
2. `echo '--*.no-bin-links true' > .yarnrc`
3. `yarn add prettier@1.15.2`
4. `touch foo.js`
5. Open `foo.js` in Sublime Text that has this plugin installed
6. Open ST command palette and type/select "JsPrettier: Format Code"
7. Check ST console for errors

[0] For projects that use Vagrant for development, it's common to have the project directory be shared from the Virtualbox VM back to the host using Virtualbox's shared folders. However when the guest OS is Linux and the host Windows, any attempt to create a symlink in that shared folder will fail, since Virtualbox doesn't yet handle them correctly (even now they are now supported in Windows 10). Most of the time this isn't a problem since the project's source directory won't contain symlinks. However yarn/npm will create symlinks in the `node_modules/.bin/` directory (since they see the guest OS supports symlinks) unless instructed not to via `--no-bin-links` or similar. As such, in these cases it's necessary to force no bin links in `.yarnrc`, so that developers on all platforms have a working Vagrant environment.

**Comment by jonlabelle** [comment]
Why not just specify the path in your [user settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L50)?

**Comment by edmorley** [comment]
Hi :-)

The project is used by many developers (including outside contributors), who won't know they need to customise their settings due to the use of `--no-bin-links`. We can try and document the workaround, however additional manual steps are more busy-work for someone trying to set up a development environment, and docs aren't always read fully anyway.

At the moment the VSCode Prettier plugin works out of the box with the project (presumably since it uses Node.js module resolution), just not `SublimeJsPrettier` (since understandably it can't use native module resolution).

**Comment by jonlabelle** [comment]
Makes sense. I'll try to work this in shortly. Seems straight forward enough.

**Comment by jonlabelle** [comment]
Give it a whirl and let me know!

**Comment by edmorley** [comment]
Thank you for the new release! I tried it out but the plugin was unable to find Prettier. I've left some comments on the change :-)
https://github.com/jonlabelle/SublimeJsPrettier/commit/18abf12b8e9bc80714557692f3bdb1563a83c612#r31405759

**Comment by edmorley** [comment]
Sorry for not spotting this before, but the filename is `bin-prettier.js` rather than `prettier-bin.js` - I typoed it above, my bad.

Also do you have any thoughts about:
https://github.com/jonlabelle/SublimeJsPrettier/commit/18abf12b8e9bc80714557692f3bdb1563a83c612#r31405938

**Comment by jonlabelle** [comment]
All [set](https://github.com/jonlabelle/SublimeJsPrettier/commit/1c717cdf18e99ff34c738058234dfd95d47339bb).

**Comment by edmorley** [comment]
Many thanks! :-)
