### ISSUE TITLE
Path variables to settings not expanded

### ISSUE THREAD

**Issue by bitst0rm** [jonlabelle/SublimeJsPrettier#148]
`JsPrettier.sublime-settings`
```
"additional_cli_args": { "--config": "${packages}/myfolder/config/prettierrc.json" }
```
path variables `${packages}` will not be expanded and JsPrettier will fail to work. It happens to all items in setting file. Using path variables is much flexibler than fixed path, e.g for those who would like to use the same settings file on other devices. A fix would be:

In `sthelper.py` change line [L28](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/jsprettier/sthelper.py#L28) from:
```
def get_setting(view, key, default_value=None):
...
    project_value = _get_project_setting(key)
    if project_value is None:
        return value
    return project_value
```
to:
```
    project_value = _get_project_setting(key)
    if project_value is None:
        # Expanding variables: https://www.sublimetext.com/docs/3/build_systems.html#variables
        variables = sublime.active_window().extract_variables()
        value = sublime.expand_variables(value, variables)
        return value
    return project_value
```
maybe you should change the same things to `def get_sub_setting`, `def _get_project_setting` ... too
your code style is badly to looking through ;)

**Comment by jonlabelle** [comment]
Hi @bitst0rm... can you create a Pull Request for this please?
