### ISSUE TITLE
JsPrettier error in Vue.js single file components.

### ISSUE THREAD

**Issue by asamolion** [jonlabelle/SublimeJsPrettier#149]
## Reporting an Issue

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] stdin: TypeError: options.locStart is not a function
[error]     at Object.findNodeAtOffset (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:10017:23)
[error]     at coreFormat (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:10203:32)
[error]     at format (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:10369:16)
[error]     at formatWithCursor (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:10381:12)
[error]     at Object.formatWithCursor (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:31224:15)
[error]     at format$1 (/home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:33227:21)
[error]     at /home/osama/workspace/vue-realworld-example-app/node_modules/prettier/bin-prettier.js:33321:28
[error]     at <anonymous>
[error]     at process._tickCallback (internal/process/next_tick.js:188:7)
```

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

### Explain the Issue and Expected Behavior

I tried to check JsPrettier's support for Vue.js single file components by cloning and running [vue-realworld-example-app](https://github.com/gothinkster/vue-realworld-example-app)
However, JsPrettier gave me an error on the first `App.vue` component located in `src/App.vue`

### Prettier version
1.15.3

### JsPrettier Plug-in Version
1.21.7

### Platform Details

    - Sublime Text Version: Sublime Text 3
    - Sublime Text Build: 3176
    - Sublime Text Architecture: x64
    - Operating System Name: Linux Mint
    - Operating System Version: 19.1
    - Operating System Architecture: x64

### Generated Prettier command line arguments
    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------
```
   /home/$USER/workspace/vue-realworld-example-app/node_modules/.bin/prettier --stdin 
   --config /home/osama/workspace/vue-realworld-example-app/.prettierrc 
   --config-precedence cli-override 
   --parser vue 
   --tab-width 4 
   --use-tabs false 
   --stdin-filepath /home/osama/workspace/vue-realworld-example-app/src/App.vue 
   --cursor-offset 263
```

### Is the same behavior observed when run against Prettier directly?
No. It just spits out the formatted code. I believe the running prettier directly is working fine.

### The contents of your `User/JsPrettier.sublime-settings` file

```
{
    "debug": true,
    "auto_format_on_save": true,
    "auto_format_on_save_requires_prettier_config": true,
    "auto_format_on_save_excludes": [
        "*/node_modules/*",
        "*/file.js",
        "*.json"
    ]
}
```
### The contents of your `<project_name>.sublime-project` file (if applicable)
Not applicable.

### Steps to reproduce the behavior

    1. Clone this repo. https://github.com/gothinkster/vue-realworld-example-app
    2. And open the folder in Sublime Text 3. 
    3. Open `src/App.vue` and lint using `JsPrettier`.

**Comment by jonlabelle** [comment]
Hi @asamolion... I was able to format perfectly, and I mirrored your config:

![issue-149-cannot-reproduce](https://user-images.githubusercontent.com/226837/51448260-e451c580-1cea-11e9-94ba-25f85e18027d.gif)
