### ISSUE TITLE
Jan 21 update stop jsPrettier working, unless user adds `disable_tab_width_auto_detection`

### ISSUE THREAD

**Issue by joshlangner** [jonlabelle/SublimeJsPrettier#154]
Latest release breaks. JsPrettier stops working unless User adds `disable_tab_width_auto_detection`

JsPrettier stopped working and I had to look at the changelog / commits to figure out what might have caused it. Turns out adding this flag to my user settings gets it working again. Seems like it's not properly picking up a project's default configs otherwise?

See: 

https://github.com/jonlabelle/SublimeJsPrettier/commit/827e17702e1e29e039209eb013081c0b63cc0d2d#diff-deb5e5e4c6cf7249beea03a4ed0570b7R189

**Comment by jonlabelle** [comment]
I @joshlangner. I cannot reproduce. You probably just needed to restart SublimeText.

**Comment by Sorgrum** [comment]
Had the same issue and can confirm that restarting Sublime Text fixed it.

**Comment by abhishiv** [comment]
I'm having the same issue, and restarting sublime text doesn't fix it.

**Comment by jonlabelle** [comment]
@abhishiv Try reinstalling the [package](https://packagecontrol.io/packages/JsPrettier) from Package Control.
