### ISSUE TITLE
Path expansion?

### ISSUE THREAD

**Issue by niksy** [jonlabelle/SublimeJsPrettier#155]
Is it possible to have path expansion in configuration files, e.g. `$HOME` and `~` which resolve to user directory?

**Comment by jonlabelle** [comment]
Expanding [environment vars](https://docs.python.org/2/library/os.path.html#os.path.expandvars) and the [user's path](https://docs.python.org/2/library/os.path.html#os.path.expanduser) is pretty straight forward. However, the Sublime Text 2 API doesn't support extracting/expanding application-level vars (via `window.extract_variables()` and `sublime.expand_variables()` methods); which I'm sure would also be desired; e.g.:

```
>>> sublime.expand_variables("The current file is: ${file}", window.extract_variables())
'The current file is: /path/to/file.js'
```

Let look into it.
