### ISSUE TITLE
Jan 25 update (1.23.0) breaks jsPrettier, unless user has Prettier 1.16 installed

### ISSUE THREAD

**Issue by joshlangner** [jonlabelle/SublimeJsPrettier#156]
We're using an older version of Prettier. Because of the way Sublime auto-pushes, ALWAYS, the very latest updated plugins to the SublimeText, all users will have received this new version. If they don't have Prettier 1.16 installed, this breaks for them. 

This was difficult to track down as the issue, because when SublimeText runs updates it's often hard to see the update message (it may appear in unfocused tabs etc.).

**Comment by jonlabelle** [comment]
Not much else I can do... but the notice was [posted](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/messages/1.23.0.txt), and indicated in the [Changelog](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/CHANGELOG.md#1230).
