### ISSUE TITLE
Error: Couldn't resolve parser "babel"

### ISSUE THREAD

**Issue by ghdna** [jonlabelle/SublimeJsPrettier#157]
Since Jan 25, this package is breaking on Sublime 3 with following error:

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[warn] Ignored unknown option `--html-whitespace-sensitivity=css`.
[error] Error: Couldn't resolve parser "babel"

Process finished with exit code 1
```
NPM versions:
* prettier@1.16.1
* babel-cli@6.26.0
* babel@6.23.0

Sublime Packages:
* Babel@8.6.3
* JSPrettier@1.23.1

OSX 10.13.6

Any suggestions?

**Comment by Twizzeld** [comment]
I reinstalled the npm package prettier and it started working for me.
`npm install -g prettier`

Hope that helps.

**Comment by ghdna** [comment]
It did kind off started working after several hours of trying too many things, including reinstalling everything. So I don't know know what clicked but it does work now.

**Comment by lamartire** [comment]
Same problem here! 🚨

**Comment by jasonwzw** [comment]
Same problem here! On Unubtu 16
```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] Error: Couldn't resolve parser "babel"

Process finished with exit code 1
```
Everything was all right yesterday!What happened!

**Comment by zaqisilverano** [comment]
Same problem here.

**Comment by ryanyu104** [comment]
Same problem here.

**Comment by lkomar** [comment]
Try to remove the `prettier` package from your `package.json` file, either by `yarn remove` or `npm uninstall`, then install it again, this worked for me

**Comment by ivanbanov** [comment]
Just point out, the PR which introduced the error was merged 3 days ago
https://github.com/jonlabelle/SublimeJsPrettier/commit/f5fd07b25aad5793540094dff820d085254b1a72

As a workaround, you can install prettier globally and configure sublime to use the global one

**Terminal**
```bash
npm install -g prettier
which prettier
# /usr/local/bin/prettier
```

**Sublime prettier config**
```json
{
  "auto_format_on_save": true,
  "prettier_cli_path": "/usr/local/bin/prettier"
}
```

I think that it would be nice to be in the README `Plugin compatible with Prettier >= 16`
