### ISSUE TITLE
There is not JsPrettier in Package Contol

### ISSUE THREAD

**Issue by John-Dim** [jonlabelle/SublimeJsPrettier#158]
I am searching in Package Control for JsPrettier but the world 'JsPrettier' does not return Results

<img width="700" alt="screenshot 2019-01-28 at 12 38 35" src="https://user-images.githubusercontent.com/29233861/51831062-f12d7500-22f9-11e9-988c-5f99cbf4109e.png">

**Comment by jonlabelle** [comment]
Sounds like a problem with Package Control. But it works fine for me.
