### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by ekulabuhov** [jonlabelle/SublimeJsPrettier#16]
Hi! Thank you for the plugin, it works great! Could you add a shortcut key? Invoking Prettier through the menu is pretty slow. Thanks!

**Comment by sonaye** [comment]
You can easily add a custom key to your keymap bindings `{ "keys": ["super+b"], "command": "js_prettier" }`, works for me.

**Comment by jonlabelle** [comment]
That's my suggestion also. I don't want to clobber any existing kb commands... as the most memorable one's are already bound.

**Comment by ekulabuhov** [comment]
I see, makes sense. Maybe you could include @sonaye's tip under https://github.com/jonlabelle/SublimeJsPrettier#usage? It might save some time for new users as it's not obvious how to do it.

**Comment by jonlabelle** [comment]
@ekulabuhov: [Done](https://github.com/jonlabelle/SublimeJsPrettier#custom-key-binding).
