### ISSUE TITLE
How to disable formatting html code

### ISSUE THREAD

**Issue by notiv-nt** [jonlabelle/SublimeJsPrettier#162]
### Explain the Issue and Expected Behavior

I have a `.vue` file, and i don't want to format html there (only html). Vscode has `prettier.disableLanguages: ["html"]`.

But this plugin has only `"auto_format_on_save_excludes": ["*.html"]` (file extension).

1) Prettier: `1.16.4`
2) Sublime v3.1.1 (3176)
3) MacOS 10.14.3

`User/JsPrettier.sublime-settings`

```json
{
  "auto_format_on_save": true
}
```

### Steps to reproduce the behavior

1. Create `.vue` file.
2. Write something
3. `ctrl+shift+p` > format > enter
4. look at the awful formatted html ((((

### Input:

```
<template>
<div>

  <nav class="nav">

    <a href="#">
      <span>
        text
        <i>text</i>
      </span>
    </a>

  </nav>

</div>
</template>

<script>

            export default {
          data:() => ({a: 10,b:30})
}
</script>

<style>
.nav{
                color: red;
ththt:ththth;
}
</style>
```

### Output:

```
<template>
  <div>
    <nav class="nav">
      <a href="#">
        <span>
          text

          <i>text</i>
        </span>
      </a>
    </nav>
  </div>
</template>

<script>
export default {
  data: () => ({ a: 10, b: 30 })
};
</script>

<style>
.nav {
  color: red;
  ththt: ththth;
}
</style>
```

### I need:

```
<!-- as is -->
<template>
<div>

  <nav class="nav">

    <a href="#">
      <span>
        text
        <i>text</i>
      </span>
    </a>

  </nav>

</div>
</template>

<!-- formatted -->
<script>
export default {
  data: () => ({ a: 10, b: 30 })
};
</script>

<!-- formatted -->
<style>
.nav {
  color: red;
  ththt: ththth;
}
</style>
```

![feb-27-2019 9-33-55 pm](https://user-images.githubusercontent.com/10743009/53514018-c93b5800-3ad7-11e9-9eb6-907f407ca8d5.gif)
![feb-27-2019 9-35-56 pm](https://user-images.githubusercontent.com/10743009/53514025-cc364880-3ad7-11e9-9782-b3b454d706aa.gif)

**Comment by jonlabelle** [comment]
Though I'm not going to intro. such an enhancement at *this time*, I do have work-around:

1. Add the `*.vue` file extension to your JsPrettier.sublime-settings [excludes](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L123), e.g.:

    ```
    "auto_format_on_save_excludes": ["*.vue"]
    ```

2. Hight/select only what you want to format in the vue file, then **JsPrettier Format Code**.

**Comment by notiv-nt** [comment]
Not cool
