### ISSUE TITLE
Respect `disable_tab_width_auto_detection` when Prettier config is present

### ISSUE THREAD

**Issue by schrodincat** [jonlabelle/SublimeJsPrettier#164]
### Explain the Issue and Expected Behavior
By default JsPrettier derives `tabWidth` Prettier option from indentation detected by Sublime Text (which is controlled by `disable_tab_width_auto_detection` setting). However, if there is a Prettier config file present, this setting isn't respected instead falling back to Prettier default setting `tabWidth: 2` even if `tabWidth` isn't set in Prettier config file.

It is expected for JsPrettier to obey `disable_tab_width_auto_detection` parameter unless `tabWidth` is set in Prettier config file as described in [`README.md`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/README.md#prettier-configuration-files).

### Prettier version
`1.16.4`

### JsPrettier Plug-in Version
`1.25.0`

### Platform Details

  - Sublime Text Version: `3.2`
  - Sublime Text Build: `3200 `
  - Sublime Text Architecture: `x64`
  - Operating System Name: `macOS`
  - Operating System Version: `10.14.3 (18D109)`
  - Operating System Architecture: `x64`

### Generated Prettier command line arguments

```
[JsPrettier DEBUG]: Prettier config file discovered at '/Users/schrodinger_cat/.prettierrc.json'

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier --stdin --config /Users/schrodinger_cat/.prettierrc.json --config-precedence cli-override --parser babel --use-tabs false --stdin-filepath /Users/schrodinger_cat/Documents/Source/macos/dotfiles/Library/Scripts/Applications/Transmit/SyncFavourite.js --loglevel debug --cursor-offset 706

Prettier reported the following output:

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"/Users/schrodinger_cat/.prettierrc.json","config-precedence":"cli-override","parser":"babel","stdin-filepath":"/Users/schrodinger_cat/Documents/Source/macos/dotfiles/Library/Scripts/Applications/Transmit/SyncFavourite.js","loglevel":"debug","cursor-offset":706,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0}
[debug] load config file from '/Users/schrodinger_cat/.prettierrc.json'
[debug] loaded options `{"semi":false,"singleQuote":true}`
[debug] applied config-precedence (cli-override): {"filepath":"/Users/schrodinger_cat/Documents/Source/macos/dotfiles/Library/Scripts/Applications/Transmit/SyncFavourite.js","cursorOffset":706,"parser":"babel","semi":false,"singleQuote":true,"useTabs":false}

Prettier process finished with exit code 0.
```
### Is the same behavior observed when run against Prettier directly?
Yes.

### The contents of your `User/JsPrettier.sublime-settings` file
Empty.

### The contents of your `<project_name>.sublime-project` file
Empty.

### The contents of your `.prettierrc.json` file
Doesn't contain `tabWidth` parameter:
```
{
    "semi": false,
    "singleQuote": true
}
```

### Steps to reproduce the behavior

1. Create Prettier config file without `tabWidth` parameter set.
2. Omit `disable_tab_width_auto_detection` parameter or set it to `false` in JsPrettier settings.
3. Open file where Sublime Text detects indentation `4`.
4. Use JsPrettier to format file.

**Comment by schrodincat** [comment]
My motivation is to have one system-wide Prettier config file which would control some Prettier settings for all editors and tools I use

**Comment by schrodincat** [comment]
Actually I read [`README.md`](https://github.com/jonlabelle/SublimeJsPrettier#prettier-configuration-files) file and it's implied that this is should be already the case. So I guess this is a bug.

**Comment by jonlabelle** [comment]
Hi @schrodincat. Because you're not specifying a tabWidth anywhere in a config, or passing it cli arg, and disabled tabWidth auto-detection - Prettier will implicitly set the default value for you... which is [two](https://prettier.io/docs/en/options.html#tab-width).

**Comment by schrodincat** [comment]
> ...and disabled tabWidth auto-detection

@jonlabelle but I haven't disabled `tabWidth` auto-detection, that's the point. Even when I'm explicitly adding `"disable_tab_width_auto_detection": false` to the `User/JsPrettier.sublime-settings` it still uses `tabWidth: 2`.

**Comment by jonlabelle** [comment]
Ah I see now. I guess because the plug-in detected a prettier config file in your $HOME path; so the expectation is that you'll have it configured there. The plug-in doesn't actually parse prettier config files, just sends them along as a CLI arg (when appropriate).

Let me think about this one.

**Comment by schrodincat** [comment]
>Ah I see now. I guess because the plug-in detected a prettier config file in your $HOME path; so the expectation is that you'll have it configured there. The plug-in doesn't actually parse prettier config files, just sends them along as a CLI arg (when appropriate). ...

@jonlabelle I guess the only way to fix this is to test for existence of `tabWidth` parameter in a Prettier config file.

**Comment by jonlabelle** [comment]
I going to defer this request, at least for now. It seems like an edge case in the fact that you would have a prettier config file defined, but have excluded the tabWidth option.

Not to mention, I'm really not interested in bloating up the codebase with the various [config](https://prettier.io/docs/en/configuration.html) parsing libs that that Prettier supports.

**Comment by schrodincat** [comment]
@jonlabelle I agree that it's probably not important enough to include parser. There is still need to fix [respective section in README](https://github.com/jonlabelle/SublimeJsPrettier#prettier-configuration-files), since it's misleading, though.

**Comment by schrodincat** [comment]
Especially since the plugin seem to be already ignoring `parser` and `useTabs` settings:

> /usr/local/bin/prettier --stdin --config /Users/schrodinger_cat/.prettierrc.json --config-precedence **cli-override --parser babel --use-tabs false** --stdin-filepath /Users/schrodinger_cat/Documents/Source/macos/dotfiles/Library/Scripts/Applications/Transmit/SyncFavourite.js --loglevel debug --cursor-offset 706
