### ISSUE TITLE
Feature Request: override default file-extensions

### ISSUE THREAD

**Issue by santyclaz** [jonlabelle/SublimeJsPrettier#166]
There are file extensions in the default auto-format file extension list that I do NOT want (in my case `css`, `scss`).

One idea is if the default list could be overridden, ideally with support as a project-level setting as well.

Right now the default set of file extensions Sublime JsPrettier will auto-format is hardcoded:
https://github.com/jonlabelle/SublimeJsPrettier/blob/42522e4722a198d313d201751df4432d2ed1d9c3/jsprettier/const.py#L88-L104

**Comment by jonlabelle** [comment]
Just add the extensions/patterns to your [excludes](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L123).

**Comment by santyclaz** [comment]
Yeah that works, and is what I've been doing. The only reason I was suggesting this white-list approach is for a convenient guarantee that any future additions to the current default list will not cause issues.

Very minor, and I totally understand if you'd prefer not to bother with it.
