### ISSUE TITLE
Trailing comma setting not valid for PHP

### ISSUE THREAD

**Issue by defmonk0** [jonlabelle/SublimeJsPrettier#167]
When running against a PHP file, as expected, the plugin passes along the prettier settings from the config file. Among those settings is a `trailingComma` setting, which is listed as being set to "none", "all", or "es5". 

For the PHP formatter of prettier, "es5" is not valid, but things like "php5" or "php7.2" are. As such, when using the "es5" setting, the plugin throws an error when attempting to format a file. There probably has to be another option added to the plugin so you can make a different choice when formatting PHP vs JS, and pass the appropriate one along.

Prettier Version: 1.16.4
Plugin Version: 1.26.2
Sublime Version: 3.2 - 3200 (Windows 10 x64)

Generated CMD:
```
C:\Users\steve\AppData\Roaming\npm\prettier.cmd --stdin --no-config --print-width 80 --tab-width 4 --single-quote false --trailing-comma es5 --bracket-spacing true --jsx-bracket-same-line false --parser php --semi true --require-pragma false --prose-wrap preserve --arrow-parens avoid --html-whitespace-sensitivity css --use-tabs false --stdin-filepath <<SNIP PATH>>\Fsraffle.php --loglevel debug --cursor-offset 356
```

Output Error:
```
[error] Invalid --trailing-comma value. Expected "all", "none", "php5" or "php7.2", but received "es5".
```

JsPrettier Settings:
```
{
    "additional_cli_args": {},
    "allow_inline_formatting": false,
    "auto_format_on_save": false,
    "auto_format_on_save_excludes": [],
    "auto_format_on_save_requires_prettier_config": false,
    "custom_file_extensions": [],
    "debug": true,
    "disable_tab_width_auto_detection": false,
    "max_file_size_limit": -1,
    "node_path": "",
    "prettier_cli_path": "",
    "prettier_options": {
        "arrowParens": "avoid",
        "bracketSpacing": true,
        "htmlWhitespaceSensitivity": "css",
        "jsxBracketSameLine": false,
        "parser": "babel",
        "printWidth": 80,
        "proseWrap": "preserve",
        "requirePragma": false,
        "semi": true,
        "singleQuote": false,
        "tabWidth": 4,
        "trailingComma": "es5"
    }
}
```

**Comment by jonlabelle** [comment]
You will need to update your config(s) [accordingly](https://github.com/prettier/plugin-php#configuration) to conform to the requirements of Prettier PHP.

**Comment by defmonk0** [comment]
I'm going to toss [this link](https://github.com/prettier/plugin-php/issues/964) here for anyone else looking for it. This actually seems to be a bug in the PrettierPHP plugin. They're overriding how the trailing-space option from the default prettier, which they shouldn't be. It's supposed to be fixed in an upcoming version.
