### ISSUE TITLE
Add options for eslint, tslint and stylelint

### ISSUE THREAD

**Issue by tobiastimm** [jonlabelle/SublimeJsPrettier#169]
First of all, thank you for the plugin!

I think it would be helpful, if the Sublime Plugin has kinda the same options like the VSCode Plugin for example.

Especially for eslint, tslint or stylelint integration.
```
prettier.eslintIntegration (default: false) - JavaScript and TypeScript only
Use prettier-eslint instead of prettier. Other settings will only be fallbacks in case they could not be inferred from ESLint rules.

prettier.tslintIntegration (default: false) - JavaScript and TypeScript only
Use prettier-tslint instead of prettier. Other settings will only be fallbacks in case they could not be inferred from TSLint rules.

prettier.stylelintIntegration (default: false) - CSS, SCSS and LESS only
Use prettier-stylelint instead of prettier. Other settings will only be fallbacks in case they could not be inferred from stylelint rules.
```

If this already works with the current plugin, at least a documentation of how to use with ... would be helpful

**Comment by jonlabelle** [comment]
Hi @tobiastimm... have you tried setting the *CLI* path of the eslint/tslint/stylelint integration as your [prettier_cli_path](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L61) setting?

Than you can add anything extra required by the integration (assuming it's a CLI arg) to your [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L238).

**Comment by tobiastimm** [comment]
@jonlabelle looks like it works, but i would prefer a bundled prettier-eslint
