### ISSUE TITLE
formatOnSaveTimeout option to prevent editor freeze when auto-formatting large json files

### ISSUE THREAD

**Issue by micahstubbs** [jonlabelle/SublimeJsPrettier#174]
**Is your feature request related to a problem? Please describe.**

When I have format on save turned on and I try to save a large json file, Sublime Text does not respond for several minutes while it formats the large json file.

**Describe the solution you'd like**

I would like a `formatOnSaveTimeout` like `prettier-vscode` has implemented https://github.com/prettier/prettier-vscode/issues/512 that would timeout format-on-save operations after a specified number of milliseconds.

(on closer inspection, this could be an editor level feature that VSCode offers, rather than a plugin level feature.  unclear about this.)

**Describe alternatives you've considered**

I've considered switching to VSCode 😅

**Comment by jonlabelle** [comment]
@micahstubbs: please use the [`max_file_size_limit`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L176) for such needs.

But I guess before you set the max file size limit, try simply [disabling](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L208) the cursor offset calculation... which is the ~~most likely~~ cause of the lock-ups.
