### ISSUE TITLE
Support for Ruby

### ISSUE THREAD

**Issue by volkanunsal** [jonlabelle/SublimeJsPrettier#175]
Can it support [prettier-ruby](https://github.com/prettier/plugin-ruby) plugin?

**Comment by jonlabelle** [comment]
It should... just follow the same guidelines outlined for [php](https://github.com/jonlabelle/SublimeJsPrettier#prettier-php).

**Comment by volkanunsal** [comment]
I've installed the plugin and added `rb` to `custom_file_extensions`. When I edit a Ruby file, it looks like prettier wants to use JS syntax rules, though.

**Comment by jonlabelle** [comment]
Make sure the plug-in supports [Prettier 1.17](https://prettier.io/blog/2019/04/12/1.17.0.html#add-an-option-to-modify-when-prettier-quotes-object-properties-5934-by-azz).

**Comment by volkanunsal** [comment]
Yup, it does.

https://github.com/prettier/plugin-ruby/pull/254

**Comment by volkanunsal** [comment]
Oh I think I figured it out. The version of my global prettier binary is 1.16.

**Comment by volkanunsal** [comment]
Spoke too soon. That didn't work. Now I get 

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

[error] stdin: SyntaxError: Unexpected character '#' (1:2)
[error] > 1 | # frozen_string_literal: true
[error]     |  ^
[error]   2 | 
[error]   3 | class ApplicationPolicy < Struct.new(:user, :record)
[error]   4 |   def index?
```
