### ISSUE TITLE
custom_file_extensions does not trigger format_on_save for multi dot extensions

### ISSUE THREAD

**Issue by bobmaerten** [jonlabelle/SublimeJsPrettier#176]
I would like to autoformat my JS file used in a Rails application for responding to XHR requests. By suffixing the js file with the template engine used in Rails, we can surcharge the generated JS.

Applying the format command with the palette works, but not autosave. Setting custom extension to `erb` works to, but I don't want to use prettier for all `erb` files.

Prettier version : 1.17.0
JsPrettier version: 1.27.0
User/JsPrettier.sublime-settings
```
  "debug": true,
  "auto_format_on_save": true,
  "custom_file_extensions": [
   "js.erb",
  ],
```

**Comment by jonlabelle** [comment]
Hi @bobmaerten. Have you tried using [Prettier for Ruby](https://github.com/prettier/plugin-ruby) - and setting your [prettier-cli path](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L61) to the ruby plug-in executable?

**Comment by bobmaerten** [comment]
Nope, it does not work either.
I tried installing with the npm package, same behaviour than without specifing prettier-cli path
running it from the command line resulted in `No parser could be inferred for file: update.js.erb`
did I miss something?

**Comment by jonlabelle** [comment]
Sounds like this enhancement, reasonably enough, should be handled by the core product - err, [Prettier for Ruby](https://github.com/prettier/plugin-ruby).
