### ISSUE TITLE
Allow formatting unsaved files

### ISSUE THREAD

**Issue by Svish** [jonlabelle/SublimeJsPrettier#177]
Would it be possible to allow formatting code that hasn't been saved to a file yet?

I'm using JSON Reindent in Sublime to for example quickly open a new file, paste in a bunch of JSON, and format it to make it easier to read. Would be great if I could use JsPrettier for this instead, especially since it supports other stuff as well, like HTML. 

I get the "JsPrettier: Format Code" option in the command palette, but I'm prompted with "File must be Saved." Could that requirement be avoided somehow? Do it in memory somehow? Or if a file is needed to pass to the `prettier` executable, could JsPrettier for example use a tmp file behind the scenes or something?

**Comment by jonlabelle** [comment]
Hi @Svish. Great suggestion, but implementing such a feature now would take quite a bit of effort to re-work parser detect/set logic - and this is first time such a request has come up.

However, if more people show interest... we can definitely re-visit the topic.

**Comment by mischnic** [comment]
I would use this often to format a snippet of code (instead of going to https://prettier.io/ and posting it there)

**Comment by coreyward** [comment]
@jonlabelle You're not exactly inviting others to weigh in when you close the issue. ;)

**Comment by jonlabelle** [comment]
@coreyward: topic is now pinned.
