### ISSUE TITLE
conflict with naomi/PHP7

### ISSUE THREAD

**Issue by jbach** [jonlabelle/SublimeJsPrettier#178]
Using JsPrettier on `.php`files using [naomi](https://github.com/borela/naomi/blob/26a04d91af34d37ff5372d056f232c823a668949/syntaxes/naomi.php7.sublime-syntax) for syntax highlighting sets parser to `html` instead of `php`

## Prettier version
1.17.0

## JsPrettier Plug-in Version
1.27.0

## Platform Details

    - Sublime Text Version: 3.2.1
    - Sublime Text Build: 3207
    - Operating System Name: Mac OS
    - Operating System Version: Mojave 10.14.4

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Open PHP file with PHP (Naomi) syntax
    2. Run JsPrettier

----
I’m not sure who’s at fault here. But `scopename` is set to `text.html embedded.php.php7 source.php.php7 keyword.embedded.begin.php.php7`, so fixing this requires:

1. switching `self.is_html(view)` calls with `self.is_php(view)` so php would be picked up before html
2. Also check for `contains('source.php.php7', scopename)` in `is_php`

I would make a PR, but wanted to confirm wether this should be fixed in JsPrettier or naomi?

**Comment by jonlabelle** [comment]
Hi @jbach. Just to confirm, you are using [Prettier PHP](https://github.com/prettier/plugin-php)... correct?

**Comment by jbach** [comment]
Yes. It works if I manually apply my fixes to JsPrettier.py. I’m guessing the root cause might be the `text.html` scopename. Otherwise `is_html` would return false and PHP would be detected by the file ending.

**Comment by jonlabelle** [comment]
I don't see an easy way around this... since as you mentioned, [naomi](https://github.com/borela/naomi/blob/26a04d91af34d37ff5372d056f232c823a668949/syntaxes/naomi.php7.sublime-syntax) is extending the "text.html" scope/syntax. JsPrettier detects HTML first which allows formatting of inlined HTML within PHP files; and without the need of a plug-in, e.g. Prettier PHP).
