### ISSUE TITLE
Allow scope: source.js in all file extensions

### ISSUE THREAD

**Issue by Rayraegah** [jonlabelle/SublimeJsPrettier#18]
The plugin is disabled on `.vue` and `.tag` files, which are similar to JSX files in vuejs and riotjs projects. The sublime syntax for `.vue` and `.tag` files mark script block as source.js

**Comment by viankakrisna** [comment]
Does prettier works on those files? I mean, have you tried `prettier --write` on those file and they format properly? If they worked, I have a pending pull request for `.jsx` in https://github.com/jonlabelle/SublimeJsPrettier/pull/19 . its just a matter of adding more extension there. Or better, make it user configurable. :)

**Comment by Rayraegah** [comment]
@viankakrisna refer to: https://github.com/jlongster/prettier/issues/651 @jlongster says its possible to extract the content in 'scope.js' of a file and then run prettier on it.

Here's an example with [CSSComb](https://github.com/csscomb/sublime-csscomb/blob/master/CSScomb.py), it extracts CSS from `<style></style>` tags, formats it and puts it back. The I/O system is the same as prettier i.e. text goes in formatted text comes out. Similarly in `.html`, `.vue` and `.tag` files the script is always in `<script></script>` tags and syntax always marks is as `scope.js` or `scope.js.embedded`.

I see a provision your code where you check for scope and it's been a while since I wrote a plugin for Sublime, but I can attempt to submit a PR for this.

**Comment by viankakrisna** [comment]
That would be really great! I need this on `.php` too, when the scripts are (sadly) inlined

**Comment by jonlabelle** [comment]
Another, simpler option might be to add a new [setting](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings) to allow inline formatting of arbitrary file and source types, instead of trying to sniff out all the different flavors of ECMAScript/JavaScript.

For example:

`allow_inline_formatting: true|false (default: false)`

Thoughts?

**Comment by viankakrisna** [comment]
Yes, but i think we should also make the setting for unusual file extensions like jsx, or even, mjs. I also have seen js running without any extensions to be called by *nix with special comments on top. Do you think we should keep a list? Or can we read the current syntax highliting, eg enable if current syntax is babel. The important thing is to make it work out of the box i think.

**Comment by Rayraegah** [comment]
> Another, simpler option might be to add a new setting to allow inline formatting of arbitrary file and source types

Yes. That would be perfect. Either by selecting text that is javascript or by sniffing out scope: source.js in files (these are usually marked by `<script>` tags). Right now you can't even run the plugin on non-js / jsx files :)

> Yes, but i think we should also make the setting for unusual file extensions like jsx, or even, mjs.
Second that. Some popular extensions I've seen where you'll find javascript: `ejs, tag, vue, tsx, msj, rjs, es6`

**Comment by jonlabelle** [comment]
@Rayraegah: do you want to take the lead on this one?

**Comment by Rayraegah** [comment]
Forked and giving it a go. Thus far, I've been able to successfully format JavaScript in HTML files and PHP (by selection). Give it a day or two :)

**Comment by Rayraegah** [comment]
Almost done.

One tiny problem is, `region` of `scope.js.embedded.html` also selects `<script>` and `</script>` tags in substring.

Not too familiar with the sublime text APIs. Any ideas?

**Comment by Rayraegah** [comment]
If you can test the scope at which <script> tag is detected in your source files and report it - it would help. I've logged them for `.tag` and `.vue` files. `.html`, `.php` files have no issues.

**Comment by jonlabelle** [comment]
Just a heads up... I did add support for formatting selections of code in any syntax; controlled via the [`allow_inline_formatting`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L33) setting.
