### ISSUE TITLE
JsPrettier should always use html parser for  .svelte file

### ISSUE THREAD

**Issue by trongthanh** [jonlabelle/SublimeJsPrettier#180]
I think [Svelte](https://svelte.dev/) doesn't need any introduction. Its component file *.svelte use a structure which is pretty compatible with *.html:

```html
<script>
	// logic goes here
</script>

<style>
	/* styles go here */
</style>

<!-- markup (zero or more items) goes here -->
```

Right now, when I try to format a .svelte document with this plugin, there are 3 scenarios:

- If my caret is in the HTML part, prettier uses `html` parser and this document is formatted correctly
- If my caret is in the <style> part, prettier uses `css` parser, and it will throw errors
- If my caret is in the <script> part, prettier uses `babel` parser,  and it will throw errors

## Prettier version

    $ prettier --version
    1.17.0

## JsPrettier Plug-in Version

Latest (by the time of this post)

## Platform Details

    - Sublime Text Version: 3.2
    - Sublime Text Build: 3208dev
    - Sublime Text Architecture: 64bit
    - Operating System Name: macOS Mojave 64bit

## `User/JsPrettier.sublime-settings` file

<details>
<summary>
User/JsPrettier.sublime-settings
</summary>

```json
{	
	"debug": true,
	"prettier_cli_path": "/usr/local/bin/prettier_d",
	"node_path": "",
	"auto_format_on_save": true,
	"auto_format_on_save_excludes": ["*/node_modules/*", "*.json", "*.html", "*.hbs"],
	"auto_format_on_save_requires_prettier_config": true,
	"allow_inline_formatting": true,
	"custom_file_extensions": ["svelte"],
	"max_file_size_limit": -1,
	"disable_tab_width_auto_detection": false,
	"disable_prettier_cursor_offset": true,
	"additional_cli_args": {
		"--plugin-search-dir": "$folder"
	},
	"prettier_options": {
		"printWidth": 100,
		"tabWidth": 2,
		"singleQuote": true,
		"trailingComma": "es5",
		"bracketSpacing": true,
		"jsxBracketSameLine": false,
		"parser": "html",
		"semi": true,
		"requirePragma": false,
		"proseWrap": "preserve",
		"arrowParens": "avoid",
		"htmlWhitespaceSensitivity": "css",
		"quoteProps": "as-needed"
	}
}
```

</details>

## Steps to reproduce the behavior

1. Install [Sublime Svelte](https://github.com/corneliusio/svelte-sublime) plugin
2. Create new *.svelte file with HTML contents or use [this example](https://svelte.dev/examples#dom-events).
3. Place the caret at different parts and execute Prettier format as described above.

**Comment by jonlabelle** [comment]
Hi @trongthanh. Can you try changing your `allow_inline_formatting` setting to `false`, and let me know the result. I'm just wondering if this setting might be conflicting with parsing detection.

Also, what is expected *parser* for `.svelte` files... e.g. `babel`?

**Comment by trongthanh** [comment]
Hi @jonlabelle,

I have tried `allow_inline_formatting: false` and getting the same behaviour as described above.

`.svelte` file, as of prettier 1.17.1, doesn't have its own parser, but it's a [compatible HTML syntax](https://svelte.dev/docs#Component_format). So I think, we can use `html` parser for it.

**Comment by jonlabelle** [comment]
Here's the solution based on [your setup](https://github.com/jonlabelle/SublimeJsPrettier/issues/180#issue-447440883) - and until Prettier natively infers the parser as html for `*.svelte` files...

In your Prettier [config file](https://prettier.io/docs/en/configuration.html), add the html parser override for *.svelte files:

```json
{
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "html"
      }
    }
  ]
```

Works like a charm!

Here's a working example project:
[jsprettier-issue-180-svelte-files.zip](https://github.com/jonlabelle/SublimeJsPrettier/files/3245573/jsprettier-issue-180-svelte-files.zip)
