### ISSUE TITLE
JSPrettier inheriting wrong config

### ISSUE THREAD

**Issue by ryami333** [jonlabelle/SublimeJsPrettier#181]
Using the latest version of JsPrettier released a couple of hours ago, the plugin now inherits a config from an ancestral directory rather than the one at the root of my project. Eg:

`/foo/.prettierrc` is getting implemented.
`/foo/bar/baz` is my project root (and Sublime workspace)
`/foo/bar/baz/prettier.config.js` is being ignored/trumped by the ancestral config.

Using all default plugin settings, except have toggled `auto_format_on_save` to `true`.

**Comment by ryami333** [comment]
Actually, it looks like it's not inheriting a config at all. Will close and open a new issue.

**Comment by ryami333** [comment]
Sorry, I was right the first time.

**Comment by ryami333** [comment]
While troubleshooting, I've determined that there seems to be an issue with the weight that different config names are given.

| Ancestral Config | Project Config | JSPrettier uses: |
| --- | --- | --- |
| none | `prettier.config.js` | Project (correct) |
| `.prettierrc` | `prettier.config.js` | Ancestral (incorrect) |
| `.prettierrc` | .prettierrc` | Project (correct) |

So it would seem that if there's an ancestral `.prettierrc` it always trumps `prettier.config.js`, which is unexpected behaviour (Prettier CLI does not behave resolve configs this way).

**Comment by ryami333** [comment]
Yes, [here's the culprit](https://github.com/jonlabelle/SublimeJsPrettier/blob/402179ea835a82ce1d6b9fa8423415605be9c7ba/jsprettier/util.py#L52).

The config resolution current checks one filename at a time, but it should instead check one directory at a time (for any/every config).

**Comment by jonlabelle** [comment]
Hi @ryami333. JsPrettier performs Prettier config resolution in order to support [auto-formatting](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L126) only when Prettier config files are discovered.

This feature was introduced [last February](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/CHANGELOG.md#1200), so I'm going to assume the issue you're having now is coincidental.

Did you restart Sublime Text after the update from Package Control?

Have you tried tried re-installing the plug-in? Maybe something was corrupted while updating.

**Comment by ryami333** [comment]
> Maybe something was corrupted while updating

I'm not suggesting that this problem is related to the new release, was just pre-empting any "what version are you using?" questions by bumping to the latest.

>  I'm going to assume the issue you're having now is coincidental.

Are you saying that you are unable to recreate this issue or just that you presume it _should_ work? I'm AFK again now unfortunately so I'll have to confirm whether or not re-installing solves the problem, but I strongly suspect that there's no coincidence that I found that code which correlates to the exact behaviour I described. Ockham's razor 😛

I haven't tried the 'auto_format_on_save_requires_config' flag yet, so I'll have to give that a go too, but note that it would only be a workaround, not a fix.

**Comment by ryami333** [comment]
@jonlabelle. I've just confirmed that reinstalling + restarting does not fix the issue, nor does enabling the `auto_format_on_save_requires_config_file` flag. Here's the console output with debug enabled:

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/foo/bar/baz/node_modules/.bin/prettier --stdin --config /foo/.prettierrc --config-precedence cli-override --parser typescript --use-tabs false --ignore-path /foo/bar/baz/.prettierignore --stdin-filepath /foo/bar/baz/Foo.tsx --loglevel debug --cursor-offset 365

Prettier reported the following output:

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"/foo/.prettierrc","config-precedence":"cli-override","parser":"typescript","ignore-path":"/foo/bar/baz/.prettierignore","stdin-filepath":"/foo/bar/baz/Foo.tsx","loglevel":"debug","cursor-offset":365,"plugin-search-dir":[],"plugin":[],"debug-repeat":0}
[debug] load config file from '/foo/.prettierrc'
[debug] loaded options `{"useTabs":false,"tabWidth":4,"endOfLine":"lf","proseWrap":"always"}`
[debug] applied config-precedence (cli-override): {"filepath":"/foo/bar/baz/Foo.tsx","cursorOffset":365,"endOfLine":"lf","parser":"typescript","proseWrap":"always","tabWidth":4,"useTabs":false}

Prettier process finished with exit code 0.
```

Note that is is using the `/foo/.prettierrc` file, despite the existence of a `/foo/bar/baz/prettier.config.js` file.

If I remove that `foo/.prettierrc` file, then it works properly:

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/foo/bar/baz/node_modules/.bin/prettier --stdin --config /foo/bar/baz/prettier.config.js --config-precedence cli-override --parser typescript --use-tabs false --ignore-path /foo/bar/baz/.prettierignore --stdin-filepath /foo/bar/baz/Foo.tsx --loglevel debug --cursor-offset 272

Prettier reported the following output:

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"/foo/bar/baz/prettier.config.js","config-precedence":"cli-override","parser":"typescript","ignore-path":"/foo/bar/baz/.prettierignore","stdin-filepath":"/foo/bar/baz/Foo.tsx","loglevel":"debug","cursor-offset":272,"plugin-search-dir":[],"plugin":[],"debug-repeat":0}
[debug] load config file from '/foo/bar/baz/prettier.config.js'
[debug] loaded options `{"useTabs":false,"tabWidth":4,"endOfLine":"lf","singleQuote":true,"trailingComma":"all","proseWrap":"always"}`
[debug] applied config-precedence (cli-override): {"filepath":"/foo/bar/baz/Foo.tsx","cursorOffset":272,"endOfLine":"lf","parser":"typescript","proseWrap":"always","singleQuote":true,"tabWidth":4,"trailingComma":"all","useTabs":false}

Prettier process finished with exit code 0.
```

**Comment by jonlabelle** [comment]
Interesting. Would you mind zip compressing your project and posting here so I can take a look?

Similar to what I did [here](https://github.com/jonlabelle/SublimeJsPrettier/issues/180#issuecomment-498088849) in an un-related post.

**Comment by ryami333** [comment]
I can do one better, [a minimal reproducible case](https://github.com/ryami333/jsprettier-demo).

**Comment by jonlabelle** [comment]
Should be [fixed now](https://github.com/jonlabelle/SublimeJsPrettier/commit/42e0725436e577e12f0b66bd13e18ae4fbfcd4f1). Thanks @ryami333!!!

**Comment by ryami333** [comment]
Awesome, thanks for the fix, happy to help.
