### ISSUE TITLE
JsPrettier install fails on Mac

### ISSUE THREAD

**Issue by pvavrik** [jonlabelle/SublimeJsPrettier#185]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [ ] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [ ] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [ ] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

Issue started quite recently.
When installing from Sublime Text 3 Package Control I get:

```
reloading plugin JsPrettier.JsPrettier
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/superuser/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 60, in <module>
    from .jsprettier.const import IS_ST3
ImportError: cannot import name IS_ST3
```
Installing by git clone result in the same thing.
As a result context's menu _JsPrettier Format Code_ is disabled and no formatting of code on save.

## Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.17.1

## JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.27.10",
    ...

## Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3.2.1
    - Sublime Text Build: 3207
    - Sublime Text Architecture: <SUBLIME_TEXT_ARCHITECTURE>
    - Operating System Name: macOS
    - Operating System Version: 10.14.5
    - Operating System Architecture: <OS_ARCHITECTURE>

## Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

**Example**

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------

    /usr/local/bin/prettier                 \
        --stdin                             \
        --no-config                         \
        --print-width 80                    \
        --tab-width 4                       \
        --single-quote false                \
        --trailing-comma none               \
        --bracket-spacing true              \
        --jsx-bracket-same-line false       \
        --parser babel                      \
        --semi true                         \
        --require-pragma false              \
        --prose-wrap preserve               \
        --arrow-parens avoid                \
        --html-whitespace-sensitivity css   \
        --quote-props as-needed             \
        --use-tabs false                    \
        --stdin-filepath messy.js           \
        --loglevel debug

    Prettier reported the following output:

    [debug] normalized argv: {"_":[],"bracket-spacing":true,"color":true",...}
    [debug] '--no-config' option found, skip loading config file.
    [debug] applied config-precedence (cli-override): {"filepath":"messy.js",...}

> **NOTE:** The back-slashes (`\`) in the example above will not be printed to the Console... and only provided here for legibility purposes. The full prettier command will be output to the Console with no line-breaks.

## Is the same behavior observed when run against Prettier directly?
no

## The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

**Example JsPrettier.sublime-settings**

    {
        "debug": false,
        "prettier_cli_path": "",
        "node_path": "",
        "auto_format_on_save": false,
        "auto_format_on_save_excludes": [],
        "auto_format_on_save_requires_prettier_config": false,
        "allow_inline_formatting": false,
        "custom_file_extensions": [],
        "max_file_size_limit": -1,
        "disable_tab_width_auto_detection": false,
        "disable_prettier_cursor_offset": false,
        "additional_cli_args": {},
        "prettier_options": {
            "printWidth": 80,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "none",
            "bracketSpacing": true,
            "jsxBracketSameLine": false,
            "parser": "babel",
            "semi": true,
            "requirePragma": false,
            "proseWrap": "preserve",
            "arrowParens": "avoid",
            "htmlWhitespaceSensitivity": "css",
            "quoteProps": "as-needed"
        }
    }

## The contents of your `<project_name>.sublime-project` file (if applicable)

The entire contents of your ***User*** overridden JsPretter Project-level Settings, excluding the comments.

**Example**

    {
        "folders": [
            {
                "path": "."
            }
        ],
        "settings": {
            "js_prettier": {
                "debug": false,
                "prettier_cli_path": "",
                "node_path": "",
                "auto_format_on_save": false,
                "auto_format_on_save_excludes": [],
                "auto_format_on_save_requires_prettier_config": false,
                "allow_inline_formatting": false,
                "custom_file_extensions": [],
                "max_file_size_limit": -1,
                "disable_tab_width_auto_detection": false,
                "disable_prettier_cursor_offset": false,
                "additional_cli_args": {},
                "prettier_options": {
                    "printWidth": 80,
                    "tabWidth": 2,
                    "singleQuote": false,
                    "trailingComma": "none",
                    "bracketSpacing": true,
                    "jsxBracketSameLine": false,
                    "parser": "babel",
                    "semi": true,
                    "requirePragma": false,
                    "proseWrap": "preserve",
                    "arrowParens": "avoid",
                    "htmlWhitespaceSensitivity": "css",
                    "quoteProps": "as-needed"
                }
            }
        }
    }

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. This is the first step
    2. This is the second step
    3. Further steps, etc.

    Any other information you want to share that is relevant to the issue being
    reported. This might include the lines of code that you have identified as
    causing the bug, and potential solutions (and your opinions on their
    merits).

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
Have you tried restarting Sublime Text after installing the plug-in? It's a common problem seen in ST, modules not loading/reloading completely after installation/upgrade... w/out restarting the program.
