### ISSUE TITLE
Caret not going to where the error is.

### ISSUE THREAD

**Issue by ArthurPBressan** [jonlabelle/SublimeJsPrettier#186]
## Explain the Issue and Expected Behavior

I'm using Sublime Prettier for a few months, but recently I noticed that Sublime is not pointing out where the errors are anymore for a little while now.

I'm sure that the `disable_prettier_cursor_offset` setting is set to false, but it is still not working.

I suppose it might be related to #147 and #168.

## Prettier version

    $ prettier --version
    1.17.1

## JsPrettier Plug-in Version

    ...
    "name": "sublime-js-prettier",
    "version": "1.27.10",
    ...

## Platform Details

Provide your Sublime Text version and Platform details.

    - Sublime Text Version: 3.2.1
    - Sublime Text Build: 3207
    - Sublime Text Architecture: 64bit
    - Operating System Name: macOS High Sierra
    - Operating System Version: 10.13.6
    - Operating System Architecture: 64bit

## Generated Prettier command line arguments

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command 
    -----------------------------------------

    /usr/local/bin/prettier --stdin --config <path_to_>.prettierrc --config-precedence cli-override --parser babel --use-tabs false --stdin-filepath <path_to_file>.js --loglevel debug --cursor-offset 58

    ------------------
     JsPrettier ERROR 
    ------------------

    Prettier reported the following output:

    [debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"<path_to_>.prettierrc","config-precedence":"cli-override","parser":"babel","stdin-filepath":"<path_to_file>.js","loglevel":"debug","cursor-offset":58,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0}
    [debug] load config file from '<>.prettierrc'
    [debug] loaded options `{"trailingComma":"es5","tabWidth":2,"singleQuote":true,"useTabs":false,"eslintIntegration":true,"bracketSpacing":true,"printWidth":80,"semi":true,"arrowParens":"avoid","jsxBracketSameLine":false}`
    [warn] Ignored unknown option { eslintIntegration: true }.
    [debug] applied config-precedence (cli-override): {"filepath":"<>","arrowParens":"avoid","bracketSpacing":true,"cursorOffset":58,"jsxBracketSameLine":false,"parser":"babel","printWidth":80,"semi":true,"singleQuote":true,"tabWidth":2,"trailingComma":"es5","useTabs":false}
    [error] <file>.js: SyntaxError: Unexpected token (1:13)
    [error] > 1 | export cons fnName = arg => {};
    [error]     |             ^
    [error]   2 | 

## Is the same behavior observed when run against Prettier directly?

N/A

## The contents of your `User/JsPrettier.sublime-settings` file

    {
        "debug": true,
        "disable_prettier_cursor_offset": false,
        "auto_format_on_save": true,
        "prettier_cli_path": "/usr/local/bin/prettier",
        "auto_format_on_save_excludes": ["*/_reset.scss"]
    }

## The contents of your `<project_name>.sublime-project` file (if applicable)

N/A

## Steps to reproduce the behavior

Try to format the folling file:

    export cons fnName = arg => {};

Caret should be placed just before `fnName` but isn't.

For the record, the issue shows up in files that *are not* included in the `auto_format_on_save_excludes` array.

**Comment by jonlabelle** [comment]
Should be [fixed now](https://github.com/jonlabelle/SublimeJsPrettier/commit/5939950a8f9a5a87e4cf466ff074c834cda98c46) @ArthurPBressan.
