### ISSUE TITLE
Unable to format code

### ISSUE THREAD

**Issue by nvrdawn** [jonlabelle/SublimeJsPrettier#187]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [ ] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

Provide a story of the issue with as much detail as possible, including the expected behavior.

## Prettier version

    $ prettier --version
    1.18.2

## JsPrettier Plug-in Version

    ...
    "name": "sublime-js-prettier",
    "version": "1.27.11",
    ...

## Platform Details

    - Sublime Text Version: Dev Channel
    - Sublime Text Build: 3208
    - Operating System Name: macOS
    - Operating System Version: 10.14.5 (18F132)

## Generated Prettier command line arguments

    Prettier reported the following output:

    [JsPrettier WARN]: <sublime.View object at 0x1082901d0>

## Is the same behavior observed when run against Prettier directly?

    No

## The contents of your `User/JsPrettier.sublime-settings` file

    {
        "debug": false,
        "prettier_cli_path": "",
        "node_path": "",
        "auto_format_on_save": false,
        "auto_format_on_save_excludes": [],
        "auto_format_on_save_requires_prettier_config": false,
        "allow_inline_formatting": false,
        "custom_file_extensions": [],
        "max_file_size_limit": -1,
        "disable_tab_width_auto_detection": false,
        "disable_prettier_cursor_offset": false,
        "additional_cli_args": {},
        "prettier_options": {
            "printWidth": 80,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "none",
            "bracketSpacing": true,
            "jsxBracketSameLine": false,
            "parser": "babel",
            "semi": true,
            "requirePragma": false,
            "proseWrap": "preserve",
            "arrowParens": "avoid",
            "htmlWhitespaceSensitivity": "css",
            "quoteProps": "as-needed"
        }
    }

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. format jsx code

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
Hi @nvrdawn. Sounds like something might not have installed correctly. Can you try re-installing the plugin?

**Comment by nvrdawn** [comment]
![image](https://user-images.githubusercontent.com/14183804/60417166-4c012a80-9c12-11e9-8a84-e77b82fbaa27.png)
I never changed my prettier path. And have restarted the sublime and reinstalled for several times already. Once I call the prettier formatter, error info occur in the sublime terminal.

**Comment by nvrdawn** [comment]
![image](https://user-images.githubusercontent.com/14183804/60417481-232d6500-9c13-11e9-81e7-0c816bd7218b.png)
Just now this warning comes up. What should I do? Reinstall once more?

**Comment by nvrdawn** [comment]
![image](https://user-images.githubusercontent.com/14183804/60417896-1f4e1280-9c14-11e9-8e1a-6fd6651aa67f.png)

**Comment by jonlabelle** [comment]
Do you possibly have an old symlink, direct download, or git install version of JsPrettier in your Sublime Packages path, possibly trying to load with a Package Control install of JsPrettier?

The only thing I could dig up was [this](ignore_vcs_packages); you might the `ignore_vcs_packagess` setting.
