### ISSUE TITLE
Multi-line import

### ISSUE THREAD

**Issue by ThomasRalee** [jonlabelle/SublimeJsPrettier#190]
**Is your feature request related to a problem? Please describe.**
I am using airbnb-eslint, the imports are required to be spread on different lines

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
To use JSprettier on files with imports, I have to:
- save the imports on my clipboard 
- run JsPrettier
- override the imports with my clipbaord

**Describe the solution you'd like**
- have an option to format imports into multiline, that would make life truly amazing

**Additional context**
- [airbnb-eslint docs](https://github.com/airbnb/javascript#modules--multiline-imports-over-newlines)
- Multiline imports should be indented just like multiline array and object literals.

- Why? The curly braces follow the same indentation rules as every other curly brace block in the style guide, as do the trailing commas.
```
// bad
import {longNameA, longNameB, longNameC, longNameD, longNameE} from 'path';

// good
import {
  longNameA,
  longNameB,
  longNameC,
  longNameD,
  longNameE,
} from 'path';
```

**Comment by jonlabelle** [comment]
Hi @ThomasRalee. Formatting enhancements/changes/suggestions should be made through  [Prettier's issue board](https://github.com/prettier/prettier/issues).
