### ISSUE TITLE
.prettierrc in project is not detected

### ISSUE THREAD

**Issue by ciaoben** [jonlabelle/SublimeJsPrettier#191]
I am on prettier 1.18.2,  and plugin `1.27.14` on mac os.
I have a simple vue repo:
```
» ll -lah
total 896
drwxr-xr-x   13 ben  staff   416B Oct 14 18:31 .
drwxr-xr-x   32 ben  staff   1.0K Oct 14 17:52 ..
drwxr-xr-x   13 ben  staff   416B Oct 14 18:42 .git
-rw-r--r--    1 ben  staff   214B Oct 14 17:52 .gitignore
-rw-r--r--    1 ben  staff    30B Oct 14 18:02 .prettierignore
-rw-r--r--@   1 ben  staff    48B Oct 14 18:42 .prettierrc
-rw-r--r--    1 ben  staff   322B Oct 14 18:20 README.md
-rw-r--r--    1 ben  staff    53B Oct 14 17:52 babel.config.js
drwxr-xr-x  821 ben  staff    26K Oct 14 17:55 node_modules
-rw-r--r--    1 ben  staff   424K Oct 14 17:52 package-lock.json
-rw-r--r--    1 ben  staff   906B Oct 14 17:52 package.json
drwxr-xr-x    4 ben  staff   128B Oct 14 17:52 public
drwxr-xr-x    6 ben  staff   192B Oct 14 17:52 src
```

Here my plugin config:

```
{
	"auto_format_on_save": true,
	// "prettier_cli_path": "/usr/local/Cellar/node/10.4.1/bin/prettier",
  "allow_inline_formatting": true,
  "debug": true,
  "auto_format_on_save_requires_prettier_config": true
}
```

I am expecting that on save the plugin use the `.prettierrc` file in my home, that has this content:
```
{
  "printWidth": 2000,
  "singleQuote": false
}
```

but instead I get this command:

```
/usr/local/Cellar/node/10.4.1/bin/prettier --stdin --no-config --print-width 80 --tab-width 2 --single-quote false --trailing-comma none --bracket-spacing true --jsx-bracket-same-line false --parser vue --semi true --require-pragma false --prose-wrap preserve --arrow-parens avoid --html-whitespace-sensitivity css --quote-props as-needed --use-tabs false --stdin-filepath /Users/ben/pro/i4mui/src/components/HelloWorld.vue --loglevel debug --cursor-offset 1733
```

Why it is not detecting my `.prettierrc` file?

If l manually run this:
```
» /usr/local/Cellar/node/10.4.1/bin/prettier --find-config-path src/components/HelloWorld.vue
.prettierrc
```
it works correctly.

**Comment by jonlabelle** [comment]
I can't seem to reproduce the problem you're experiencing.

Here's the quick example project I used: [jsprettier-issue-191-prettierrc-not-detected.zip](https://github.com/jonlabelle/SublimeJsPrettier/files/3747779/jsprettier-issue-191-prettierrc-not-detected.zip)

**Comment by bijection** [comment]
I'm also experiencing this bug, although when I download https://github.com/jonlabelle/SublimeJsPrettier/issues/191#issuecomment-544243136 and run it it works fine.

**Comment by jonlabelle** [comment]
@ciaoben, @bijection: If possible, can you zip up and attach the project so I can run on my end?

Just be sure to **exclude any private/sensitive resources** (passwords, keys, etc.) from the archive; anything you wouldn't want publicly exposed.

**Comment by indigane** [comment]
I'm having the same issue. In my case it seems to have been caused by the config file resolver cache, which won't look for the config file again, if it wasn't found at the first format.

So if you added the config file during development, it won't be detected.
