### ISSUE TITLE
Prettier overrides option is ignored

### ISSUE THREAD

**Issue by adamgruber** [jonlabelle/SublimeJsPrettier#192]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

Overrides set using the `prettier_options.overrides` option inside the `JsPrettier.sublime-settings` file do not get applied.

## Prettier version
1.18.2

## JsPrettier Plug-in Version
1.27.14

## Platform Details
    - Sublime Text Version: 3.2.2
    - Sublime Text Build: 3211
    - Operating System Name: macOS High Sierra
    - Operating System Version: 10.13.6

## Generated Prettier command line arguments
```
[JsPrettier DEBUG]: Could not resolve Prettier config file, will use options defined in Sublime Text.

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier
  --stdin                           \
  --no-config                       \
  --print-width 80                  \
  --tab-width 4                     \
  --single-quote true               \
  --trailing-comma es5              \
  --bracket-spacing true            \
  --jsx-bracket-same-line false     \
  --parser css                      \
  --semi true                       \
  --require-pragma false            \
  --prose-wrap preserve             \
  --arrow-parens avoid              \
  --html-whitespace-sensitivity css \
  --quote-props as-needed           \
  --use-tabs false                  \
  --stdin-filepath /test.scss       \
  --loglevel debug                  \
  --config-precedence prefer-file   \
  --cursor-offset 0                 \

Prettier reported the following output:

[debug] normalized argv: {"_":[],"bracket-spacing":true,"color":true,"editorconfig":true,"jsx-bracket-same-line":false,"require-pragma":false,"semi":true,"single-quote":true,"stdin":true,"use-tabs":false,"config":false,"print-width":80,"tab-width":4,"trailing-comma":"es5","parser":"css","prose-wrap":"preserve","arrow-parens":"avoid","html-whitespace-sensitivity":"css","quote-props":"as-needed","stdin-filepath":"/Users/adamg/Desktop/prettier-test/test.scss","loglevel":"debug","config-precedence":"prefer-file","cursor-offset":0,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0}
[debug] '--no-config' option found, skip loading config file.
[debug] applied config-precedence (prefer-file): {"filepath":"/test.scss","arrowParens":"avoid","bracketSpacing":true,"cursorOffset":29,"htmlWhitespaceSensitivity":"css","jsxBracketSameLine":false,"parser":"css","printWidth":80,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":true,"singleQuote":true,"tabWidth":4,"trailingComma":"es5","useTabs":false}

Prettier process finished with exit code 0.
```

## Is the same behavior observed when run against Prettier directly?

No, when run with prettier CLI, directly pointing to a config file with same options, the overrides are respected.

## The contents of your `JsPrettier.sublime-settings` file

```
{
  "debug": true,
  "disable_tab_width_auto_detection": true,
  "additional_cli_args": {
    "--config-precedence": "prefer-file",
  },
  "auto_format_on_save": true,
  "auto_format_on_save_requires_prettier_config": false,
  "prettier_cli_path": "/usr/local/bin/prettier",
  "prettier_options": {
    "tabWidth": 4,
    "trailingComma": "es5",
    "singleQuote": true,
    "overrides": [
        {
            "files": "*.scss",
            "options": {
                "tabWidth": 2,
            },
        },
    ],
  }
}
```

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Set up JsPrettier sublime plugin with above settings
    2. Create a test SASS file (`test.scss`)
    3. Save file and observe formatting

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
You'll need to use [Prettier configuration files](https://prettier.io/docs/en/configuration.html) instead of `prettier_options` defined in your [JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L279) file if you want to use [configuration overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides).

The `overrides` section is not currently processed by the plugin and passed along as CLI args to Prettier.

You'll also want to add/set [`--config-precedence`](https://prettier.io/docs/en/cli.html#config-precedence) to your JsPrettier settings under [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L267), to ensure file configuration options override the CLI...

```json
{
  "additional_cli_args": {
    "--config-precedence": "file-override"
  }
}
```

**Comment by adamgruber** [comment]
I could have sworn this used to work and just recently it stopped. Is it something that could be made to work? One of the nice things about this plugin is that I don't have to have separate prettier config files for each project, I can just have them in one place defined in the `JsPrettier.sublime-settings` file.
