### ISSUE TITLE
Allow prettying unsaved files

### ISSUE THREAD

**Issue by KaKi87** [jonlabelle/SublimeJsPrettier#195]
Hello,

**Is your feature request related to a problem? Please describe.**

One of Sublime Text's most practical features is to edit files without requiring the user to save these into the filesystem by himself.

**Describe the solution you'd like**

The purpose of adding plugins to a software is to extend its capabilities, not limit them.

Therefore, JsPrettier should work properly with unsaved files.

**Describe alternatives you've considered**

If, for some reason, you don't want to make direct support for unsaved files, the plugin could firstly save the file by itself before prettying it, then return the result, and finally delete the file.

**Additional context**

![Popup screenshot](https://user-images.githubusercontent.com/21284089/70851553-edb1c680-1e96-11ea-8a7b-b2ae99458387.png)

Note : this is a duplicate of #177 but I had no choice since this one is locked and definitely not resolved, so this is my only way to make my point.

Thanks

**Comment by jonlabelle** [comment]
Hi @KaKi87. Thanks for the feedback... however, unless a PR request comes along, I really don't have any interest in re-working the plug-in to support buffered-only content.

**Comment by KaKi87** [comment]
Is there actually anything you have interest in about the plugin ?

**Comment by jonlabelle** [comment]
Yes.
