### ISSUE TITLE
Trailing Comma `None` Setting Not Applied

### ISSUE THREAD

**Issue by loganknecht** [jonlabelle/SublimeJsPrettier#198]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [ ] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

I am making an AWS Cloud Formation Script that is in the JSON syntax. JSPrettier is causing it to fail because it keeps appending a trailing comma despite having set it to `none`.

## Prettier version

```bash
╭─lknecht@愛と支えボックス ~/Repositories/Nextflow ‹debug/scaling-dev*›
╰─$ prettier --version
1.19.1
```
## JsPrettier Plug-in Version

```json
{
  "name": "sublime-js-prettier",
  "version": "1.28.5",
  "description": "JsPrettier is a Sublime Text Plug-in for Prettier, the opinionated code formatter.",
  "author": "Jon LaBelle",
  "license": "MIT",
  "dependencies": {
    "prettier": "latest"
  },
  "repository": "jonlabelle/SublimeJsPrettier",
  "keywords": [
    "sublime",
    "sublimetext",
    "plugin",
    "prettier",
    "jsprettier",
    "formatter",
    "javascript",
    "css"
  ],
  "files": [
    "*.md",
    ".no-sublime-package",
    "Context.sublime-menu",
    "JsPrettier.py",
    "JsPrettier.sublime-commands",
    "jsprettier/**",
    "Main.sublime-menu",
    "messages.json",
    "messages/*.txt"
  ],
  "bugs": {
    "url": "https://github.com/jonlabelle/SublimeJsPrettier/issues"
  },
  "homepage": "https://github.com/jonlabelle/SublimeJsPrettier"
}
```

## Platform Details

![image](https://user-images.githubusercontent.com/1308524/72845541-ab2c9800-3c53-11ea-8341-260b289e507e.png)

- Operating System Name: OSX Mojave
- Operating System Version: 10.14.6

## Generated Prettier command line arguments

```
Prettier reported the following output:
[debug] normalized argv: {"_":[],"bracket-spacing":true,"color":true,"editorconfig":true,"jsx-bracket-same-line":false,"require-pragma":false,"semi":true,"single-quote":false,"stdin":true,"use-tabs":false,"vue-indent-script-and-style":false,"config":false,"print-width":120,"tab-width":4,"trailing-comma":"none","parser":"yaml","prose-wrap":"preserve","arrow-parens":"avoid","html-whitespace-sensitivity":"css","quote-props":"as-needed","stdin-filepath":"/Users/lknecht/Desktop/FAUST/performance_tests/cloud_formation/rglab_cloud_formation_template.yaml","loglevel":"debug","cursor-offset":647,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] '--no-config' option found, skip loading config file.
[debug] applied config-precedence (cli-override): {"filepath":"/Users/lknecht/Desktop/FAUST/performance_tests/cloud_formation/rglab_cloud_formation_template.yaml","arrowParens":"avoid","bracketSpacing":true,"cursorOffset":647,"htmlWhitespaceSensitivity":"css","jsxBracketSameLine":false,"parser":"yaml","printWidth":120,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":true,"singleQuote":false,"tabWidth":4,"trailingComma":"none","useTabs":false,"vueIndentScriptAndStyle":false}
```

## Is the same behavior observed when run against Prettier directly?

Unknown

## The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

```
{
    
    "debug": true,
    "auto_format_on_save": true,
    "custom_file_extensions": ["sublime-settings", "yaml"],
    "prettier_options": {
        "printWidth": 120,
        "tabWidth": 4,
        "trailingComma": "none"
    }
}
```

## Steps to reproduce the behavior
    1. Install Prettier
    2. Install SublimeJSPrettier
    3. Save JSON file

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by loganknecht** [comment]
Disregard. I am a dingus and had a `.yml` file instead of a `.json` file. It appears to be working correctly now!

**Comment by jonlabelle** [comment]
Hi @loganknecht. Can you please post the content your trying to format?

**Comment by loganknecht** [comment]
@jonlabelle 

It was this
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Parameters":
        {
            "S3NextflowBucketName":
                {
                    "Type": "String",
                    "Description": "S3 Bucket used to store Nextflow metadata (session cache, logs, and intermediate results)",
                },
        },
    "Resources":
        {
            "VPC":
                {
                    "Type": "AWS::EC2::VPC",
                    "Properties": { "CidrBlock": "10.0.0.0/16" },
                    "Metadata": { "AWS::CloudFormation::Designer": { "id": "6f3337fe-97f7-4123-ba22-4acd5a15734e" } },
                },
        },
}
```

But per my previous comment this was an error on my part. I was saving `json` contents in a file that ended with the `.yml` extension. The fix was changing it to the correct extension `.json`

Sorry for the noise!
