### ISSUE TITLE
JsPrettier does not properly configure parser for Less files

### ISSUE THREAD

**Issue by percyhanna** [jonlabelle/SublimeJsPrettier#199]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

When prettying a Less file, it forces the parser to use CSS, which prevents Prettier from parsing and prettying the content properly. It should use SCSS instead.

## Prettier version

`1.19.1`

## JsPrettier Plug-in Version

`1.28.5`

## Platform Details

    - Sublime Text Version: 3.2.2
    - Sublime Text Build: 3211
    - Operating System Name: macOS
    - Operating System Version: 10.15

## Generated Prettier command line arguments

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------

```sh
/Users/percyhanna/.config/yarn/global/node_modules/.bin/prettier \
  --stdin \
  --config /path/to/.prettierrc \
  --config-precedence cli-override \
  --parser css \
  --use-tabs false \
  --ignore-path /path/to/.prettierignore \
  --stdin-filepath /path/to/file.less \
  --loglevel debug \
  --cursor-offset 6930
```

    Prettier reported the following output:

    [debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"/path/to/.prettierrc","config-precedence":"cli-override","parser":"css","ignore-path":"/path/to/.prettierignore","stdin-filepath":"/path/to/app/assets/stylesheets/landing_pages.less","loglevel":"debug","cursor-offset":6217,"plugin-search-dir":[],"plugin":[],"debug-repeat":0}
    [debug] load config file from '/path/to/.prettierrc'
    [debug] loaded options `{"jsxSingleQuote":true,"singleQuote":true,"trailingComma":"es5"}`
    [debug] applied config-precedence (cli-override): {"filepath":"/path/to/app/assets/stylesheets/landing_pages.less","cursorOffset":6217,"jsxSingleQuote":true,"parser":"css","singleQuote":true,"trailingComma":"es5","useTabs":false}

## Is the same behavior observed when run against Prettier directly?

If I remove `--parser css` then it works as expected. Or, if I use `--parser scss`.

## The contents of your `User/JsPrettier.sublime-settings` file

```json
{
  "debug": true,
  "auto_format_on_save": true,
  "prettier_cli_path": "/Users/percyhanna/.config/yarn/global/node_modules/.bin/prettier"
}
```

## The contents of your `<project_name>.sublime-project` file (if applicable)

n/a

## Steps to reproduce the behavior

This issue is specifically related to this bug that has been fixed in prettier: https://github.com/prettier/prettier/pull/2034

If I save a `.less` file with the `&:extend` content, then it adds the space, thus breaking the syntax in less.

```css
div {
  &:extend(.something);
}
```

**Comment by percyhanna** [comment]
Upon further investigation, `--parser scss` does not work, but removing the `--parser` option works, and using `--parser less` also works.

**Comment by jonlabelle** [comment]
According to [Prettier's documentation](https://prettier.io/docs/en/options.html#parser), they are the same (... *"scss" same parsers as "css"*), therefore, you'll need to bring the problem up on the [Prettier boards](https://github.com/prettier/prettier/issues).

A work-around in the meantime would be to setup a [configuration override](https://prettier.io/docs/en/configuration.html#configuration-overrides), then add an [additional CLI argument](https://github.com/jonlabelle/SublimeJsPrettier/blob/9e9a6efaa0988833c9836d67ce6dbb142f74e062/JsPrettier.sublime-settings#L267) for [config precedence](https://prettier.io/docs/en/cli.html#--config-precedence) as follows:

```json
"additional_cli_args": {
  "--config-precedence": "file-override"
}
```
