### ISSUE TITLE
Error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by mdchristians** [jonlabelle/SublimeJsPrettier#2]
I haven't gotten a chance to really dive into debugging this yet, but simply running through the install instructions is giving me an error when I try and run the command for the first time.

I verified Prettier was installed and restarted sublime with the same issue.

Also, upon opening the package settings for the first time both the default and user files are empty.

<img width="485" alt="screen shot 2017-01-18 at 7 47 11 pm" src="https://cloud.githubusercontent.com/assets/4482233/22090554/0d90b678-ddb8-11e6-937a-8bb6f60918f2.png">

EDIT: I forgot to mention that prettier is working via the CLI if that helps.

**Comment by jonlabelle** [comment]
This should be corrected since [1.0.1](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.0.1). And noted in the [Changelog](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/messages/1.0.1.txt).

Let me know.
