### ISSUE TITLE
trailing Comma option

### ISSUE THREAD

**Issue by Rayraegah** [jonlabelle/SublimeJsPrettier#20]
Setting trailing comma to **none** does not turn off trailing commas. The off command is a boolean value. Seems to be an issue in prettier itself.

CLI args: 
`['--print-width', '80', '--single-quote=true', '--trailing-comma', 'none', '--bracket-spacing=true', '--jsx-bracket-same-line=false', '--parser', 'babylon', '--tab-width', '4']`

FIX args:
`['--print-width', '80', '--single-quote=true', '--trailing-comma=false', '--bracket-spacing=true', '--jsx-bracket-same-line=false', '--parser', 'babylon', '--tab-width', '4']`

FYI only.

**Comment by jonlabelle** [comment]
Have you updated your prettier install (`npm install -g prettier`) so it adheres to the change?

**Comment by jonlabelle** [comment]
@Rayraegah: You are correct. I was able to reproduce the issue in v0.18.0.

**Comment by jonlabelle** [comment]
I opened the [issue](https://github.com/jlongster/prettier/issues/747) on the Prettier board.
