### ISSUE TITLE
singleQuote not respected by JsPrettier

### ISSUE THREAD

**Issue by altinselimi** [jonlabelle/SublimeJsPrettier#201]
Hi there,

- [x] **Explain the Issue and Expected Behavior**
I work in different projects which follow different conventions. I have come to notice that JsPrettier does is not really using the options I am providing it with in package.json or .prettierrc file. More specifically the singleQuote flag. The expected behavior is it should respect the flags provided there.

- [x] **Prettier version**
1.19.1
- [x] **JsPrettier Plug-in Version**
1.28.6
- [x] **Platform Details**
MacOS Catalina
- [x] **Generated Prettier command line arguments**
--single-quote --write
- [x] **Is the same behavior observed when run against Prettier directly?**
No, running the same file using prettier directly outputs the single quotes as it should
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
```
{
	"custom_file_extensions": ["jade"],
	"auto_format_on_save": true,
}
```
- [x] **Steps to reproduce the behavior**
Save file, or run JsPrettify and you will see all the quotes are doubles.

**Comment by jonlabelle** [comment]
Add this to your [JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L267):

```json
"additional_cli_args": { "--config-precedence": "file-override" }
```
