### ISSUE TITLE
event listener @event in vuejs get multiline format

### ISSUE THREAD

**Issue by jd-0001** [jonlabelle/SublimeJsPrettier#202]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [ ] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior
We have code like below:
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="err => { form_errors = err }"
/>
```

After we run formatter we get even in multi-line like below:
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="
    err => {
      form_errors = err
    }
  "
/>
```

## Prettier version
node_modules/.bin/prettier --version
1.19.1

## JsPrettier Plug-in Version
1.28.0
(I got it from changeLog)

## Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3.2.2
    - Sublime Text Build: 3211
    - Sublime Text Architecture: How?
    - Operating System Name: Linux Mint
    - Operating System Version: 19.3
    - Operating System Architecture: 

## Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.
```shell
Prettier reported the following output:

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"parser":"vue","stdin-filepath":"/home/bapu/Projects/portal-name/src/frontend/src/pages/edit/Edit.vue","loglevel":"debug","config":"src/frontend/prettierrc.json","cursor-offset":710,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] load config file from 'src/frontend/prettierrc.json'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"endOfLine":"lf","arrowParens":"avoid","bracketSpacing":true,"htmlWhitespaceSensitivity":"css","insertPragma":false,"jsxBracketSameLine":false,"jsxSingleQuote":true,"printWidth":120,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":false,"singleQuote":true,"trailingComma":"none","vueIndentScriptAndStyle":false}`
[debug] applied config-precedence (cli-override): {"filepath":"/home/bapu/Projects/portal-name/src/frontend/src/pages/edit/Edit.vue","arrowParens":"avoid","bracketSpacing":true,"cursorOffset":710,"endOfLine":"lf","htmlWhitespaceSensitivity":"css","insertPragma":false,"jsxBracketSameLine":false,"jsxSingleQuote":true,"parser":"vue","printWidth":120,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":false,"singleQuote":true,"tabWidth":2,"trailingComma":"none","useTabs":false,"vueIndentScriptAndStyle":false}

Prettier process finished with exit code 0.
```

> **NOTE:** The back-slashes (`\`) in the example above will not be printed to the Console... and only provided here for legibility purposes. The full prettier command will be output to the Console with no line-breaks.

## The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.
**I have project level settings**
```
"js_prettier":
		{
			"debug": true,
			"prettier_cli_path": "/home/bapu/Projects/portal-name/src/frontend/node_modules/prettier/bin-prettier.js",
			"additional_cli_args":
			{
				"--config": "src/frontend/prettierrc.json"
			},
			"auto_format_on_save": true
		}
```

## The contents of your `<project_name>.sublime-project` file (if applicable)
```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"python\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"path": "/home/bapu/Projects/portal-name"
		}
	],
	"settings":
	{
		"ESLint-Formatter":
		{
			"format_on_save": false,
			"format_on_save_extensions":
			[
				"js",
				"jsx",
				"es",
				"es6",
				"babel",
				"vue"
			]
		},
		"js_prettier":
		{
			"debug": true,
			"prettier_cli_path": "/home/bapu/Projects/portal-name/src/frontend/node_modules/prettier/bin-prettier.js",
			"additional_cli_args":
			{
				"--config": "src/frontend/prettierrc.json"
			},
			"auto_format_on_save": true
		}
	}
}
```

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.
Jus t use above code and format

    Any other information you want to share that is relevant to the issue being
    reported. This might include the lines of code that you have identified as
    causing the bug, and potential solutions (and your opinions on their
    merits).

This isn't happening in vs-code. vs-code properly formats above code.

**Comment by jonlabelle** [comment]
When I copy/paste your code into prettier playground, the [same result](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeSBbADtBMA6UABEUgJYDOAvPiAOZwwD6mOUeAFAOQCuWANhACGAEwC0AMwgAnDFwCUtQiSRTZTEUJhCaINRg1ahS4qX1M406TOq1zl69IomV5iFhhlotvTIPvPbxciAAE+TXgLKxtdByIqAD4iYCJ7aKd4ojiAXxMAegSQABoQAK8oCmRQIWiAdwAFGoRKlCEANwgyEWKQACNpITAAa0YAZSxBsig6ZBhpHjgSgAsYDH4AdSWyeAoJsDhR5u2yNu2AT2RwCkqSqYpLGHqBugwhZAkhfnuSgCsKAA8AEIDYZjIQYOAAGSmcHen2+ID+-1GUzo-DgAEUeBB4HCvosQBMnJZLm0Fj0sNIpjB1l0YEtkAAOAAMJUpEHu6wGWEulLg92kbVhJQAjtj4E93C0QEIKGJ2HARIqetI4GKyKqnkIXm9VPCCfcMGRZvMDaj0VicbC9fiStperSRPTkAAmO0DMj8VEAYQgGFelyguB6PHuABUhL0Wh9bSAyXAAJJQJWwUZgKkeACCydGMDO6Lx92y2SAA) is produced.
