### ISSUE TITLE
JsPrettier does not properly configure parser for Less files

### ISSUE THREAD

**Issue by percyhanna** [jonlabelle/SublimeJsPrettier#205]
Reopening #199.

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

When prettying a Less file, it forces the parser to use CSS, which prevents Prettier from parsing and prettying the content properly. It should use SCSS instead.

## Prettier version

`1.19.1`

## JsPrettier Plug-in Version

`1.28.5`

## Platform Details

    - Sublime Text Version: 3.2.2
    - Sublime Text Build: 3211
    - Operating System Name: macOS
    - Operating System Version: 10.15

## Generated Prettier command line arguments

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------

```sh
/Users/percyhanna/.config/yarn/global/node_modules/.bin/prettier \
  --stdin \
  --config /path/to/.prettierrc \
  --config-precedence cli-override \
  --parser css \
  --use-tabs false \
  --ignore-path /path/to/.prettierignore \
  --stdin-filepath /path/to/file.less \
  --loglevel debug \
  --cursor-offset 6930
```

    Prettier reported the following output:

    [debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"stdin":true,"use-tabs":false,"config":"/path/to/.prettierrc","config-precedence":"cli-override","parser":"css","ignore-path":"/path/to/.prettierignore","stdin-filepath":"/path/to/app/assets/stylesheets/landing_pages.less","loglevel":"debug","cursor-offset":6217,"plugin-search-dir":[],"plugin":[],"debug-repeat":0}
    [debug] load config file from '/path/to/.prettierrc'
    [debug] loaded options `{"jsxSingleQuote":true,"singleQuote":true,"trailingComma":"es5"}`
    [debug] applied config-precedence (cli-override): {"filepath":"/path/to/app/assets/stylesheets/landing_pages.less","cursorOffset":6217,"jsxSingleQuote":true,"parser":"css","singleQuote":true,"trailingComma":"es5","useTabs":false}

## Is the same behavior observed when run against Prettier directly?

If I remove `--parser css` then it works as expected. Or, if I use `--parser scss`.

## The contents of your `User/JsPrettier.sublime-settings` file

```json
{
  "debug": true,
  "auto_format_on_save": true,
  "prettier_cli_path": "/Users/percyhanna/.config/yarn/global/node_modules/.bin/prettier"
}
```

## The contents of your `<project_name>.sublime-project` file (if applicable)

n/a

## Steps to reproduce the behavior

This issue is specifically related to this bug that has been fixed in prettier: https://github.com/prettier/prettier/pull/2034

If I save a `.less` file with the `&:extend` content, then it adds the space, thus breaking the syntax in less.

```css
div {
  &:extend(.something);
}
```

**Comment by percyhanna** [comment]
I forgot to respond before the issue was locked.

As per [Prettier's documentation](https://prettier.io/docs/en/options.html#parser):

>* "css" (via postcss-scss and postcss-less, autodetects which to use) First available in v1.7.1
>* "scss" (same parsers as "css", prefers postcss-scss) First available in v1.7.1
>* "less" (same parsers as "css", prefers postcss-less) First available in v1.7.1

Using `--parser scss` _**prefers**_ postcss-scss, and using `--parser less` _**prefers**_ postcss-less. There is a difference — they are not the same.

**Comment by jonlabelle** [comment]
So what is your suggestion to fix/change this behavior? How is the plug-in supposed to automatically detect that you want to parse LESS files using a different (SCSS) parser?

This is exactly what the [file override](https://prettier.io/docs/en/configuration.html#configuration-overrides) option is for; and you can override the file/parser behaviors.

**Comment by percyhanna** [comment]
@jonlabelle I suppose it would be something like this: #209

**Comment by jonlabelle** [comment]
Okay thanks, I'll take a look.
