### ISSUE TITLE
useTabs in project configuration file is not working

### ISSUE THREAD

**Issue by quangbuule** [jonlabelle/SublimeJsPrettier#208]
**Reproduction steps:**
- Having a project open with `.prettierrc` containing: ```"useTabs": false```
- Open a file having these settings: 
![image](https://user-images.githubusercontent.com/5992964/78422287-f9293780-76a9-11ea-9047-29ee39e3882e.png)
- Edit and save the file with some indentation.

**Expectation:**
- The file is saved with tabs converting to spaces

**Actual:**
Tabs are not converted to spaces that is configured in the `.prettierrc`

**Discussion:**
The tabs/spaces settings on Sublime could be different with `.prettierrc` when opening a file. I am not sure how the settings are determined, but I think we should follow the project configuration.

I believe this is because we are adding `--use-tabs {view_settings.translate_tabs_to_spaces}` in the end of the command argument list.

**Comment by jonlabelle** [comment]
Add this to your [JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L267):

```json
"additional_cli_args": { "--config-precedence": "file-override" }
```
