### ISSUE TITLE
Project-level Settings based on .eslintrc

### ISSUE THREAD

**Issue by tajo** [jonlabelle/SublimeJsPrettier#21]
I know you can now use .sublime-project file but it would be nice if this plugin tried first to look it up in `.eslintrc`:

- is prettier plugin used -> format on on save
- used the rules...

**Comment by jonlabelle** [comment]
why would you want prettier/formatting settings configured in a linting file?

**Comment by Rayraegah** [comment]
You might want to see this: https://github.com/not-an-aardvark/eslint-plugin-prettier

**Comment by jonlabelle** [comment]
At this time, I'm not looking to support the various prettier mix-ins already out there. At least not until prettier itself becomes more stable.
