### ISSUE TITLE
A way to force prettier even if prettierignore existing

### ISSUE THREAD

**Issue by kud** [jonlabelle/SublimeJsPrettier#210]
**Is your feature request related to a problem? Please describe.**

I currently use `auto_format_on_save`. However, as prettier isn't so great for jinja2/nunjucks, I disabled it via .prettierignore.

However, I still want to use prettier for certain part of code via selection + right-click > jsprettier.

But as I've ignored the file, prettier does nothing on it.

**Describe the solution you'd like**

JsPrettier could ignore `.prettierignore` when it's using by selection (and keep it when whole file / on save)

**Comment by jonlabelle** [comment]
Hi @kud. Thanks for the feedback. But at this time, I'm not looking to implement this particular feature (respectfully). It just seems to edgy of a use-case, ultimately adding unnecessary complexity to the code base.
