### ISSUE TITLE
[Question] How to use mdx parser on .md files?

### ISSUE THREAD

**Issue by kud** [jonlabelle/SublimeJsPrettier#214]
Hello,

I've got a question. For some reasons (I explained here:http://diary.kud.io/en/posts/2020/05/10/how-to-edit-a-markdown-in-2020-part-1-zmv) I had to switch my mdx files from `.mdx` to `.md`.

However, when I use JsPrettier, it uses the markdown parser instead of mdx one (which is normal). Is there a way to always use mdx parser for markdown files?

Thank you.

**Comment by jonlabelle** [comment]
Hi @kud: Have you tried a [configuration override](https://prettier.io/docs/en/configuration.html#configuration-overrides)?

**Comment by kud** [comment]
Interesting option! I didn't know about that, I was searching into your options, not the one in prettier.

However, it doesn't work as you can see:

```
[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"use-tabs":false,"config":"/Users/kud/Projects/_kud/diary/.prettierrc.js","parser":"markdown","stdin-filepath":"/Users/kud/Projects/_kud/diary/src/pages/en/posts/2020/05/10/how-to-edit-a-markdown-in-2020-part-1-zmv/index.md","loglevel":"debug","cursor-offset":169,"plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] load config file from '/Users/kud/Projects/_kud/diary/.prettierrc.js'
[debug] loaded options `{"parser":"mdx"}`
[debug] applied config-precedence (cli-override): {"filepath":"/Users/kud/Projects/_kud/diary/src/pages/en/posts/2020/05/10/how-to-edit-a-markdown-in-2020-part-1-zmv/index.md","cursorOffset":169,"parser":"markdown","useTabs":false}

Prettier process finished with exit code 0.
```

```js
module.exports = {
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "parser": "mdx"
      }
    }
  ]
}
```

**Comment by jonlabelle** [comment]
Add this to your [JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L267):

```json
"additional_cli_args": { "--config-precedence": "file-override" }
```

**Comment by kud** [comment]
Perfect! it works. Thank you very much. :)
