### ISSUE TITLE
Syntax specifc printwidth

### ISSUE THREAD

**Issue by princemaple** [jonlabelle/SublimeJsPrettier#216]
**Is your feature request related to a problem? Please describe.**
I want to format HTML with 100 print width and 80 for others.

**Describe the solution you'd like**
put
```json
	"prettier_options": {
	  "printWidth": 100,
	}
```
in syntax specific settings, HTML.sublime-settings in this case and have JsPrettier pick it up automatically when on an HTML file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

If it already works, I must be doing something wrong. I tried just that and didn't work. Just trying to confirm with this issue, that if this feature exists.

**Comment by jonlabelle** [comment]
Hi @princemaple. The plug-in doesn't read `prettier_options` from Syntax Specific Settings.

You must define them in your *User* level **JsPrettier.sublime-settings** file:

![jsprettier-user-prefs-navigate-ss](https://user-images.githubusercontent.com/226837/82906834-71cea680-9f2b-11ea-9b55-923e4e1878d5.png)

**Comment by princemaple** [comment]
Can I achieve having different print width for different languages though?

**Comment by princemaple** [comment]
That's a no I guess? Since user settings apply to all syntax and cannot to customized to the language.

**Comment by jonlabelle** [comment]
Yes. The default behavior of JsPrettier is to read the the currently configured `tab_size` for the view, and set the `printWidth` Prettier option.

**Comment by princemaple** [comment]
Are we talking about the same thing? Print width is the line length, not the tab size. Sorry about chasing this further.

**Comment by jonlabelle** [comment]
Yes...

- tab_size (SublimeText)
- printWidth (Prettier)

**Comment by princemaple** [comment]
Thanks. Will you accept a PR to add reading settings from syntax specific settings so we can have different print width for different languages? (Although I'm starting to think I should stick to 80 for all languages now, lol)

**Comment by jonlabelle** [comment]
> Will you accept a PR to add reading settings from syntax specific settings so we can have different print width for different languages?

[Again](https://github.com/jonlabelle/SublimeJsPrettier/issues/216#issuecomment-634034145), if you set the *Sublime Text* [`tab_size`](https://sublime-text-unofficial-documentation.readthedocs.io/en/latest/reference/settings.html#file-settings) setting in your syntax file, JsPrettier will automatically translate option to [--tab-width](https://prettier.io/docs/en/options.html#tab-width) in Prettier.

**Comment by princemaple** [comment]
Again, it's printWidth (line length limit) I'm trying to change, not tab width. That's why I was asking if we were on the same page 😂 😂

**Comment by jonlabelle** [comment]
Doy!

**Comment by princemaple** [comment]
AHHHH finally we connect :)))) I knew something wasn't right lolll
