### ISSUE TITLE
[error] Couldn't resolve parser "babylon"

### ISSUE THREAD

**Issue by y213140** [jonlabelle/SublimeJsPrettier#219]
Prettier reported the following error(s):

[warn] Ignored unknown option --stdin.
[error] Couldn't resolve parser "babylon"

Process finished with exit code 1

version 2.0.5

**Comment by jonlabelle** [comment]
The `--stdin` option has been deprecated. You probably just need to update the plugin ([JsPrettier](https://github.com/jonlabelle/SublimeJsPrettier#install-jsprettier-via-package-control)).
