### ISSUE TITLE
Ignored unknown option: --jsx-bracket-same-line=false

### ISSUE THREAD

**Issue by manatarms** [jonlabelle/SublimeJsPrettier#22]
Seems like an issue with the update of the Prettier CLI, but it affects this plugin.
The sublime console is returning this error
```
## Prettier CLI Error Output:
Ignored unknown option: --jsx-bracket-same-line=false
## Prettier CLI Return Code:
    0
```

**Comment by jonlabelle** [comment]
Make sure you're on the lateset prettier release (npm install -g prettier).
