### ISSUE TITLE
UnicodeDecodeError when decoding cp949 stderror with utf-8

### ISSUE THREAD

**Issue by peppy0510** [jonlabelle/SublimeJsPrettier#220]
Same issue with [Issue #196](https://github.com/jonlabelle/SublimeJsPrettier/issues/196)
In my case, occurs when Popen's stderror has cp949 charset while running East Asian version of Windows OS which does not use utf-8 charset for stderror.

It should be changed something like below, works fine with my system.

`JsPrettier.py line 412`

> ```python
> try:
>     error_output = stderr.decode('utf-8')
> except UnicodeDecodeError:
>     error_output = stderr.decode('cp949')
> ```

`JsPrettier.py line 425`

> ```python
> try:
>     stderr_output = stderr.decode('utf-8')
> except UnicodeDecodeError:
>     stderr_output = stderr.decode('cp949')
> ```

**Comment by jonlabelle** [comment]
Hi @peppy0510: Can you pull down [this branch](https://github.com/jonlabelle/SublimeJsPrettier/tree/issue-220-unicode-decode-error-cp949), and let me know if the problem is resolved?
