### ISSUE TITLE
Hang with a specific file (3.5k lines) - ok with prettier CLI

### ISSUE THREAD

**Issue by darkred** [jonlabelle/SublimeJsPrettier#224]
There's [this](https://github.com/tophf/mpiv/raw/master/script.user.js) javascript file (3620 lines, 100KB size).

If I run `prettier -w` in CLI it completes within less than 1 sec (~500 msec).

But, if run `JsPrettier: Format Code` then the node.exe process hangs indefinitely (and ST until I manually kill node.exe), 
with CPU usage ~30% and memory usage growing from 0.3 GB to 1.5 GB ! (I waited ~15 min (!) before I finally killed the process) ! 
*Other, small .js files I tested, all complete within a second.*

<details>
<summary>My system</summary>

- windows 10 x64
- Nodejs 14.9.0 x64
- Prettier 2.1.1 installed globally
- Sublime Text version 3.2.2 dev build 3211 x64
- SublimeJsPrettier 1.30.7 (with `SublimeJsPrettier - User Settings` none/empty)
</details>

<details>
<summary>Prettier config <code>.prettierrc.js</code> (located in <code>C:\Users\Kostas</code>)</summary>

```javascript
module.exports = {
	printWidth: 80,
	tabWidth: 4,
	useTabs: true,
	singleQuote: true,
};
```
</details>

<details>
<summary>STR</summary>

- download https://github.com/tophf/mpiv/raw/master/script.user.js
- open command prompt, run `prettier -w "script.user.js"`: it will complete within less than 1 sec (~500msec)

---

- Now, redownload https://github.com/tophf/mpiv/raw/master/script.user.js
- open in ST: click: Command Palette | `JsPrettier: Format Code`
- open Task Manager: notice that the node.exe process hangs indefinitely,
with CPU usage ~30% and memory usage grows from 0.3 GB to 1.5 GB! *(I waited ~15 min(!) before I finally killed the process)*

For reference, in Process Explorer it shows that node.js is launched with these arguments:

```
"node"   "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\prettier\bin-prettier.js" --config C:\Users\Kostas\.prettierrc.js --parser babel --use-tabs false --stdin-filepath C:\Users\Kostas\Downloads\script.user.js --cursor-offset 0
```
(I also tried renaming the file to the shortest filename/path possible, e.g. `1.js` and moved it to `C:\` but didtn't help)
</details>

Thank you

**Comment by darkred** [comment]
The exact same issue occurs in a fresh Sublime Text test installation, with only JsPrettier installed.

**Comment by jonlabelle** [comment]
Change [this setting](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L230), to `true`.

**Comment by darkred** [comment]
Thank you very much.
