### ISSUE TITLE
Documentation addition

### ISSUE THREAD

**Issue by gstalnaker** [jonlabelle/SublimeJsPrettier#225]
**Is your feature request related to a problem? Please describe.**

Jon - it would be helpful for folks who are *not* coders, and who thus do not have development environments on their computers, to know *before* they start the process to install SublimeJsPrettier what will happen when they follow the steps for its installation and use in SublimeText.

I found SublimeJsPrettier looking for better Markdown indenting. So, I decided to see what SublimeJsPrettier might do. Unlike many ST3 packages, this one cannot be installed and tested quickly given it's requirements. But I'm an old IT guy (recently retired) so I don't normally worry over such things.

But ... installing nodejs using the Windows .msi also installs python, npm, Visual Studio code, and nodejs -- uses 3+ Gb, takes a fair bit of time, and requires a Windows restart (and I've still not installed prettier). I know that SublimeJsPrettier is what it is and it's requirements are what they are, but the nodejs install is nonetheless a substantial "investment."

**Describe the solution you'd like**

I think the requirements section of your documentation should reference the nodejs requirements, if not summarize them: https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms

I confess it took me quite a bit of digging to find that link. There seems to be no documentation on the nodejs site that explains what the installers will install. One finds out as one performs the install. 

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by jonlabelle** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Jon - it would be helpful for folks who are _not_ coders, and who thus do not have development environments on their computers, to know _before_ they start the process to install SublimeJsPrettier what will happen when they follow the steps for its installation and use in SublimeText.
> 
> I found SublimeJsPrettier looking for better Markdown indenting. So, I decided to see what SublimeJsPrettier might do. Unlike many ST3 packages, this one cannot be installed and tested quickly given it's requirements. But I'm an old IT guy (recently retired) so I don't normally worry over such things.
> 
> But ... installing nodejs using the Windows .msi also installs python, npm, Visual Studio code, and nodejs -- uses 3+ Gb, takes a fair bit of time, and requires a Windows restart (and I've still not installed prettier). I know that SublimeJsPrettier is what it is and it's requirements are what they are, but the nodejs install is nonetheless a substantial "investment."

I'm not sure what Node MSI installer you downloaded, or options you selected when installing, but [JSPrettier](https://packagecontrol.io/packages/JsPrettier) only requires [SublimeText](https://nodejs.org/) and [Node](https://code.visualstudio.com). [Visual Studio Code](https://code.visualstudio.com) is an entirely different editor from [SublimeText](https://www.sublimetext.com). If you're looking for a more complete set of installation instructions for either of the mentioned products, I would suggest visiting their respective web sites and documentation section(s). That said, installing the products is just matter downloading the setup/installer product(s) from the respective web sites. 

> **Describe the solution you'd like**
> 
> I think the requirements section of your documentation should reference the nodejs requirements, if not summarize them: https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms
> 
> I confess it took me quite a bit of digging to find that link. There seems to be no documentation on the nodejs site that explains what the installers will install. One finds out as one performs the install.

Installing Node is just a matter of [downloading](https://nodejs.org/en/download/) the proper installer for your platform (e.g. Windows, macOS, Linux), the running it when the download completes.

> **Describe alternatives you've considered**
> 
> n/a
> 
> **Additional context**
> 
> n/a

**Comment by jonlabelle** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Jon - it would be helpful for folks who are _not_ coders, and who thus do not have development environments on their computers, to know _before_ they start the process to install SublimeJsPrettier what will happen when they follow the steps for its installation and use in SublimeText.
> > I found SublimeJsPrettier looking for better Markdown indenting. So, I decided to see what SublimeJsPrettier might do. Unlike many ST3 packages, this one cannot be installed and tested quickly given it's requirements. But I'm an old IT guy (recently retired) so I don't normally worry over such things.
> > But ... installing nodejs using the Windows .msi also installs python, npm, Visual Studio code, and nodejs -- uses 3+ Gb, takes a fair bit of time, and requires a Windows restart (and I've still not installed prettier). I know that SublimeJsPrettier is what it is and it's requirements are what they are, but the nodejs install is nonetheless a substantial "investment."
> 
> I'm not sure what Node MSI installer you downloaded, or options you selected when installing, but [JSPrettier](https://packagecontrol.io/packages/JsPrettier) only requires [SublimeText](https://nodejs.org/) and [Node](https://code.visualstudio.com). [Visual Studio Code](https://code.visualstudio.com) is an entirely different editor from [SublimeText](https://www.sublimetext.com). If you're looking for a more complete set of installation instructions for either of the mentioned products, I would suggest visiting their respective web sites and documentation section(s). That said, installing the products is just matter downloading the setup/installer product(s) from the respective web sites.
> 
> > **Describe the solution you'd like**
> > I think the requirements section of your documentation should reference the nodejs requirements, if not summarize them: https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms
> > I confess it took me quite a bit of digging to find that link. There seems to be no documentation on the nodejs site that explains what the installers will install. One finds out as one performs the install.
> 
> Installing Node is just a matter of [downloading](https://nodejs.org/en/download/) the proper installer for your platform (e.g. Windows, macOS, Linux), the running it when the download completes.
> 
> > **Describe alternatives you've considered**
> > n/a
> > **Additional context**
> > n/a
