### ISSUE TITLE
Error when user settings omit "prettier_options" key

### ISSUE THREAD

**Issue by lethosor** [jonlabelle/SublimeJsPrettier#227]
## Explain the Issue and Expected Behavior

I recently upgraded to 1.32.0 and had previously customized my "JsPrettier.sublime-settings - User" file. Previously, saving JS files would run them through prettier, but it now produces the following error:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "~/.config/sublime-text-3/Packages/JsPrettier/JsPrettier.py", line 274, in run
    prettier_ignore_filepath, source_file_path)
  File "~/.config/sublime-text-3/Packages/JsPrettier/JsPrettier.py", line 513, in parse_prettier_options
    option_value = get_sub_setting(view, option_name)
  File "~/.config/sublime-text-3/Packages/JsPrettier/jsprettier/sthelper.py", line 44, in get_sub_setting
    value = settings.get(PRETTIER_OPTIONS_KEY).get(key)
AttributeError: 'NoneType' object has no attribute 'get'
```

The problem appears to be [this line](https://github.com/jonlabelle/SublimeJsPrettier/blob/1.32.0/jsprettier/sthelper.py#L44), although I have not attempted to fix this on the plugin's end yet.

I was able to work around this by adding `"prettier_options": {}` to my user settings file. I would expect this to be unnecessary, because this key is present (with several options) in the "JsPrettier.sublime-settings - Default" file, and as far as I know, settings were previously being retrieved from there successfully.

## Prettier version

n/a

## JsPrettier Plug-in Version

1.32.0

I am unsure how to check which version I was using previously. I'm not seeing an obvious change between 1.31.0 and 1.32.0 that could have caused this, so it may have been an older version.

## Platform Details

- Sublime Text Version: 3.2.2
- Sublime Text Build: 3211
- Sublime Text Architecture: x86_64
- Operating System Name: Ubuntu Linux
- Operating System Version: 18.04
- Operating System Architecture: x86_64

## Generated Prettier command line arguments

n/a, prettier does not run

## Is the same behavior observed when run against Prettier directly?

n/a

## The contents of your `User/JsPrettier.sublime-settings` file

Problematic (causes the error; I was using this successfully previously):

```
{
    "auto_format_on_save": true,
    "debug": true,
    "auto_format_on_save_excludes": ["redacted"],
    "node_path": "redacted/.nvm/versions/node/v13.13.0/bin/node"
}
```

Fixed:

```
{
    "auto_format_on_save": true,
    "debug": true,
    "auto_format_on_save_excludes": ["redacted"],
    "node_path": "redacted/.nvm/versions/node/v13.13.0/bin/node",
    "prettier_options": {}
}
```

## Steps to reproduce the behavior

Unsure as I have not attempted a clean install yet:

1. Install JsPrettier
2. Create a user settings file similar to above - define `auto_format_on_save` but not `prettier_options`
3. Save a JS file
4. Check the sublime console for output

**Comment by jonlabelle** [comment]
Hi @lethosor... I can't seem to reproduce the problem using the settings defined in the issue.

But maybe try re-installing the plugin from [Package Control](https://github.com/jonlabelle/SublimeJsPrettier#install-jsprettier-via-package-control); close, re-open Sublime Text to ensure everything gets loaded properly/cleanly.

**Comment by lethosor** [comment]
Reinstalling the package seems to have fixed this - thanks! (I had previously tried restarting Sublime with no luck, but forgot to mention that.)
