### ISSUE TITLE
Provide an after prettier done hook

### ISSUE THREAD

**Issue by viankakrisna** [jonlabelle/SublimeJsPrettier#23]
Currently i want to run `eslint --fix` after prettier done its job. Anyone knows how to do it?

**Comment by jonlabelle** [comment]
You could probably accomplish this with a [Macro](http://docs.sublimetext.info/en/latest/extensibility/macros.html). Here's a decent [article](https://webdesign.tutsplus.com/articles/quick-tip-banish-repetitive-tasks-with-sublime-text-2-macros--webdesign-6398) to get you started.

**Comment by jonlabelle** [comment]
@viankakrisna [Here's a plug-in](https://github.com/jisaacks/ChainOfCommand) (Chain of Command) that might offer some assistance.
