### ISSUE TITLE
.prettier.yaml Config File Not Detected At Project Level - User Settings Being Applied Instead

### ISSUE THREAD

**Issue by loganknecht** [jonlabelle/SublimeJsPrettier#231]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

When I have a `.prettier.yaml` file in my project's root level it is not being detected on save settings.

What happens is that my default settings from my `JsPrettier.sublime-settings` is applied instead.

![image](https://user-images.githubusercontent.com/1308524/99441423-b2045580-28cc-11eb-84a7-fbf0cdfe761c.png)

## Prettier version

To show the currently installed prettier version, run the following command:

```bash
$ prettier --version
2.1.2
```

## JsPrettier Plug-in Version

```json
{
  "name": "sublime-js-prettier",
  "version": "1.34.1",
  "description": "JsPrettier is a Sublime Text Plug-in for Prettier, the opinionated code formatter.",
  "author": "Jon LaBelle",
  "license": "MIT",
  "dependencies": {
    "prettier": "latest"
  },
  "repository": "jonlabelle/SublimeJsPrettier",
  "keywords": [
    "sublime",
    "sublimetext",
    "plugin",
    "prettier",
    "jsprettier",
    "formatter",
    "javascript",
    "css"
  ],
  "files": [
    "*.md",
    ".no-sublime-package",
    "Context.sublime-menu",
    "JsPrettier.py",
    "JsPrettier.sublime-commands",
    "jsprettier/**",
    "Main.sublime-menu",
    "messages.json",
    "messages/*.txt"
  ],
  "bugs": {
    "url": "https://github.com/jonlabelle/SublimeJsPrettier/issues"
  },
  "homepage": "https://github.com/jonlabelle/SublimeJsPrettier"
}
```

## Platform Details

Sublime Text Version: 3.2.2
Sublime Text Build: 3211
OS: OSX
OS Version: Catalina 10.15.7
OS Architecture: Unknown

## Generated Prettier command line arguments

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/lknecht/.nvm/versions/node/v12.17.0/bin/prettier --no-config --print-width 120 --tab-width 4 --single-quote false --trailing-comma none --bracket-spacing true --jsx-bracket-same-line false --parser babel --semi true --require-pragma false --prose-wrap preserve --arrow-parens always --html-whitespace-sensitivity css --quote-props as-needed --vue-indent-script-and-style false --embedded-language-formatting auto --jsx-single-quote false --use-tabs false --stdin-filepath /Users/lknecht/Repositories/project-api/test/unit/testruns_controller.test.js --loglevel debug --cursor-offset 10603

Prettier reported the following output:

[debug] normalized argv: {"_":[],"bracket-spacing":true,"color":true,"editorconfig":true,"jsx-bracket-same-line":false,"jsx-single-quote":false,"require-pragma":false,"semi":true,"single-quote":false,"use-tabs":false,"vue-indent-script-and-style":false,"config":false,"print-width":120,"tab-width":4,"trailing-comma":"none","parser":"babel","prose-wrap":"preserve","arrow-parens":"always","html-whitespace-sensitivity":"css","quote-props":"as-needed","embedded-language-formatting":"auto","stdin-filepath":"/Users/lknecht/Repositories/project-api/test/unit/testruns_controller.test.js","loglevel":"debug","cursor-offset":10603,"config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}
[debug] '--no-config' option found, skip loading config file.
[debug] applied config-precedence (cli-override): {"filepath":"/Users/lknecht/Repositories/project-api/test/unit/testruns_controller.test.js","arrowParens":"always","bracketSpacing":true,"cursorOffset":10603,"embeddedLanguageFormatting":"auto","htmlWhitespaceSensitivity":"css","jsxBracketSameLine":false,"jsxSingleQuote":false,"parser":"babel","printWidth":120,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":true,"singleQuote":false,"tabWidth":4,"trailingComma":"none","useTabs":false,"vueIndentScriptAndStyle":false}
```

## Is the same behavior observed when run against Prettier directly?

Unknown

## The contents of your `User/JsPrettier.sublime-settings` file

```json
{
    "debug": "true",
    "prettier_cli_path": "/Users/lknecht/.nvm/versions/node/v12.17.0/bin/prettier",
    "auto_format_on_save": true,
    "custom_file_extensions": ["sublime-keymap", "sublime-settings", "yaml"],
    "prettier_options": {
        "printWidth": 120,
        "tabWidth": 4,
        "trailingComma": "none"
    }
}
```

## The contents of your `<project_name>.sublime-project` file (if applicable)

N/A

## Steps to reproduce the behavior

1. Make Project
1. Add `.prettierrc.yaml`
1. Add Configurations
1. Save

**Comment by loganknecht** [comment]
None of these have helped

# 62
# 66
# 191

**Comment by loganknecht** [comment]
Hello!

Is there anyone who can speculate on this :)

**Comment by loganknecht** [comment]
Hello!

Shameless bump, because I have no idea what I'm doing and would love guidance

❤️  ❤️  ❤️  ❤️  ❤️

**Comment by jonlabelle** [comment]
@loganknecht: Just to clarify - `.prettier.yaml` is not [known/supported](https://prettier.io/docs/en/configuration.html) config file Prettier will detect.

Can you confirm the file that *can't* be detected is named either `.prettierrc.yaml` or `.prettierrc.yml`?

**Comment by klchoi** [comment]
@loganknecht have you try restart ST? For me, after checkout the debug message, I find that `--no-config` param was passed to prettier. I guess it happen because I was create `.prettierrc` after I ran prettier. Restart ST fix that issue for me.

**Comment by loganknecht** [comment]
Alright. I guess that was the issue @klchoi 

I'm marking this closed. Thank you @jonlabelle and everyone for taking the time to read my confusion!
