### ISSUE TITLE
Consider renaming to 'SublimePrettier'

### ISSUE THREAD

**Issue by dvcrn** [jonlabelle/SublimeJsPrettier#237]
Not a feature request per-se, but with the official tool now called `prettier`, how about following suite and renaming this to "SublimePrettier"? 😄 Is there still a reason to keep the `Js` in the name?

**Comment by jonlabelle** [comment]
I totally agree with you, and that was the name I used when [originally submitting](https://github.com/wbond/package_control_channel/pull/6069) the package to Package Control. However I was [asked](https://github.com/wbond/package_control_channel/pull/6069#issuecomment-272386149) by an approver to change the name from SublimePrettier to *SublimeJsPretter*.

I believe changing the name now would undoubtedly cause unexpected downtimes for the installers, especially in light of the recent [Package takeover vulnerability](https://packagecontrol.io/news#2021-02-24-Package_Takeover_Vulnerability_Notification).
