### ISSUE TITLE
(see #179) Code folding is scrambled

### ISSUE THREAD

**Issue by neaumusic** [jonlabelle/SublimeJsPrettier#238]
I see [this bug](https://github.com/jonlabelle/SublimeJsPrettier/issues/179) https://github.com/jonlabelle/SublimeJsPrettier/issues/179 was closed, but I think it should be re-opened since it's still a major issue

**Comment by neaumusic** [comment]
I think a good solution would be to simply re-open any formatted lines

**Comment by jonlabelle** [comment]
Hi @neaumusic. I agree, but did you [read through](https://github.com/jonlabelle/SublimeJsPrettier/issues/179#issuecomment-506924868) the discussion?

**Comment by neaumusic** [comment]
Yeah I read through the discussion! That’s unfortunate the plugin didn’t work. I can try to look into this sometime but wouldn’t have much to go off other than interpreting code 🙂

**Comment by neaumusic** [comment]
I don’t think this issue should be closed.
