### ISSUE TITLE
[Question] Is it possible to use with Prettier Community plugins?

### ISSUE THREAD

**Issue by andreseduardop** [jonlabelle/SublimeJsPrettier#239]
JsPrettier works great on its own.
I wonder if it works together with other [Community Plugins for Prettier](https://prettier.io/docs/en/plugins.html)?

Specifically, I haven't gotten it to work with [prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template).

**Comment by jonlabelle** [comment]
Hi @andreseduardop. I would *think* so... but I haven't tried any of them myself.

Is there a particular community plugin you're looking to use?

**Comment by andreseduardop** [comment]
Hi @jonlabelle. 

Prettier works fine for me in VS Code. But, I can't get it to work with the Go plugin ["prettier-plugin-go-template"](https://github.com/NiklasPor/prettier-plugin-go-template).

**Comment by jonlabelle** [comment]
Here's an [example SublimeText project](https://github.com/jonlabelle/SublimeJsPrettier/files/6498394/jsprettier-and-prettier-community-plugin-example.zip) you can reference that uses the Prettier Community Plugin [prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template) to format `*.gohtml` files.

**Comment by isnifer** [comment]
@jonlabelle hello, same question from me. Can't use prettier with https://github.com/trivago/prettier-plugin-sort-imports. Could you please help?
Getting this:
```
[warn] Ignored unknown option { importOrderSeparation: false }.
[warn] Ignored unknown option { experimentalBabelParserPluginsList: ["jsx"] }.
```
