### ISSUE TITLE
Feature: enable JsPrettier only if prettier is in package.json

### ISSUE THREAD

**Issue by alexkuz** [jonlabelle/SublimeJsPrettier#24]
It would be nice to have an option that will allow `auto_format_on_save` only when `prettier` is in package dependencies, so there's no need to setup `.sublime-project` for each project.

**Comment by jonlabelle** [comment]
Hi @alexkuz, thanks for the suggestion. Though I would argue that the majority of JsPrettier users have Prettier installed globally (e.g.: `npm install -g prettier`), and introducing such a feature would add quite a bit of complexity (and side-affects) attempting to determine the intention of the plug-in, in out- of-scoped configurations.

**Comment by alexkuz** [comment]
Well, globally installed prettier is what causing this problem. With the current plugin I can never use `auto_format_on_save=true` globally (or locally - if I can't add `.sublime-project` to the package).

Just for the reference - SublimeLinter has a similar setting in `node_linter`, that is disabled by default but uses `package.json` when enabled:
https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py#L65

**Comment by jonlabelle** [comment]
To clarify, are you saying that the `auto_format_on_save` does not work at all for you?

**Comment by alexkuz** [comment]
No, it works just fine - what I mean is that it works for any js file (obviously) if I set it globally. And if I set globally `auto_format_on_save=false`, I can't enable it for a particular project without adding `.sublime-project` file (which can be an issue if I don't own that project, for example).
