### ISSUE TITLE
Help with prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by jonlabelle** [jonlabelle/SublimeJsPrettier#240]
*@jonlabelle hello, same question from me. Can't use prettier with https://github.com/trivago/prettier-plugin-sort-imports. Could you please help?*

*Getting this:*

```
[warn] Ignored unknown option { importOrderSeparation: false }.
[warn] Ignored unknown option { experimentalBabelParserPluginsList: ["jsx"] }.
```

Originally posted by @isnifer in https://github.com/jonlabelle/SublimeJsPrettier/issues/239#issuecomment-846416915

**Comment by jonlabelle** [comment]
@isnifer, can you package up minimal working project of your configuration, and attach it to this post?

Here's an [example](https://github.com/jonlabelle/SublimeJsPrettier/files/6498394/jsprettier-and-prettier-community-plugin-example.zip).

**Comment by isnifer** [comment]
@jonlabelle thanks for the response, it's just enough to add these two lines to any of your project. I think plugin can just ignore unknown config lines and not exit with 0 code

**Comment by jonlabelle** [comment]
Worked fine for me. Please reference this [example project](https://github.com/jonlabelle/SublimeJsPrettier/files/6527323/jsprettier-and-prettier-plugin-sort-imports.zip) which uses [@trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports) to sort imports.

**Comment by isnifer** [comment]
@jonlabelle actually, confirm. Your example is working. And my project started working when I added prettier as devDependency lmaaao. (I really don't know why I didn't have it)
Thanks
