### ISSUE TITLE
[Question] Could not resolve Prettier config file, will use options defined in Sublime Text.

### ISSUE THREAD

**Issue by Prinzhorn** [jonlabelle/SublimeJsPrettier#241]
So I've been using SublimeJsPrettier for a while now and it worked great, thanks!. Now I started a new project and it just couldn't find the config file (`prettier` in package.json). The structure was:

```
project/
  src/
    App.svelte
  package.json
```

Saving `App.svelte` would just not use my `"parser": "svelte"` override from package.json, which works perfectly in another project. I reinstalled SublimeJsPrettier, I closed and reopened Sublime multiple times.

Then I tried the following:

```
project/
  App.svelte
  src/
    App.svelte
    foo/
      App.svelte
  package.json
```

For some reason `src/foo/App.svelte` worked as expected, but not the other two.

Ok, so I opened `/home/alex/.config/sublime-text-3/Packages/JsPrettier` in sublime and edited `find_prettier_config` to `print` what `generate_dirs` yields to see if it searches in the correct places. I also removed `@memoize`. I didn't get any logs, so I figured I need to fully close Sublime. I reopened Sublime, got the logs from my `print` **and suddently _all_ of the App.svelte worked, not just one of them**.

So what the hell is going on here? I've spent like two hours trying to make this work losing my mind and it was some sort of broken caching I assume? I don't know how Sublime internally handles all the Python stuff, but I assume fully closing it should have cleared the memoize cache?

I don't get it. I just removed `prettier` from `package.json` and none of the three files worked. I added it back and _all three_ worked. There is something super fishy going on. I assume originally the `src/foo/App.svelte` worked because for the other two it had the result cached. But why that would be the case across restarting Sublime is beyond me. Maybe the `plugin_host` process didn't exit...BUT I had this issue on Wednesday, came back today and it still didn't work but there was prettier in my package.json.

So I'm not even sure what the point of this whole thread is now. Any idea what's happening? Maybe `@memoize` wasn't a good idea after all?

**Comment by jonlabelle** [comment]
Hi @Prinzhorn. Try adding a config precedence in your [settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L264):

```json
"additional_cli_args": {
    "--config-precedence": "prefer-file"
}
```

**Comment by Prinzhorn** [comment]
Thanks! Like I said, this worked fine in a different project with the exact same setup. I've had `"--config-precedence": "file-override"` set for month, possibly years. There was definitely something fishy going on with memoization. It caches the prettier config path using the directory the file is in. That explains why it was working with a Svelte file I created in a new folder but not with the ones that existed in folders where I've previously saved a file.

The only thing I don't understand is why the memoization seemingly survived a sublime restart.

To summarize: I've saved a Svelte file _before_ having a `prettier` section in my package.json. Then I updated the package.json but the Svelte file still wasn't formatting. Which is expected behavior because memoization, but confusing to the user.  Then I ran into some edge case where closing sublime wasn't clearing the cache, possible because the `plugin_host` process didn't exit it still held the memory? So maybe closing all sublime windows didn't actually close everything, who knows.

I get that memoization avoids finding the config file every single time you save something. But maybe it shouldn't be cached if

1. ` find_prettier_config` returns `None`
2. **and** `file-override` is specified

because otherwise you run into inconsistencies when setting up a new project like I did.

**Comment by jonlabelle** [comment]
I went ahead and pulled out path memoization.

And I agree, It can be a bit confusing to the end-user when paths are adjusted after formatting a particular file. The previous implementation was very basic, and needs to be overhauled to handle such commons scenarios as manual path updates.

**Comment by Prinzhorn** [comment]
Thanks! Let's hope this doesn't cause a performance regression with `auto_format_on_save`
