### ISSUE TITLE
[Question] How to get JSPrettier to work with WSL files

### ISSUE THREAD

**Issue by ecambronerosaba** [jonlabelle/SublimeJsPrettier#242]
Whenever I try to auto format with prettier on files I'm running on WSL Ubuntu 18.04 on Windows 10 I run into the following error:
```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

'\\wsl$\Ubuntu-18.04\home\ecambronero\Developer\Personal\react\pics'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The filename, directory name, or volume label syntax is incorrect.


Prettier process finished with exit code 1.
```
My prettier cli path is configured as:
```
    "prettier_cli_path": "C:/Users/Name/AppData/Local/Yarn/bin/prettier.cmd",
```
and my node path is configured as:

```
    "node_path": " C:/Program Files/nodejs/node.exe",
```

There doesn't seem to be any resources on how to get this to work. Thanks!

**Comment by jonlabelle** [comment]
Hi @ecambronerosaba. Interesting. So it looks like your paths to Prettier and Node are pointing back to the Windows environment, which I don't think the WSL allows.

Can you try installing Node and Prettier in the WSL, and update the paths accordingly?

**Comment by ecambronerosaba** [comment]
That seemed to do the trick! Thank you so much! If anyone else runs into this issue I updated my `prettier_cli_path` to:  
 ```//wsl$/Ubuntu-18.04/home/name/.nvm/versions/node/v14.17.3/bin/prettier``` 

and my `node path` to:  
 ```//wsl$/Ubuntu-18.04/home/name/.nvm/versions/node/v14.17.3/bin/node```
