### ISSUE TITLE
Please support yarn 2. node_modules is empty

### ISSUE THREAD

**Issue by zhea55** [jonlabelle/SublimeJsPrettier#243]
Currently with yarn 2, node_modules directory is empty.

Could u add a feature, auto find yarn's prettier bin.

` yarn run prettier` should do the work.

**Comment by jonlabelle** [comment]
Hi @zhea55. What path should be checked in place of `node_modules`?

**Comment by zhea55** [comment]
yarn 2 project is very rare。
