### ISSUE TITLE
Prettier fails when cursor is in `<script>` or `<style>`.

### ISSUE THREAD

**Issue by ehzro3** [jonlabelle/SublimeJsPrettier#245]
## Explain the Issue and Expected Behavior

jsPrettier error occurs when the cursor is placed within `<script>` or `<style>`. It says Prettier failed for ridiculous reasons such as a HTML having `<!DOCTYPE html>`, Or a completely normal and single `</form>` trying to closing the block twice.

## Prettier version

   2.5.0

## JsPrettier Plug-in Version

    ...
    "name": "sublime-js-prettier",
    "version": "1.50.0",
    ...

## Platform Details

Provide your Sublime Text version and Platform details.

    - Sublime Text Version: 4121
    - Sublime Text Build: 4121
    - Operating System Name: MacOS Monterey
    - Operating System Version: 12.0.1

## Generated Prettier command line arguments

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------

[debug] normalized argv: {"_":[],"color":true,"editorconfig":true,"use-tabs":true,"config":"/Users/taro/playground/sveltekit-skeleton/.prettierrc","parser":"babel","stdin-filepath":"/Users/taro/playground/sveltekit-skeleton/src/routes/index.svelte","loglevel":"debug","cursor-offset":330,"config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}
[debug] load config file from '/Users/taro/playground/sveltekit-skeleton/.prettierrc'
[debug] loaded options `{"useTabs":true,"singleQuote":true,"trailingComma":"none","printWidth":100}`
[debug] applied config-precedence (cli-override): {"filepath":"/Users/taro/playground/sveltekit-skeleton/src/routes/index.svelte","cursorOffset":330,"parser":"babel","printWidth":100,"singleQuote":true,"trailingComma":"none","useTabs":true}

## Is the same behavior observed when run against Prettier directly?

No.

## The contents of your `User/JsPrettier.sublime-settings` file

{
	"debug": true,
	"auto_format_on_save": true,
	"custom_file_extensions": [
		"svelte",
	],
	"prettier_options": {
		"semi": false,
		"singleQuote": true,
		"trailingComma": "all"
	}
}

## Steps to reproduce the behavior

1. Open up a HTML or a Svelte in ST.
2. Place cursor anywhere between `<script>` or `<style>`.
3. Format with jsPrettier.

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jonlabelle** [comment]
Hi @ehzro3. Looks like the default parser (*babel*) is being used for Svelte files.

Try adding an overrides section in your *.prettierrc* file (`/Users/taro/playground/sveltekit-skeleton/.prettierrc`) for Svelte files, then update your JsPrettier plugin settings so Prettier config files are the preferred method for reading options.

**.prettierrc:**

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

**JsPrettier.sublime-settings:**

```json
"additional_cli_args": {
    "--config-precedence": "file-override"
}
```

**Comment by ehzro3** [comment]
Thanks @jonlabelle !  
I have no idea how it works but it does!
