### ISSUE TITLE
Jumps to top of page when Prettier is run. 

### ISSUE THREAD

**Issue by joelnz** [jonlabelle/SublimeJsPrettier#247]
When I run prettier (both on save and from the control-click-dialogue), it jumps to the top of the page.

This is quite frustrating especially when working with large files. 

Sublime version: 4126
Prettier Version 1.50.0
Mac OS Monterey 12.0.1
Settings:
{
        "debug": false,
        "prettier_cli_path": "",
        "node_path": "",
        "auto_format_on_save": true,
        "auto_format_on_save_excludes": [],
        "auto_format_on_save_requires_prettier_config": false,
        "allow_inline_formatting": false,
        "custom_file_extensions": [],
        "max_file_size_limit": -1,
        "disable_tab_width_auto_detection": false,
        "disable_prettier_cursor_offset": false,
        "additional_cli_args": {"--config": "~/.prettierrc",},
        "prettier_options": {
            "printWidth": 80,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "es5",
            "bracketSpacing": true,
            "bracketSameLine": false,
            "jsxSingleQuote": false,
            "parser": "babel",
            "semi": true,
            "requirePragma": false,
            "proseWrap": "preserve",
            "arrowParens": "always",
            "htmlWhitespaceSensitivity": "css",
            "quoteProps": "as-needed",
            "vueIndentScriptAndStyle": false,
            "embeddedLanguageFormatting": "auto",
            "editorconfig": true
        }
    }

**Comment by jonlabelle** [comment]
Hi @joelnz. Unfortunately you are using a version of Prettier (1.50.0) that is no longer supported. Please consider upgrading Prettier (v2.4 or above) to resolve this issue.

**Comment by joelnz** [comment]
Sorry I meant that my SublimeJsPrettier version is 1.50.0
My Prettier version is 2.5.1.
