### ISSUE TITLE
Use prettierd for better performance?

### ISSUE THREAD

**Issue by adamwathan** [jonlabelle/SublimeJsPrettier#248]
**Is your feature request related to a problem? Please describe.**

Running this package within Sublime is a lot slower than using Prettier in VS Code, I expect because here we have to boot up the node process from scratch every time but since VS Code is JS-based there's a persistent JS environment running so Prettier is always "hot" and ready to go.

**Describe the solution you'd like**

Discovered [prettierd](https://github.com/fsouza/prettierd) today which is a persistent Prettier daemon designed to let you run Prettier very quickly without startup penalties. Got me wondering if there's a way to integrate that concept into this package to improve the performance.

Great work by the way, thanks for maintaining this! ❤️

**Comment by AirBashX** [comment]
> 嗨@adamwathan。如果在[设置](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L57)中指定 prettierd 的路径会发生什么？

------------------
 JsPrettier ERROR 
------------------
Prettier reported the following output:
Prettier process finished with exit code 1

**Comment by jonlabelle** [comment]
Curious if this [wrapper](https://github.com/ruyadorno/prettierme) would work...

> *Alternatively, one can use [prettierme](https://github.com/ruyadorno/prettierme) to integrate directly with other editors.*

**Comment by jonlabelle** [comment]
I'm not looking to support this particular feature at this time, but please feel free to open a pull request.
