### ISSUE TITLE
`node_path` not determined automatically for project using nvm 

### ISSUE THREAD

**Issue by macgyver** [jonlabelle/SublimeJsPrettier#249]
I need to manually set the `node_path` in order for JsPrettier to work in my project - ideally it would figure this information out automatically because the location could be different for other projects, e.g. one project uses Prettier v2 on Node 14 and another project uses Prettier v3 on Node 18, so I can't just set one node path that will work for all my projects.

This project uses [nvm](https://github.com/nvm-sh/nvm) which is a pretty popular method for controlling which version of node is used in each shell. Typically the node version that should be used for a directory is declared in a `.nvmrc` file, so the process for finding what version of node should be used to prettier a file in a project that uses `nvm` would be to traverse the parent paths until you encounter a `.nvmrc` file, and then `cat .nvmrc | nvm which` to find the node path.

Maybe this is an issue for prettier to handle? but I noticed there is a `which` function in your utils that is used to find the node path, and you have the configuration option to set the node path as well, so perhaps this is something that can be fixed here.

Here's the error output btw:

```
{{ my app folder }}/node_modules/.bin/prettier --config{{ my app folder }}/.prettierrc --parser babel --use-tabs false --stdin-filepath {{my app folder}}/{{ path to file }} --loglevel debug --cursor-offset 163

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

env: node: No such file or directory


Prettier process finished with exit code 127.
```

**Comment by jonlabelle** [comment]
@macgyver. Can't you just use NVM's bin [environment variable](https://github.com/nvm-sh/nvm#environment-variables) in your [prettier_cli_path](https://github.com/jonlabelle/SublimeJsPrettier/blob/6a5d291188cb4036646705f28a84525fac84c668/JsPrettier.sublime-settings#L57)? e.g.:

```json
"prettier_cli_path": "$NVM_BIN/prettier"
```

**Comment by jonlabelle** [comment]
> mmm it is cool that Sublime can interpolate environment variables in its settings file.. although I don't understand what environment it is running in? when I run the commands above it seems that `$NVM_BIN` is an empty string - normally for me it would be set after `~/.zshrc` is executed.

Your `$NVM_BIN` variable would have to be set and exported *prior* to opening Sublime Text otherwise it won't be picked it up. And you may need to look at [*Calling nvm use automatically in a directory with a .nvmrc file*](https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file).

> I can't use your suggestion for the `prettier_cli_path` because it would always point to the globally installed `prettier` for the currently active `node`, but a different version of Prettier may be required for _each project_ using that version of node. To behave correctly it would need first to look for the `prettier` bin in the closest `node_modules` folder to the file being saved, and fall back to the global `node_modules` after that. Does that make sense?

I'm not sure I follow this scenario.

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
