### ISSUE TITLE
Refactor code to support CudaText (text editor)

### ISSUE THREAD

**Issue by Alexey-T** [jonlabelle/SublimeJsPrettier#251]
I’d want to reuse part of your code for CudaText editor plugin (Sub plugin for CudaFormatter), so can I ask you to refactor? I will need the python module which 

- don’t use ST api (all text and options must be passed as parameters)
- takes string (miltiline string) or list of strings - and formats it via Prettier, and returns formatted str
- calls of Node.js maybe will be included to new module 

Can you help please?

@jairomartineza @olehl Are you interested to help here? I will give some donation

**Comment by jonlabelle** [comment]
Hi @Alexey-T. Feel free to use any part of this plugin in your project as long as it adheres to the [license](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/LICENSE.txt).
