### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by jt3k** [jonlabelle/SublimeJsPrettier#254]
i installed jsPrettier in sublime 3
then  press cmd+shift+p → jsprettier → enter
and I see this in the console ↓↓↓
```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

env: node: No such file or directory


Prettier process finished with exit code 127.

```

this problem has been around for many years. I would like you to fix this. How long can you wait?

**Comment by jt3k** [comment]
you don't handle cases where node-js is installed with nvm

why don't you try shell command `which node` instead of heuristically looking for the appearance of the node binary?

**Comment by jonlabelle** [comment]
Duplicate. Please see #249.

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
