### ISSUE TITLE
JsPrettier ERROR /usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by thebravoman** [jonlabelle/SublimeJsPrettier#255]
Basically the same as https://github.com/jonlabelle/SublimeJsPrettier/issues/189 but 189 is closed and no new information is allowed. Could not understand why it is closed. 

Happened with me now. 

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

/usr/bin/env: ‘node’: No such file or directory


Prettier process finished with exit code 127.
```

Now I have to code and hardcode node_path to be something along the lines of 

```
$ which node
/home/kireto/.nvm/versions/node/v14.18.2/bin/node
```

Not sure how stable this as we are changing node version and I guess it should somehow find the node path automatically. Probably like it was suggested in the previous issue - by using the 'which' command.

**Comment by jonlabelle** [comment]
See https://github.com/jonlabelle/SublimeJsPrettier/issues/249#issuecomment-1046168097

**Comment by thebravoman** [comment]
I tried. This happened
![Screenshot from 2022-06-06 11-45-38](https://user-images.githubusercontent.com/1311493/172127852-5d981766-b133-495b-88a1-0576ee466590.png)

$NVM_BIN is empty. Who should be setting this?

**Comment by jonlabelle** [comment]
> $NVM_BIN is empty. Who should be setting this?

NVM should set this in your environment when you open a terminal session (via bash profile); ***then*** open Sublime Text.

**Comment by jonlabelle** [comment]
You just have to load [NVM](https://github.com/nvm-sh/nvm#usage) ***prior*** to opening Sublime Text so the appropriate environment variables are picked up.

```bash
cd <path/to/my/project>
nvm use <version>
subl .
```

Works great for me!

**Comment by thebravoman** [comment]
"Then we ship your machine" was the joke :)

Thanks for the helping out here. Doesn't work for me. I am not starting
subl in this way but with search of subl and enter.

**Comment by macgyver** [comment]
lol ya, this is a tricky one - how do you propose this plugin could be made aware of all the possible ways of managing the node version / installed dependencies for a project? it's tricky enough to do it just for `nvm`, but what about `n`? and i'm sure there are others...

**Comment by thebravoman** [comment]
I would propose "which node".

**Comment by jonlabelle** [comment]
> I would propose "which node".

@thebravoman Well that's [exactly what the plug-in does](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/jsprettier/sthelper.py#L215).

**Comment by thebravoman** [comment]
Hm. Clever.

Than why do we need to specify the node path in the config?

 For me "which" works as node is in /usr/bin and I don't know of a case in
which it can not be found.

Is the config only read if which returns none?

**Comment by jonlabelle** [comment]
> Hm. Clever. Than why do we need to specify the node path in the config? For me "which" works as node is in /usr/bin and I don't know of a case in which it can not be found. Is the config only read if which returns none?

@thebravoman You shouldn't need to specify a path to `node` if it's in `/usr/bin`. Every path that exists in your environment `$PATH` variable [will be traversed](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/jsprettier/util.py#L241). However, if you use NVM installed Node.js, you need run [these steps first](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).

I'm curious what your `$PATH` currently looks like. Run the following command in a terminal session and post your results...

```bash
echo -e ${PATH//:/\\n}
```
