### ISSUE TITLE
Plugin expects `.prettierrc`

### ISSUE THREAD

**Issue by ran-dall** [jonlabelle/SublimeJsPrettier#257]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [✅] **Explain the Issue and Expected Behavior**
- [✅] **Prettier version**
- [✅] **JsPrettier Plug-in Version**
- [✅] **Platform Details**
- [✅] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

On [Prettier's Configuration File page](https://prettier.io/docs/en/configuration.html), they list many ways to pass the configuration; however, this extension seems to only look for `.prettierrc`, and will complain in the console (with debug enabled) if it doesn't find it.

## Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    2.6.2

## JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.60.6",
    ...

## Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 4
    - Sublime Text Build: 4126
    - Sublime Text Architecture: amd64
    - Operating System Name: Gentoo Linux
    - Operating System Version: 5.15.41
    - Operating System Architecture: amd64

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

1. Enable Debugging
2. Rename `.prettierrc` to `.prettier.json` or any of the other options on the [Prettier's Configuration File page](https://prettier.io/docs/en/configuration.html)
3. Observe failure on console

**Comment by jonlabelle** [comment]
Hi @ran-dall. First off, thanks for filling out the issue request form!

So it looks like you're just missing the ***rc*** suffix at the end of your filename, and before the file extension (.json). So your config filename should be `.prettierrc.json`. See the [Prettier configuration](https://prettier.io/docs/en/configuration.html) docs page for the complete list.
