### ISSUE TITLE
Allow for disabling default Prettier options

### ISSUE THREAD

**Issue by queengooborg** [jonlabelle/SublimeJsPrettier#259]
Normally when running Prettier, if an option is not specified, it (usually) has no effect.  However, because all of the options are predefined in the settings, I end up having formatting applied to projects that shouldn't be applied.  I'd love for there to be a way to disable the options defined in Sublime Text settings (say, set `prettier_options` to `null` or have an additional parameter) so I don't have to consistently reformat my files in ESLint afterwards.

**Comment by jonlabelle** [comment]
Hi @queengooborg. Try adding an [additional cli arg](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L264) for [--config-precedence](https://prettier.io/docs/en/cli.html#--config-precedence), with a value of **file-override**:

```json
"additional_cli_args": {
  "--config-precedence": "prefer-file"
}
```

See if this produces the behavior you're looking for.
