### ISSUE TITLE
JsPrettier using html parser instead of svelte

### ISSUE THREAD

**Issue by ghost** [jonlabelle/SublimeJsPrettier#261]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the Issue and Expected Behavior**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior
JsPrettier using `html` parser when formatting `svelte` instead of inferring from `.prettierrc` or file name. (`--parser html` in CLI debug)

After some digging, I assume the plugin concludes that it is formatting `html` when it got here.
https://github.com/jonlabelle/SublimeJsPrettier/blob/2ff0bf26126c4824c4a579606e14076f4f66dd19/JsPrettier.py#L756
(svelte top scope is `text.html.svelte`)

Adding
https://github.com/jonlabelle/SublimeJsPrettier/blob/2ff0bf26126c4824c4a579606e14076f4f66dd19/JsPrettier.py#L748-L750
```python
if filename.endswith('.svelte'):
  return False
```
makes the plugin just outright refuse the file. I think I'm doing it wrong here.

Adding condition for svelte solve this
```python
elif self.is_svelte(view):
  prettier_options.append(cli_option_name)
  prettier_options.append('svelte')
  continue
```
```python
@staticmethod
def is_svelte(view):
  filename = view.file_name()
  if not filename:
    return False
  scopename = view.scope_name(0)
  if scopename.startswith('text.html.svelte') or filename.endswith('.svelte'):
    return True
  return False
```

I don't know if this is a good way to do it though.
No PR since I'm not fluent in python and quite new at using git in general.

## Prettier version
`2.8.1`

## JsPrettier Plug-in Version
`1.61.0`

## Platform Details
ST4 build 4143 x64
Windows 10

## Generated Prettier command line arguments
```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

D:\svelte\prettier-test\node_modules\.bin\prettier --config D:\svelte\prettier-test\.prettierrc --parser html --use-tabs true --ignore-path D:\svelte\prettier-test\.prettierignore --stdin-filepath D:\svelte\prettier-test\src\routes\test\+page.svelte --loglevel debug --cursor-offset 193

Prettier reported the following output:

[debug] normalized argv: {"_":[],"cache":false,"color":true,"editorconfig":true,"useTabs":true,"config":"D:\\svelte\\prettier-test\\.prettierrc","parser":"html","ignorePath":"D:\\svelte\\prettier-test\\.prettierignore","filepath":"D:\\svelte\\prettier-test\\src\\routes\\test\\+page.svelte","loglevel":"debug","cursorOffset":193,"configPrecedence":"cli-override","debugRepeat":0,"plugins":[],"pluginSearchDirs":[],"__raw":{"_":[],"cache":false,"color":true,"editorconfig":true,"use-tabs":true,"config":"D:\\svelte\\prettier-test\\.prettierrc","parser":"html","ignore-path":"D:\\svelte\\prettier-test\\.prettierignore","stdin-filepath":"D:\\svelte\\prettier-test\\src\\routes\\test\\+page.svelte","loglevel":"debug","cursor-offset":"193","config-precedence":"cli-override","debug-repeat":0,"plugin":[],"plugin-search-dir":[]}}
[debug] load config file from 'D:\svelte\prettier-test\.prettierrc'
[debug] loaded options `{"pluginSearchDirs":".","plugins":["prettier-plugin-svelte"],"useTabs":true,"singleQuote":true,"trailingComma":"es5","proseWrap":"always","htmlWhitespaceSensitivity":"ignore","singleAttributePerLine":true,"svelteSortOrder":"options-scripts-markup-styles","svelteStrictMode":true,"parser":"svelte"}`
[debug] applied config-precedence (cli-override): {"filepath":"D:\\svelte\\prettier-test\\src\\routes\\test\\+page.svelte","cursorOffset":193,"htmlWhitespaceSensitivity":"ignore","parser":"html","plugins":["prettier-plugin-svelte"],"pluginSearchDirs":["."],"proseWrap":"always","singleAttributePerLine":true,"singleQuote":true,"svelteSortOrder":"options-scripts-markup-styles","svelteStrictMode":true,"trailingComma":"es5","useTabs":true}

Prettier process finished with exit code 0.
```

## Is the same behavior observed when run against Prettier directly?
no

## The contents of your `User/JsPrettier.sublime-settings` file
```json
// Settings in here override those in "/JsPrettier/JsPrettier.sublime-settings",

{
  "debug": true,
  "max_file_size_limit": 8192,
  "custom_file_extensions": ["svelte"],
  "--config-precedence": "file-override"
}
```

## The contents of your `<project_name>.sublime-project` file (if applicable)
```json
{
  "folders":
  [
    {
      "path": "D:\\svelte\\prettier-test",
      "folder_exclude_patterns":
      [
        "node_modules",
        ".svelte-kit",
      ],
      "file_exclude_patterns":
      [
      ],
    },
  ],
}
```

## Steps to reproduce the behavior
1. Create svelte with `npm create svelte@latest`
2. Opt for `prettier` and `prettier-plugin-svelte`
3. Write obvious code that will get formatted by default rules
4. Run `JsPrettier: Format Code`

**Comment by davidlgj** [comment]
@g6d3np81 I'm having the same issue as you, do you mind sharing what was wrong with your configuration?
