### ISSUE TITLE
[Question] Auto formatting not triggering

### ISSUE THREAD

**Issue by nk9** [jonlabelle/SublimeJsPrettier#262]
I have JsPrettier installed via PackageControl. When I use the Format Code command directly, my JS file is formatted as expected. But although I've turned on `auto_format_on_save` in the project, saving is not triggering auto formatting.

*~/Library/Application Support/Sublime Text/Packages/User/JsPrettier.sublime-settings*
```json
{
	"debug": true,
}
```

*myproj/myproj.sublime-project*
```json
{
    "settings":
    {
        "js_prettier": {
            "auto_format_on_save": true
        }
    }
}
```

When I explicitly call the command, I get this at the top of the output, along with the verbose CLI command and arguments:

```
[JsPrettier DEBUG]: Could not resolve Prettier config file, will use options defined in Sublime Text.
```

When I just save a JS file in this project, nothing happens in the console at all.

When I set `auto_format_on_save` in the `JsPrettier.sublime-settings` file, then auto-save starts working. But that will cause auto-save to happen in all projects, which isn't what I want. The Sublime docs say that [project settings override any user settings](https://www.sublimetext.com/docs/projects.html#settings-key), so I would expect this to work with the change I've made… What am I missing?

**Comment by nk9** [comment]
Happy New Year! Wanted to bump this again after the holidays to see if anyone has an idea what's wrong.

**Comment by jonlabelle** [comment]
Hi @nk9. I'm not able to reproduce the problem based on your params.

Can you zip/archive your entire project and attach to this post, and I will try and reproduce from it.

**Comment by nk9** [comment]
The problem was that I was using Sublime Projects incorrectly. First of all, my `.sublime-project` file didn't include a `"folders"` attribute. But more importantly, I wasn't opening the `.sublime-project` file itself. Instead, I was just opening the folder which _contained_ the project file. Once I fixed both of these issues, `auto_format_on_save` is now working as expected.

This is confusing, and isn't discussed at all in the docs, so I [filed a bug with ST itself](https://github.com/sublimehq/sublime_text/issues/5819). But I'm going to close this, since this was a case of user error.
