### ISSUE TITLE
Saving a php document with cursor inside a script tag causes cursor to jump to top of document

### ISSUE THREAD

**Issue by bdlowery** [jonlabelle/SublimeJsPrettier#265]
**prettier version:** 2.8.3
**Prettier-PHP. version:** 0.19.3
**JsPrettier version:** 1.62.0

1. open a .php file with html, php, and a script tag in it
2. go down to the script tag
3. save the document 
4. your cursor will jump to the start of the document

JsPrettier settings:
```
{
	"debug": true,
	"auto_format_on_save": true,
	"additional_cli_args": { "--config-precedence": "file-override" },
	"custom_file_extensions": ["php"],
	"allow_inline_formatting": true,
}
```

**Comment by jonlabelle** [comment]
It's probably because the PHP plug-in isn't following the [cursor API](https://prettier.io/docs/en/api.html#prettierformatwithcursorsource--options).
