### ISSUE TITLE
Svelte support + bug

### ISSUE THREAD

**Issue by crossinghoods** [jonlabelle/SublimeJsPrettier#266]
When working with .svelte extension file it uses --parser html instead of --parser svelte, which I have corrected on my local version with the following code

```python
  if option_name == 'parser':
                if self.is_typescript(view):
                    prettier_options.append(cli_option_name)
                    prettier_options.append('typescript')
                    continue
                elif self.is_svelte(view):
                    prettier_options.append(cli_option_name)
                    prettier_options.append('svelte')
                    continue
```
- When sublime runs this prettier with this parser; sublime freeze with a spiner for about 3-5 seconds on a small page and the time grows exponentially.
- Prettier v2.2.1
- "prettier-plugin-svelte": "^2.9.0", "svelte": "^3.55.1",
- Mac OS Ventura 13.2.1 (22D68)
- [--config .prettierrc --parser svelte --use-tabs false --ignore-path .prettierignore --stdin-filepath step-1.svelte --loglevel debug --cursor-offset 1319] **Generated Prettier command line arguments**
- [Running with prettier CLI only takes 290ms (no issues), but saving with sublime/jsprettier freezes ] **Is the same behavior observed when run against Prettier directly?**
- [ 
```json
{
  "custom_file_extensions": ["svelte"],
  "disable_prettier_cursor_offset": false,
  "auto_format_on_save_excludes": [
    "*/node_modules/*",
    "*.html",
    "*.json",
    "*.min.js",
    "*-min.js"
  ],
  "auto_format_on_save": true,
  "prettier_cli_path": "/usr/local/bin/prettier",
  "debug": false
}
```
- ] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ format on save, just save] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior
When sublime runs this prettier with this parser; sublime freeze with a spiner for about 3-5 seconds on a small page and the time grows exponentially.

## Prettier version
Prettier v2.2.1

## JsPrettier Plug-in Version
"prettier-plugin-svelte": "^2.9.0", 
"svelte": "^3.55.1",

## Platform Details

Provide your Sublime Text version and Platform details.
    - Sublime Text Version: 4
    - Sublime Text Build: 4147
    - Sublime Text Architecture: Intel
    - Operating System Name: Mac OS
    - Operating System Version: Ventura 13.2.1 (22D68)
    - Operating System Architecture: Intel

**Comment by jonlabelle** [comment]
Hi @crossinghoods. Sounds pretty specific to the svelte plug-in itself, not sure how much help I can be.

You can try disabling the [cursor offset calculation](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L231) and see if that helps.

**Comment by crossinghoods** [comment]
disabled cursor offset calculation and it seems to have worked!

**Comment by nikitaourazbaev** [comment]
I’m seeing a similar issue with Liquid files, they are being parsed with the `html` parser as, because the scope is `text.html.liquid`, it starts with `text.html` so the `is_html` check returns true before it can fail and attempt to infer the parser.

I’ve also modified my local copy of the plugin, adding an `is_liquid` method and placing it before `is_html`, which corrects this (and even works without disabling cursor offset calculation).

As `prettierrc` makes it possible to have overrides and to specify a parser, would it be possible for the plugin to read that value first, before trying to infer the parser?

The relevant part of my prettierrc is:

```json
{
  "plugins": ["@shopify/prettier-plugin-liquid"],
  "overrides": [
    {
      "files": "*.liquid",
      "options": {
        "parser": "liquid-html",
        "singleQuote": false
      }
    }
  ]
}
```

Happy to open a new issue if you don’t feel this is related.
