### ISSUE TITLE
Allow unsaved files to be formatted with prettier without saving

### ISSUE THREAD

**Issue by 0xdevalias** [jonlabelle/SublimeJsPrettier#269]
**Is your feature request related to a problem? Please describe.**

I want to be able to format unsaved files, without being forced to save them.

**Describe the solution you'd like**

As above.

**Describe alternatives you've considered**

Not using this plugin and resorting to other methods (like calling `prettier` directly)

**Additional context**

`prettier` can be passed content directly from stdin, it doesn't need to be saved to a file first.

For this to work, either the `--parser` or `--stdin-filepath` options need to be specified, so that it knows what type of parser needs to be used:

- https://prettier.io/docs/en/options.html#parser
- https://prettier.io/docs/en/options.html#file-path

Eg. the following would pass the contents of the clipboard into `prettier`, format them as JS, and then put them back on the clipboard

```bash
# Method 1
⇒ pbpaste | prettier --parser babel | pbcopy

# Method 2
⇒ pbpaste | prettier --stdin-filepath foo.js | pbcopy
```

While I haven't deeply validated this, one suggested method of implementing this via ChatGPT (GPT-3.5) was:

```python
import subprocess
import sublime
import sublime_plugin

class PrettierFormatCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        # Get the full contents of the file
        code = self.view.substr(sublime.Region(0, self.view.size()))

        # Run Prettier on the code
        prettier_cmd = ['prettier', '--stdin']
        prettier_proc = subprocess.Popen(prettier_cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        prettier_stdout, prettier_stderr = prettier_proc.communicate(code.encode('utf-8'))

        # If Prettier returned an error, print the error message and exit
        if prettier_proc.returncode != 0:
            print(prettier_stderr.decode('utf-8').strip())
            return

        # Replace the contents of the file with the formatted code
        formatted_code = prettier_stdout.decode('utf-8')
        self.view.replace(edit, sublime.Region(0, self.view.size()), formatted_code)
```

Though it would need at least some tweaking, since the `--stdin` command is no longer needed:

- https://github.com/prettier/prettier/issues/4559

**Comment by jonlabelle** [comment]
Hi @0xdevalias. Thanks for the feedback. Unfortunately I'm not looking to implement this enhancement at this time. Mainly because of the file and syntax mapping that takes place, and the fact that most of it would have to be reworked to support formatting file buffers.

**Comment by 0xdevalias** [comment]
@jonlabelle Can you expand on what aspect of the file/syntax mapping that complicates things currently? Skimming the code, it looks like a number of the 'syntax type' detections are using the syntax from the scope (not filename) ([Ref](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L655-L661)), so it would presumably just respect whatever syntax I had set on my unsaved file already, right?

https://github.com/jonlabelle/SublimeJsPrettier/blob/778cda45c212f28054cad3c4aa01002c5a646e4f/JsPrettier.py#L655-L661

Why would things have to be reworked to support formatting file buffers? Skimming through the code just now it looks like there is already code in place to support formatting selected regions of code ([Ref](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L343-L356)); unless I'm misreading things. Wouldn't it be a fairly similar implementation to that?

https://github.com/jonlabelle/SublimeJsPrettier/blob/778cda45c212f28054cad3c4aa01002c5a646e4f/JsPrettier.py#L343-L356

That code seems to be getting references to the selected text, for each of them, extracting the substring of selected text as `source_text`, and then passing it into `self.format_code`:

- https://www.sublimetext.com/docs/api_reference.html#sublime.View
  - https://www.sublimetext.com/docs/api_reference.html#sublime.View.sel
    - > The view's `Selection`
      - https://www.sublimetext.com/docs/api_reference.html#sublime.Selection
  - https://www.sublimetext.com/docs/api_reference.html#sublime.View.substr
    - > The string at the `Point` or within the `Region` provided.

Even formatting the entire file seems to be handled in the same sort of way, where a `Region` is created of the entire size of the view, the substring of all code in that region is extracted as `source_text`, and then passed to `self.format_code`:

https://github.com/jonlabelle/SublimeJsPrettier/blob/778cda45c212f28054cad3c4aa01002c5a646e4f/JsPrettier.py#L278-L287

Within `format_code` ([Ref](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L379-L452)), the `source` is seemingly just piped into `prettier` on `STDIN`, so there should be no reason it needs to be using a saved file:

https://github.com/jonlabelle/SublimeJsPrettier/blob/778cda45c212f28054cad3c4aa01002c5a646e4f/JsPrettier.py#L408-L424

- https://docs.python.org/3/library/subprocess.html#subprocess.Popen
  - > Execute a child program in a new process.
- https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate
  - > Interact with process: Send data to `stdin`. Read data from `stdout` and `stderr`, until end-of-file is reached. Wait for process to terminate and set the `returncode` attribute. The optional `input` argument should be data to be sent to the child process, or `None`, if no data should be sent to the child.

If there is something I'm missing here please let me know, but from my quick skim/theorising through the codebase, it looks like the current architecture of the plugin would make implementing this on unsaved file buffers fairly trivial, as pretty much all of the 'required pieces' for it seem to already be in place?

**Comment by 0xdevalias** [comment]
Quickly hacked together my own version of it, which is more or less using the same methods your plugin (and my original example code) did, and it seems to work fine. Obviously doesn't have quite as robust config/error checking/etc though.

- https://github.com/0xdevalias/dotfiles/commit/5d04bf3a49f40daae4eca56467854245bfb51c64
  - https://github.com/0xdevalias/dotfiles/blob/devalias/sublimetext/SublimeSettings/PrettierFormat.py
  - https://github.com/0xdevalias/dotfiles/blob/devalias/sublimetext/SublimeSettings/PrettierFormat.sublime-settings
  - https://github.com/0xdevalias/dotfiles/blob/devalias/sublimetext/SublimeSettings/PrettierFormat.sublime-commands
