### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by snsnsjsn** [jonlabelle/SublimeJsPrettier#270]
When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [ ] **Explain the Issue and Expected Behavior**
- [ ] **Prettier version**
- [ ] **JsPrettier Plug-in Version**
-## 1.61.0
sublime Build 4143
- [ ] **Platform Details**
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0

Prettier process finished with exit code 1.
- [ ] **Generated Prettier command line arguments**
- [ ] **Is the same behavior observed when run against Prettier directly?**
- [ ] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [ ] **Steps to reproduce the behavior**

---

## Explain the Issue and Expected Behavior

Provide a story of the issue with as much detail as possible, including the expected behavior.

## Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    <PRETTIER_VERSION>

## JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "<JS_PRETTIER_PLUGIN_VERSION>",
    ...

## Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: <SUBLIME_TEXT_VERSION>
    - Sublime Text Build: <SUBLIME_TEXT_BUILD>
    - Sublime Text Architecture: <SUBLIME_TEXT_ARCHITECTURE>
    - Operating System Name: <OS_NAME>
    - Operating System Version: <OS_VERSION>
    - Operating System Architecture: <OS_ARCHITECTURE>

## Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

**Example**

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command
    -----------------------------------------

    /usr/local/bin/prettier                 \
        --no-config                         \
        --print-width 80                    \
        --tab-width 2                       \
        --single-quote false                \
        --trailing-comma es5                \
        --bracket-spacing true              \
        --bracket-same-line false           \
        --jsx-single-quote false            \
        --parser babel                      \
        --semi true                         \
        --require-pragma false              \
        --prose-wrap preserve               \
        --arrow-parens always               \
        --html-whitespace-sensitivity css   \
        --quote-props as-needed             \
        --vue-indent-script-and-style false \
        --embedded-language-formatting auto \
        --use-tabs false                    \
        --editorconfig true                 \
        --single-attribute-per-line false   \
        --stdin-filepath messy.js           \
        --loglevel debug

    Prettier reported the following output:

    [debug] normalized argv: {"_":[],"bracket-spacing":true,"color":true",...}
    [debug] '--no-config' option found, skip loading config file.
    [debug] applied config-precedence (cli-override): {"filepath":"messy.js",...}

> **NOTE:** The back-slashes (`\`) in the example above will not be printed to the Console... and only provided here for legibility purposes. The full prettier command will be output to the Console with no line-breaks.

## Is the same behavior observed when run against Prettier directly?

For example, the following command passes the contents of `messy.js` to Prettier and prints the formatted to stdout:

    /usr/local/bin/prettier                 \
        --no-config                         \
        --print-width 80                    \
        --tab-width 2                       \
        --single-quote false                \
        --trailing-comma es5                \
        --bracket-spacing true              \
        --bracket-same-line false           \
        --jsx-single-quote false            \
        --parser babel                      \
        --semi true                         \
        --require-pragma false              \
        --prose-wrap preserve               \
        --arrow-parens always               \
        --html-whitespace-sensitivity css   \
        --quote-props as-needed             \
        --vue-indent-script-and-style false \
        --embedded-language-formatting auto \
        --use-tabs false                    \
        --editorconfig true                 \
        --single-attribute-per-line false   \
        --stdin-filepath messy.js           \
        --loglevel debug                    \
        < messy.js

## The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, excluding the comments.

**Example JsPrettier.sublime-settings**

    {
        "debug": false,
        "prettier_cli_path": "",
        "node_path": "",
        "auto_format_on_save": false,
        "auto_format_on_save_excludes": [],
        "auto_format_on_save_requires_prettier_config": false,
        "allow_inline_formatting": false,
        "custom_file_extensions": [],
        "max_file_size_limit": -1,
        "disable_tab_width_auto_detection": false,
        "disable_prettier_cursor_offset": false,
        "additional_cli_args": {},
        "prettier_options": {
            "printWidth": 80,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "es5",
            "bracketSpacing": true,
            "bracketSameLine": false,
            "jsxSingleQuote": false,
            "parser": "babel",
            "semi": true,
            "requirePragma": false,
            "proseWrap": "preserve",
            "arrowParens": "always",
            "htmlWhitespaceSensitivity": "css",
            "quoteProps": "as-needed",
            "vueIndentScriptAndStyle": false,
            "embeddedLanguageFormatting": "auto",
            "editorconfig": true,
            "singleAttributePerLine": false
        }
    }

## The contents of your `<project_name>.sublime-project` file (if applicable)

The entire contents of your ***User*** overridden JsPretter Project-level Settings, excluding the comments.

**Example**

    {
        "folders": [
            {
                "path": "."
            }
        ],
        "settings": {
            "js_prettier": {
                "debug": false,
                "prettier_cli_path": "",
                "node_path": "",
                "auto_format_on_save": false,
                "auto_format_on_save_excludes": [],
                "auto_format_on_save_requires_prettier_config": false,
                "allow_inline_formatting": false,
                "custom_file_extensions": [],
                "max_file_size_limit": -1,
                "disable_tab_width_auto_detection": false,
                "disable_prettier_cursor_offset": false,
                "additional_cli_args": {},
                "prettier_options": {
                    "printWidth": 80,
                    "tabWidth": 2,
                    "singleQuote": false,
                    "trailingComma": "es5",
                    "bracketSpacing": true,
                    "bracketSameLine": false,
                    "jsxSingleQuote": false,
                    "parser": "babel",
                    "semi": true,
                    "requirePragma": false,
                    "proseWrap": "preserve",
                    "arrowParens": "always",
                    "htmlWhitespaceSensitivity": "css",
                    "quoteProps": "as-needed",
                    "vueIndentScriptAndStyle": false,
                    "embeddedLanguageFormatting": "auto",
                    "editorconfig": true,
                    "singleAttributePerLine": false
                }
            }
        }
    }

## Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. This is the first step
    2. This is the second step
    3. Further steps, etc.

    Any other information you want to share that is relevant to the issue being
    reported. This might include the lines of code that you have identified as
    causing the bug, and potential solutions (and your opinions on their
    merits).

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

PS C:\Users\DELL> node -v
v18.16.0
PS C:\Users\DELL> npm -v
9.5.1

I have ctrl +shift+p to run 
![Uploading image.png…]()

nothing happened , and console print the error
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.16.0

Prettier process finished with exit code 1.

**Comment by jonlabelle** [comment]
@snsnsjsn: sounds like you need to troubleshoot your prettier installation. Can you run prettier from the command-line?

**Comment by jonlabelle** [comment]
Hi @snsnsjsn. What happens when you try and format the same code in the [Prettier Playground](https://prettier.io/playground/)?

**Comment by snsnsjsn** [comment]
> Hi @snsnsjsn. What happens when you try and format the same code in the [Prettier Playground](https://prettier.io/playground/)?

hi，,this is what I want , but I could not execute it by sublime

**Comment by jgburet** [comment]
Hey, same here since some time.

MacOS 13.4.1
SublimeText 4150
SublimeJsPrettier 1.63.1
node 16.10.0
prettier 2.7.1
pnpm 7.18.2

`pnpm prettier --config ./.prettierrc.yaml src` works in zsh

error in ST console:
```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

/Users/jgburet/Development/xxx/backend/node_modules/.bin/prettier:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

Playground works just fine with:
```js
export async function* streamPages(
    session,
    query,
){
    for (let nextPage = query; nextPage;) {
        yield 1;
        await sleep(1)
    }
}
```

`.prettierrc.yaml`:
```
semi: true
trailingComma: all
singleQuote: true
printWidth: 100
tabWidth: 4
useTabs: false
```
