### ISSUE TITLE
Add Support For ESLinter Configurations

### ISSUE THREAD

**Issue by loganknecht** [jonlabelle/SublimeJsPrettier#272]
**Is your feature request related to a problem? Please describe.**

I am working across multiple teams who are using files like `.eslintrc.json` to house their prettier configurations.
Which looks something like this
```json
{
  "extends": ["prettier"],
  // ...
  "rules": {
    // ...
    "prettier/prettier": [
      "warn",
      {
        "semi": true,
        "singleQuote": false,
        "trailingComma": "none",
        "arrowParens": "always",
        "printWidth": 110
      }
    ]
  },
  // ...
}
```

**Describe the solution you'd like**

I would like `SublimeJsPrettier` to also check `eslint` configuration files for settings as well.

**Describe alternatives you've considered**

In #169 someone stated that a solution was to use the `prettier_cli_path` to specify the executable that should run, but that is not sufficient as I am working across multiple repos, with different eslint version and if I install one it does not guarantee that it will work for all.

I would like `prettier` to be able to be configured on a project by project basis.

**Additional context**

N/A

**Comment by jonlabelle** [comment]
Hi @loganknecht. Please use the [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L265) setting to specify a common path for your eslint configuration. You'll see examples in the comments.
