### ISSUE TITLE
Support not passing any Prettier config CLI options even when *not* using a Prettier config file

### ISSUE THREAD

**Issue by MarkAmeryCurative** [jonlabelle/SublimeJsPrettier#274]
This is more or less a duplicate of https://github.com/jonlabelle/SublimeJsPrettier/issues/259, but I want to flesh out the problem a bit and explain why the proposed workaround there isn't adequate.

Prettier is, by its own lights, [_"An opinionated code formatter"_](https://prettier.io/). Part of it being opinionated is that you can run it with no config whatsoever, and doing so is totally reasonable. At my workplace, that's how they've got Prettier set up: they have CI steps and pre-commit hooks that run Prettier on all our code _with no config_, simply using the default settings for whatever Prettier version we've got specified in our `package.json` with no `.prettierrc`.

This Sublime plugin does not easily support using Prettier this way. The project I'm working on currently uses an old (pre-3.0) version of Prettier, which means its `trailingComma` config value defaults to `es5` instead of `all`. But this plugin, instead of simply deferring to the default config options of the Prettier executable being invoked, passes its _own_ default config options which - [as of a couple of weeks ago](https://github.com/jonlabelle/SublimeJsPrettier/commit/39d3450933d7633f4098bce0c9827a3e4962a8ad) - include setting `trailingComma` to `all`. So an update to this plugin happened and instead of stuff just magically working like it used to I had to dig into how the config works and the release history of the plugin and figure out that I need to be overriding the `trailingComma` explicitly in my config for this plugin - even though all I really want is for it to call Prettier without any config options!

To be honest, I think the nicest fix would actually be to not set any `prettier_options` by default. The plugin's default config file could still contain all the documentation is does currently, but either set every value in `prettier_options` to `null` or just have commented out examples of setting them or something like that. I think having any options at all be baked into the `prettier_options` object in the plugin's default settings file is an antipattern that will cause the same kind of problem I experienced any time that a new Prettier release changes one of Prettier's defaults.

But failing that, it'd be nice if there were a setting I could use to explicitly opt out of using `prettier_options`, or at least opt out of using the `prettier_options` from the _default_ package settings. What do you think?

**Comment by jonlabelle** [comment]
Hi @MarkAmeryCurative. As mentioned in #259, just set...

```
"additional_cli_args": {
  "--config-precedence": "file-override"
}
```

**Comment by MarkAmeryCurative** [comment]
@jonlabelle that doesn't negate the effect of passing the CLI flags; it simply means that *if* there is a config file and *if* that config file sets values for the same config variables that are being passed by CLI flags, then the values in the config file will take precedence. But we don't have a config file in our project, and I don't want to add one and fill it with settings that are just repeating Prettier's defaults just for the sake of the minority of devs on my team who use Sublime.
