### ISSUE TITLE
Crash when low on memory

### ISSUE THREAD

**Issue by alecmev** [jonlabelle/SublimeJsPrettier#275]
## Explain the Issue and Expected Behavior

Sublime Text outright crashes when formatting on-save when low on memory. Not the very first time, but after maybe 5-10 invocations, so also looks like there could be a memory leak somewhere. Disabling JsPrettier fixes the problem. LSP-eslint, for example, doesn't suffer from this, despite also having auto-fix enabled. `disable_prettier_cursor_offset` doesn't help. This has been happening for some months now, just didn't have time to narrow it down before.

## Prettier version

3.0.3

## JsPrettier Plug-in Version

1.63.1

## Platform Details

    - Sublime Text Build: 4156
    - Architecture: x64
    - Operating System Name: Arch

## Generated Prettier command line arguments

    prettier --config .prettierrc.yaml --parser typescript --use-tabs false --ignore-path .prettierignore --stdin-filepath foo.tsx --loglevel debug

Prettier reported the following output:

    The command is broken, it needs to be --log-level, but I ran it myself and there was nothing out of ordinary.

## Is the same behavior observed when run against Prettier directly?

No, it never crashes, run back-to-back.

## The contents of your `User/JsPrettier.sublime-settings` file

```json
{
  "auto_format_on_save": true,
  "auto_format_on_save_requires_prettier_config": true,
  "disable_tab_width_auto_detection": true,
  "custom_file_extensions": ["xml", "svg"],
  "disable_prettier_cursor_offset": true,
  "debug": true
}
```

## Steps to reproduce the behavior

Well, this is hard. I did it by just opening a million tabs of Google Maps, but I'm sure there's a saner way. Basically, my hope for this issue is guided troubleshooting, or at least some hints.

**Comment by jonlabelle** [comment]
How much memory are we talking about here?
