### ISSUE TITLE
JsPrettier cannot find plugin

### ISSUE THREAD

**Issue by jakubmazanec** [jonlabelle/SublimeJsPrettier#276]
I have repo with this (simplified) structure:

```
foobar/
  api/
  ui/
    node_modules/
      prettier/
      prettier-plugin-packagejson/
    src/
    prettier.config.js
```

When saving files in `foobar/ui/src`, JsPrettier fails with this error: `Error: Cannot find package 'prettier-plugin-packagejson' imported from foobar\noop.js`. It is obvious why the plugin can't be found: it is located in `foobar/ui/node_modules/prettier-plugin-packagejson`, where Node resolution algorithm starting from `foobar/noop.js` is unable to reach. I don't know where `noop.js` comes from, but it should be in `foobar/ui`.

**Comment by jonlabelle** [comment]
*node_modules/prettier-plugin-packagejson* isn't a known directory that's searched for. I'm not sure how to help.

**Comment by jakubmazanec** [comment]
I'm sorry, I'm not sure what you mean by `node_modules/prettier-plugin-packagejson isn't a known directory that's searched for`. 

Anyway, maybe what would clear things up is this: what is that `noop.js` file JsPrettier mentions in the error? It doesn't exist in the file system, so I assume it is somehow created on the fly by JsPrettier? If that file was in the correct location, then importing `prettier-plugin-packagejson` would work.

**Comment by jonlabelle** [comment]
[prettier-plugin-packagejson](https://www.npmjs.com/package/prettier-plugin-packagejson#prettier-plugin-packagejson) isn't something that's supported by the plugin.

**Comment by jakubmazanec** [comment]
Why not? And what about other Prettier plugins? If Prettier, running from `foobar/ui` as working directory, can correctly find plugins (as they are specified in `prettier.config.js`), I would assume SublimeJsPrettier should handle it as well.
