### ISSUE TITLE
Switch to `--log-level` Prettier CLI option name is needed

### ISSUE THREAD

**Issue by jakubmazanec** [jonlabelle/SublimeJsPrettier#277]
In Prettier v3, `--loglevel` CLI option was changed to `--log-level`: https://github.com/prettier/prettier/pull/13204. But the old name is actually being used for all Prettier versions: https://github.com/jonlabelle/SublimeJsPrettier/blob/5a4e4c12a8ead90ab250703afc1ef3867ca40f03/JsPrettier.py#L633C9-L633C9

**Comment by jonlabelle** [comment]
Thanks for the tip @jakubmazanec. [Update applied](https://github.com/jonlabelle/SublimeJsPrettier/commit/988c766903e134401143410278ecc41da042a219).
