### ISSUE TITLE
Prettier cannot find plugin

### ISSUE THREAD

**Issue by jakubmazanec** [jonlabelle/SublimeJsPrettier#278]
## Explain the Issue and Expected Behavior

Clone repository https://github.com/jakubmazanec/SublimeJsPrettier-bug, open file `subfolder/src/main.ts` and try to format it using SublimeJsPrettier. It unexpectedly fails with a Prettier error. My guess is it's because SublimeJsPrettier runs Prettier with working directory being the location of the Sublime project (`/SublimeJsPrettier-bug`), not location of the Prettier config file (`/SublimeJsPrettier-bug /subfolder`).

## Prettier version

3.0.3

## JsPrettier Plug-in Version

1.63.1

## Platform Details

    - Sublime Text Version: 4
    - Sublime Text Build: 4152
    - Operating System Name: Windows 11 Pro
    - Operating System Version: <22H2>

## Generated Prettier command line arguments

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

D:\projects\SublimeJsPrettier-bug\subfolder\node_modules\.bin\prettier --config D:\projects\SublimeJsPrettier-bug\subfolder\prettier.config.js --parser typescript --use-tabs false --stdin-filepath D:\projects\SublimeJsPrettier-bug\subfolder\src\main.ts --log-level debug --cursor-offset 26

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

[debug] normalized argv: {"":[],"cache":false,"color":true,"editorconfig":true,"useTabs":false,"config":"D:\\projects\\SublimeJsPrettier-bug\\subfolder\\prettier.config.js","parser":"typescript","filepath":"D:\\projects\\SublimeJsPrettier-bug\\subfolder\\src\\main.ts","logLevel":"debug","cursorOffset":26,"configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":[],"__raw":{"_":[],"cache":false,"color":true,"editorconfig":true,"use-tabs":false,"config":"D:\\projects\\SublimeJsPrettier-bug\\subfolder\\prettier.config.js","parser":"typescript","stdin-filepath":"D:\\projects\\SublimeJsPrettier-bug\\subfolder\\src\\main.ts","log-level":"debug","cursor-offset":"26","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] load config file from 'D:\projects\SublimeJsPrettier-bug\subfolder\prettier.config.js'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"endOfLine":"lf","arrowParens":"always","bracketSameLine":false,"bracketSpacing":false,"embeddedLanguageFormatting":"auto","htmlWhitespaceSensitivity":"css","jsxSingleQuote":false,"printWidth":100,"proseWrap":"always","quoteProps":"as-needed","requirePragma":false,"semi":true,"singleQuote":true,"trailingComma":"all","plugins":["prettier-plugin-packagejson"]}`
[error] D:\projects\SublimeJsPrettier-bug\subfolder\src\main.ts: Error: Cannot find package 'prettier-plugin-packagejson' imported from D:\projects\SublimeJsPrettier-bug\noop.js
[error]     at new NodeError (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:18797:5)
[error]     at packageResolve (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19743:9)
[error]     at moduleResolve (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19775:20)
[error]     at defaultResolve (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19880:15)
[error]     at resolve (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19898:12)
[error]     at importFromFile (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:19913:15)
[error]     at importFromDirectory (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20182:10)
[error]     at file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20199:12
[error]     at async loadPlugin (file:///D:/projects/SublimeJsPrettier-bug/subfolder/node_modules/prettier/index.mjs:20204:28)
[error]     at async Promise.all (index 0)


Prettier process finished with exit code 2.
```

## Is the same behavior observed when run against Prettier directly?

When running `npx prettier src/main.ts` from directory `subfolder`, it works.

## The contents of your `User/JsPrettier.sublime-settings` file

```
{
  "debug": true,
  "auto_format_on_save": true,
  "auto_format_on_save_excludes": ["*/node_modules/*"],
  "auto_format_on_save_requires_prettier_config": true,
  "disable_tab_width_auto_detection": true,
  "prettier_options": {
    "printWidth": 120,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": false,
    "jsxBracketSameLine": false,
    "semi": true,
    "requirePragma": false,
    "proseWrap": "preserve",
    "arrowParens": "always",
    "htmlWhitespaceSensitivity": "css",
    "quoteProps": "as-needed",
  }
}
```

**Comment by jonlabelle** [comment]
I'm not really sure the purpose/usefulness of this [package](https://www.npmjs.com/package/prettier-plugin-packagejson), but it's definitely the culprit. Everything formatted perfectly once it was removed it.

1. `npm uninstall prettier-plugin-packagejson --save-dev`
2. Remove [line#15](https://github.com/jakubmazanec/SublimeJsPrettier-bug/blob/main/subfolder/prettier.config.js#L15)

**Comment by jakubmazanec** [comment]
It's a standard Prettier plugin for consistently formatting package.json files. I don't want to remove it. Also, there other useful Pretiter plugins I **need** to use in some projects, e.g. https://github.com/tailwindlabs/prettier-plugin-tailwindcss. Please fix SublimeJsPrettier, as Prettier itself works just fine with this setup.

**Comment by jonlabelle** [comment]
SublimeJsPrettier does work already w/ *most* plugins, [see here](https://github.com/jonlabelle/SublimeJsPrettier/issues/239)

**Comment by jakubmazanec** [comment]
It isn't in an awkward place, it represents an actual situation that can arise: you can use Sublime Text as editor for JavaScript and also for non-JavaScript apps (e.g. API service written in C# ) that don't use Prettier - this isn't some virtual issue, it is a real problem I'm currently experiencing that costs me time, because I have to constantly turn plugins on and off, or run Prettier manually.

The issue you linked is sadly useless for me - I cannot change my project setup. AFAIK there is no reason not to use `prettier.config.js`'s directory as working directory, because of how Prettier works - the config is always in the root of directory _tree the user wants formatted_, and  if the `prettier.config.js` isn't in the root of _Sublime project_, it means the user doesn't actually use it for some parts of it.

Or alternatively what should be done: use, as the working directory, the parent directory of a `node_modules` folder that contains `prettier_cli_path`, because that is the only way Prettier can then find plugins. IMO this would be universal solution.

At least there could be some config option, because currently I have perfectly normal project setup that SublimeJsPrettier can't handle.

**Comment by jakubmazanec** [comment]
My attempt at the second solution is here: #280.
