### ISSUE TITLE
[Question] I could not format css, json...

### ISSUE THREAD

**Issue by zhouxinghong** [jonlabelle/SublimeJsPrettier#281]
If you're not exactly sure what to say, here are some suggestions: <https://stackoverflow.com/help/how-to-ask>

Hello!
After I installed the extension, I could not format css, json, markdown and other file contents in Sublime Text.
What is the reason for this?
Windows 10 x64 19044
1.65.1
Sublime Text 4152 x64

**Comment by zhouxinghong** [comment]
![image](https://github.com/jonlabelle/SublimeJsPrettier/assets/54253524/896aa11e-d908-433f-becc-57259d45b602)

**Comment by zhouxinghong** [comment]
I followed the default settings without any personal settings...

**Comment by jonlabelle** [comment]
Hi @zhouxinghong. Did you [install Prettier](https://github.com/jonlabelle/SublimeJsPrettier#install-prettier)? Can you provide any errors written to the SublimeText console?

**Comment by jonlabelle** [comment]
Prettier is a [NodeJS package](https://www.npmjs.com/package/prettier).

1. [Download](https://nodejs.org/en/download) and install NodeJS.
2. Then you can install Prettier from the command line, type: `npm install -g prettier`

**Comment by zhouxinghong** [comment]
I understand what you said. Thank you very much, teacher! 👍😜🎉
