### ISSUE TITLE
JsPrettier doesn't run in appropriate context when used in monorepo context

### ISSUE THREAD

**Issue by pdamoc** [jonlabelle/SublimeJsPrettier#282]
### Context: 

Complex monorepo with the following structure 

```
/root
    /libs
    /apps
        /app1
            /packages 
                /pkg1
                ...
```

Some of the apps are implemented using `Svelte` and some of the apps have a workspace structure with some of the packages using `Svelte`. 

The SublimeText has the `root` added to the project and various internal folders. 

When attempting to format the file, JsPrettier sometimes executes in the wrong context. This results in errors related to finding the appropriate plugins (in my case `prettier-plugin-svelte`). 

### Solution

I created a small function that finds the first ancestor of the file that has a `package.json` and uses that as the `CWD` for prettier. I then use `find_root` instead of `get_st_project_path` in [run](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L227).

```
from pathlib import Path
def find_root(source_file_path):
    for p in Path(source_file_path).parents:
        if "package.json" in os.listdir(p):
            return p

    return None
```

I switched to the provided `python 3.8` on my local version in order to have access to `pathlib`but I guess a backwards compatible version can be created for ST2. 

ST: 4169
JsPrettier: 1.65.4
MacOS: 14.4.1 (23E224)

**Comment by jonlabelle** [comment]
Hi @pdamoc. Can you provide a version of your code that is compatible w/ Python 2 (e.g. without pathlib)?

Go ahead an make a pull request for your changes so I can take a look.
