### ISSUE TITLE
Support ESM config files

### ISSUE THREAD

**Issue by mrcsmcln** [jonlabelle/SublimeJsPrettier#284]
**Is your feature request related to a problem? Please describe.**

SublimeJsPrettier does not automatically discover ESM config files. This means that when `auto_format_on_save_requires_prettier_config` is set to `true`, files do not automatically format.

As of Prettier 3.0, ESM config files are supported (see [here](https://prettier.io/docs/en/configuration), [here](https://prettier.io/blog/2023/07/05/3.0.0.html#support-config-files-in-esm-13130httpsgithubcomprettierprettierpull13130-by-fiskerhttpsgithubcomfisker), and [here](https://github.com/prettier/prettier/pull/13130)).

**Describe the solution you'd like**

I would like SublimeJsPrettier to support ESM config files out of the box. I see a list of candidate config files at [jsprettier/const.py:28](https://github.com/jonlabelle/SublimeJsPrettier/blob/39d3450933d7633f4098bce0c9827a3e4962a8ad/jsprettier/const.py#L28). I suspect two simple additions, `'prettier.config.mjs'` and `'.prettierrc.mjs'` would do the trick.

Tangentially, I also noticed the files are not listed in the same order they are loaded by Prettier (see [here](https://prettier.io/docs/en/configuration) and [here](https://github.com/cosmiconfig/cosmiconfig/blob/main/README.md#cosmiconfig)). I'm not sure if this makes a difference, but I thought it might be helpful to point out.

If you'd like, I can make a pull request with these changes. The only reason I didn't make one is because I wasn't sure if the alternate loading strategy would cause any errors elsewhere.

**Describe alternatives you've considered**

A current workaround is to specify the config file as a CLI arg:

```json
{
    "additional_cli_args": {
        "--config": "./prettier.config.mjs"
    }
}
```

This is not ideal because config file names are not always the same between projects.

**Additional context**

I have no additional context to provide.

**Comment by jonlabelle** [comment]
[All set](https://github.com/jonlabelle/SublimeJsPrettier/commit/209f85ee5c390cf38717ef07b961b8b1bc86dadb). Thanks @mrcsmcln!
