### ISSUE TITLE
Doesn't work when folder names use parentheses (Next.js route groups)

### ISSUE THREAD

**Issue by JGJP** [jonlabelle/SublimeJsPrettier#285]
## Explain the Issue and Expected Behavior

Next.js [route groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) require that some folders be named with parentheses like `(foldername)`. JsPrettier does not run in any files that are direct or indirect children of these folders.

## Prettier version

3.2.5

## JsPrettier Plug-in Version

1.66.0

## Platform Details

ST4: 4169
Platform: Windows 11

## Generated Prettier command line arguments

```bash
prettier --config C:\Users\username\project\prettier.config.js --parser typescript --use-tabs true --ignore-path C:\Users\username\project\.prettierignore --stdin-filepath C:\Users\username\project\src\app\(front)\page.tsx --log-level debug --cursor-offset 7839
```

## Is the same behavior observed when run against Prettier directly?

Running prettier directly works fine

**Comment by jonlabelle** [comment]
Hi @JGJP. Can you post the error you are receiving when attempting to format a file a with parenthesis in its path?

**Comment by JGJP** [comment]
@jonlabelle sorry I should have included it initially, the error looks like this:

```
------------------
 JsPrettier ERROR 
------------------

Prettier produced the following output:

\page.tsx was unexpected at this time.
```

I think it's treating the parentheses as symbols for string substitution, trying to run the contents as a command. Potentially quite dangerous.

**Comment by JGJP** [comment]
If you surround the path in double quotes it should resolve the issue, depending on shell?

**Comment by jonlabelle** [comment]
@JGJP: I can't seem to reproduce. I tried on both macOS and Windows and both attempts completed with exit code 0 (see below).

#### Windows

```
C:\Users\jlabelle25\AppData\Roaming\npm\prettier.cmd --no-config --print-width 80 --tab-width 4 --single-quote false --trailing-comma none --bracket-spacing true --bracket-same-line false --parser babel --semi true --require-pragma false --prose-wrap preserve --arrow-parens avoid --html-whitespace-sensitivity css --quote-props as-needed --vue-indent-script-and-style false --embedded-language-formatting auto --jsx-single-quote false --single-attribute-per-line false --use-tabs true --stdin-filepath C:\Users\jlabelle25\Desktop\test\(folder)\test.js --log-level debug

Prettier process finished with exit code 0.
```

#### macOS

```
/Users/jon/.nvm/versions/node/v20.12.0/bin/prettier --config /Users/jon/tmp/jsprettier-285/.prettierrc --parser markdown --use-tabs false --stdin-filepath /Users/jon/tmp/jsprettier-285/(folder)/auth.md --log-level debug --config-precedence file-override

Prettier process finished with exit code 0.
```

**Comment by JGJP** [comment]
@jonlabelle 
I think the issue might be caused by it using my default shell fish, which uses plain brackets for substitution. It seems to me that surrounding the path in double quotes would resolve the issue and not cause issues for other shells?

**Comment by jonlabelle** [comment]
@JGJP: Try replacing [line #639](https://github.com/jonlabelle/SublimeJsPrettier/blob/a0c07d61f0617094028876986ae44920a3630c4c/JsPrettier.py#L639), with the following line:

```python
prettier_options.append('"' + source_file_path + '"')
```

See if that makes any difference.

Also, the value for `--stdin-filepath` is only used for sniffing the file extension. We can probably get rid of the path prefix all together. e.g.:

```python
>>> source_file_path = 'C:\(folder)\inner folder\test.js'
>>> filename = os.path.split(source_file_path)[1] # strip the path prefix
test.js

# Prettier just needs the filename for sniffing
prettier_options.append('--stdin-filepath')
prettier_options.append(filename)
```

**Comment by JGJP** [comment]
@jonlabelle 
Thanks for this, after using the cloned repo locally and making the change I can confirm it's working
