### ISSUE TITLE
Make it possible to use relative paths in `prettier_cli_path`

### ISSUE THREAD

**Issue by hoest** [jonlabelle/SublimeJsPrettier#29]
In JavaScript projects with `prettier` as dev-dependency (`package.json`) inside the `node_modules` folder of the project, it would be great to use this version of `prettier`.

Something like this in a `*.sublime-project` file:

```json
{
  "folders": [{ "path": "." }],
  "settings" : {
    "js_prettier": {
      "auto_format_on_save": true,
      "prettier_cli_path": "./node_modules/.bin/prettier"
    }
}
```

Or maybe its possible to automatically find the first `node_modules` folder inside a project and use that `prettier`, otherwise use the globally installed version of `prettier`.

**Comment by jonlabelle** [comment]
Now available since [v1.6.21](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.6.21).
