### ISSUE TITLE
[error] Invalid configuration file: ENOENT: no such file or directory ...

### ISSUE THREAD

**Issue by DavidHe1127** [jonlabelle/SublimeJsPrettier#291]
## Error

```
------------------
 JsPrettier ERROR 
------------------

Prettier produced the following output:

[error] Invalid configuration file: ENOENT: no such file or directory, scandir '/xxx/xyz'


Prettier process finished with exit code 2.
```

## Investigation

Seems it doesn't see my `.prettierrc` below as valid. It works after removing it from project root.

```
{
  "printWidth": 120,
  "singleQuote": true,
  "trailingComma": "es5",
  "tabWidth": 2
}
```

For now have to revert to `1.66.0` so it works again.

**Comment by jonlabelle** [comment]
Hi @DavidHe1127. Can you attach a minimal project required to reproduce?

Please attach it in zip format, and do not include your `node_modules` directory.

**Comment by DavidHe1127** [comment]
@jonlabelle Thanks for getting back swiftly. I can confirm after upgrading prettier cli to `3.2.5` the latest, the error is gone
