### ISSUE TITLE
[Bug] SublimeJsPrettier Doesn't Work with `prettier-plugin-astro`

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [jonlabelle/SublimeJsPrettier#296]
### Explain the issue

I recently discovered that this package doesn't seem to work with `prettier-plugin-astro`: https://github.com/withastro/prettier-plugin-astro

```
------------------
 JsPrettier ERROR 
------------------

Prettier produced the following output:

[error] /home/michael/Development/website/src/pages/work.astro: TypeError: Cannot read properties of undefined (reading 'start')
[error]     at locStart (file:///home/michael/Development/website/node_modules/prettier-plugin-astro/dist/index.js:808:43)
[error]     at nodeContainsCursor (file:///home/michael/Development/website/node_modules/prettier/index.mjs:20939:40)
[error]     at isMatchedNode (file:///home/michael/Development/website/node_modules/prettier/index.mjs:19512:64)
[error]     at getChildren (file:///home/michael/Development/website/node_modules/prettier/index.mjs:19521:16)
[error]     at getChildren.next (<anonymous>)
[error]     at getDescendants (file:///home/michael/Development/website/node_modules/prettier/index.mjs:19530:16)
[error]     at getDescendants.next (<anonymous>)
[error]     at getCursorNode (file:///home/michael/Development/website/node_modules/prettier/index.mjs:20941:14)
[error]     at coreFormat (file:///home/michael/Development/website/node_modules/prettier/index.mjs:21216:23)
[error]     at async formatWithCursor (file:///home/michael/Development/website/node_modules/prettier/index.mjs:21416:14)


Prettier process finished with exit code 2.
```

### Prettier version

3.3.2

### JsPrettier plug-in version

1.68.1

### Platform

Linux

### SublimeText version

4

### Prettier config

```json
{
  "plugins": ["prettier-plugin-astro"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ],
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "arrowParens": "always",
  "endOfLine": "auto"
}
```

### Steps to reproduce

1. Install `prettier-plugin-astro`.
2. Create new Astro project.
3. Try to format an Astro file.

### Reproducible outside of SublimeText?

No

**Comment by jonlabelle** [comment]
Hi @FoggyMtnDrifter. So it worked for me after I added a [custom file extension](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L171) for `astro`.

> Minimal project: [astro-working-example.zip](https://github.com/user-attachments/files/15878520/jsprettier-296-astro.zip)

**Comment by FoggyMtnDrifter** [comment]
Here's my custom JSPrettier config:

```json
{
	"auto_format_on_save": true,
	"auto_format_on_save_requires_prettier_config": true,
	"custom_file_extensions": ["astro"],
}
```

**Comment by FoggyMtnDrifter** [comment]
Important to note, I was also able to reproduce the same error as before in your minimal project.

**Comment by FoggyMtnDrifter** [comment]
I've just discovered that the LSP package for Astro has its own formatter built-in which seems to work correctly, which means I won't need to rely on JSPrettier for these files. Thanks for checking on this anyways!

**Comment by privetkuku** [comment]
@jonlabelle, good day, sir!

I tried adding
