### ISSUE TITLE
[Question] How to use with svelte

### ISSUE THREAD

**Issue by KarChung-Konstant** [jonlabelle/SublimeJsPrettier#297]
### What's your question?

I have install the plugin by following https://github.com/sveltejs/prettier-plugin-svelte

1) npm i --save-dev prettier-plugin-svelte prettier
2) {
    "plugins": ["prettier-plugin-svelte"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}

But when I save, nothing happens for .svelte file

If I add `"custom_file_extensions": ["svelte"]`, it shows: `SyntaxError: Opening tag "a" not terminated. (93:17)`
But actually there is no problem:
```
<a
    href={`/dashboard/course/${course.id}`}
    class="w-full"
>
     {course.attributes.general_title}
</a>
```

**Comment by jonlabelle** [comment]
Hi @KarChung-Konstant.

Can you please open a new issue using the [Bug](https://github.com/jonlabelle/SublimeJsPrettier/issues/new?assignees=jonlabelle&labels=investigating&projects=&template=bug.yml&title=%5BBug%5D+) template?

Please following the instructions for each field in the template, so we can take a look.

Thanks
