### ISSUE TITLE
[Bug] Formatting is slow for Svelte

### ISSUE THREAD

**Issue by karchung0930** [jonlabelle/SublimeJsPrettier#298]
### Explain the issue

It took about 1-3 seconds to format the `.svelte` file. The plugin is https://github.com/sveltejs/prettier-plugin-svelte

### Prettier version

3.3.3

### JsPrettier plug-in version

3.2.6

### Platform

Windows

### SublimeText version

4

### Prettier config

```json
{
    "plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

### Steps to reproduce

1. Try to save the file
2. Sublime Text will be like stunning between 1 and 3 seconds

### Reproducible outside of SublimeText?

No

### Attach a minimal project

[jsprettier-and-svelte.zip](https://github.com/user-attachments/files/16817040/jsprettier-and-svelte.zip)

**Comment by jonlabelle** [comment]
I'm getting about 130ms to format your project, and on my Mac book pro (2019).

```console
$ prettier *.svelte --write
test.svelte 130ms (unchanged)
```

Try using a `.prettierignore` file to speed things up by ignoring misc files in your project. But all the plug-in is doing is running the prettier command and capturing its output. I'm open to suggestions on performance improvements (via pull requests), but there's not much else I can offer.
