### ISSUE TITLE
JsPrettier Error: Use of const in strict mode

### ISSUE THREAD

**Issue by LucaRosaldi** [jonlabelle/SublimeJsPrettier#3]
This is the error I get when I run the command:

```
/usr/local/lib/node_modules/prettier/bin/prettier.js:4
const fs = require("fs");
^^^^^
SyntaxError: Use of const in strict mode.
```

Any help?

**Comment by jonlabelle** [comment]
You may want to consider updating your installation of [node.js](https://nodejs.org/) to later version. Here's a [related discussion](http://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode) on the topic.

**Comment by jonlabelle** [comment]
I'm going to close the issue since it traces back to [prettier](https://github.com/jlongster/prettier), and not the Sublime Text plug-in/wrapper.
