### ISSUE TITLE
[Enhancement] Support for the "experimentalTernaries" option

### ISSUE THREAD

**Issue by chototoro** [jonlabelle/SublimeJsPrettier#300]
### Is your feature request related to a problem?

A year ago, Prettier released a new option called `experimentalTernaries`, allowing for a new formatting style of multiline ternaries (https://github.com/prettier/prettier/pull/13183). Currently, setting this option to `true` has no impact on the formatted files.

### Describe the solution you'd like

It would be great to see the `experimentalTernaries` option supported in JsPrettier.

**Comment by jonlabelle** [comment]
Hi @chototoro. You add this option to your [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L265) setting.

**Comment by chototoro** [comment]
@jonlabelle Oh yes! I didn't realize i could do it like that, thank you very much! 👍
