### ISSUE TITLE
[Bug] JsPrettier broken pipe in NextJs route group page file

### ISSUE THREAD

**Issue by JGJP** [jonlabelle/SublimeJsPrettier#301]
### Explain the issue

Next.js includes a convention for route groups as described here:
https://nextjs.org/docs/app/building-your-application/routing/route-groups

This creates files that can have a filepath that looks like:
`(marketing)/about/page.js `

These files do not get formatted properly by JsPrettier. When either formatting on save or manually formatting via command it won't work and will sometimes throw a "Broken pipe" error

![image](https://github.com/user-attachments/assets/3a815e69-7e4a-4433-a082-dd84c16542fe)

### Prettier version

3.2.5

### JsPrettier plug-in version

latest

### Platform

Windows

### SublimeText version

4

### Prettier command

```console
C:\Users\j\_dev\arga\dapp\node_modules\.bin\prettier --config C:\Users\j\_dev\arga\dapp\prettier.config.js --parser typescript --use-tabs true --ignore-path C:\Users\j\_dev\arga\dapp\.prettierignore --stdin-filepath C:\Users\j\_dev\arga\dapp\src\app\(app)\declarations\[id]\page.tsx --log-level debug --cursor-offset 1931
```

### Prettier config

```json
/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').PluginOptions} */
const config = {
	plugins: ['prettier-plugin-tailwindcss'],
	trailingComma: 'all',
	tabWidth: 3,
	semi: false,
	singleQuote: true,
	useTabs: true,
	printWidth: 120,
	arrowParens: 'avoid',
	jsxSingleQuote: true,
}

export default config
```

### Steps to reproduce

Create directory that has brackets such as `app/blog/[slug]/page.js `
Try to run JsPrettier to format the file

### Reproducible outside of SublimeText?

No

### Attach a minimal project

Will provide shortly

**Comment by JGJP** [comment]
Here's the reproduction, it's actually a route group issue, not a dynamic route issue:

https://github.com/JGJP/jsprettier-route-group-repro/blob/main/src/app/(group)/route/page.tsx

**Comment by jonlabelle** [comment]
Hi @JGJP. Can you very the fix for me?

## Install the fix branch

1. Uninstall the existing "JsPrettier" package, then close Sublime Text (all instances).

   Command Pallete -> Package Control: Remove Package -> "JsPrettier"

2. Navigate to your package path:

   ```bash
   cd C:\Users\<YourUsername>\AppData\Roaming\Sublime Text\Packages
   ```

   > If you still see a folder called "JsPretter", **delete it**.

3. Clone the fix/test branch:

   ```bash
   git clone --depth 1 --branch "develop/windows-no-shell-exec-v2" --single-branch "https://github.com/jonlabelle/SublimeJsPrettier.git" "JsPrettier"
   ```

4. Reopen Sublime Text and verify whether or not the problem still persists.

## Uninstall the fix branch

After you finished verifying, you can delete the above fix branch, and reinstall JsPrettier from [PackageControl](https://packagecontrol.io/packages/JsPrettier):

1. Again, uninstall the "JsPrettier" package, then close Sublime Text (all instances).

   Command Pallete -> Package Control: Remove Package -> JsPrettier

2. Navigate to your package path:

   ```bash
   cd C:\Users\<YourUsername>\AppData\Roaming\Sublime Text\Packages
   ```

   > If you still see a folder called "JsPretter", **delete it**.

3. Reinstall "JsPretter" from [PackageControl](https://packagecontrol.io/packages/JsPrettier):

   Command Pallete -> Package Control: Install Package -> "JsPrettier"

---

I will push the fix shortly after you verify the issue is resolved.

**Comment by JGJP** [comment]
@jonlabelle thanks for the fix. Unfortunately still a similar issue, the error is different though:

![image](https://github.com/user-attachments/assets/fae13a93-0dab-4687-8b65-3ff7bb124e5d)

**Comment by jonlabelle** [comment]
> @JGJP: thanks for the fix. Unfortunately still a similar issue, the error is different though.

Would you mind zipping up a minimal project (no `node_modules` please) so I can reproduce the behavior?

**Comment by JGJP** [comment]
@jonlabelle did you check this out? You should be able to reproduce with this:
https://github.com/jonlabelle/SublimeJsPrettier/issues/301#issuecomment-2435143001

**Comment by JGJP** [comment]
You know what it might be, you might need to set fish shell as your default shell. Fish does command substitution between `()`, not `$()` like bash

**Comment by JGJP** [comment]
I'm pretty sure that if you just wrap the path in single quotes it'll work. I actually tried to make this change myself but I'm not really good enough with Python

**Comment by jonlabelle** [comment]
@JGJP: can you test for me on [again](https://github.com/jonlabelle/SublimeJsPrettier/issues/301#issuecomment-2449681570), but use the `fix/quoting-in-windows-shells` branch this time.

**Comment by JGJP** [comment]
@jonlabelle sorry I tried it but the error is the same

<path after parentheses> was unexpected at this time

**Comment by jonlabelle** [comment]
> sorry I tried it but the error is the same
> 
> <path after parentheses> was unexpected at this time

@JGJP: I must be missing something somewhere. When you can, attach a minimal project that will allow me to reproduce the behavior.

**Comment by jonlabelle** [comment]
@JGJP: Can you confirm you're using the *new* fix branch ***[fix/quoting-in-windows-shells](https://github.com/jonlabelle/SublimeJsPrettier/tree/fix/quoting-in-windows-shells)*** to test the new changes?

I cannot reproduce the problem any longer using [your project](https://github.com/JGJP/jsprettier-route-group-repro).

#### Here's the output when I run on Windows now (exit code 0):

You'll notice `--stdin-filepath` is now quoted:

```plaintext
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

C:\tmp\jsprettier-route-group-repro\node_modules\.bin\prettier --config C:\tmp\jsprettier-route-group-repro\prettier.config.js --parser typescript --use-tabs false --stdin-filepath 'C:\tmp\jsprettier-route-group-repro\src\app\(group)\route\page.tsx' --log-level debug

Prettier produced the following output:

[debug] normalized argv: {"":[],"cache":false,"color":true,"editorconfig":true,"useTabs":false,"config":"C:\\tmp\\jsprettier-route-group-repro\\prettier.config.js","parser":"typescript","filepath":"'C:\\tmp\\jsprettier-route-group-repro\\src\\app\\(group)\\route\\page.tsx'","logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":[],"__raw":{"_":[],"cache":false,"color":true,"editorconfig":true,"use-tabs":false,"config":"C:\\tmp\\jsprettier-route-group-repro\\prettier.config.js","parser":"typescript","stdin-filepath":"'C:\\tmp\\jsprettier-route-group-repro\\src\\app\\(group)\\route\\page.tsx'","log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] load config file from 'C:\tmp\jsprettier-route-group-repro\prettier.config.js'
[debug] loaded options `{"plugins":["prettier-plugin-tailwindcss"]}`
[debug] applied config-precedence (cli-override): {"filepath":"'C:\\tmp\\jsprettier-route-group-repro\\src\\app\\(group)\\route\\page.tsx'","parser":"typescript","plugins":["prettier-plugin-tailwindcss"],"useTabs":false}

Prettier process finished with exit code 0.
```

**Comment by JGJP** [comment]
@jonlabelle yes I was using your new fix branch and confirmed that the path was quoted in the console. Honestly I'm struggling to think of what could be causing the issue now

**Comment by jonlabelle** [comment]
@JGJP: Give it another try... I [made an update](https://github.com/jonlabelle/SublimeJsPrettier/pull/302/commits/41ff47e67d1410215d7b12616604bf1f3c51c6bc) to force the use of the command shell (cmd.exe) on Windows.

**Comment by JGJP** [comment]
No luck still, error is the same. The single quotes not working is telling me that it was not using fish shell, and maybe the parentheses need some kind of escaping for cmd.exe

**Comment by JGJP** [comment]
I've tried some stuff in the cmd prompt and seems what's needed is to change the single quotes to double quotes, and to escape and parentheses with `^` (this is cmd.exe specific) so the path would look like this:

```
C:\Users\j\_dev\arga\dapp\node_modules\.bin\prettier --config C:\Users\j\_dev\arga\dapp\prettier.config.js --parser typescript --use-tabs true --ignore-path C:\Users\j\_dev\arga\dapp\.prettierignore --stdin-filepath "C:\Users\j\_dev\arga\dapp\src\app\^(app^)\witnessing\page.tsx" --log-level debug --cursor-offset 246

C:\Users\j\_dev\arga\dapp\node_modules\.bin\prettier --config C:\Users\j\_dev\arga\dapp\prettier.config.js --parser typescript --use-tabs true --ignore-path C:\Users\j\_dev\arga\dapp\.prettierignore --stdin-filepath "C:\Users\j\_dev\arga\dapp\src\app\^(app^)\declarations\[id]\page.tsx" --log-level debug --cursor-offset 1931
```

**Comment by jonlabelle** [comment]
@JGJP: What happens if you escape `(app)` to become `\(app\)`, and `[id]` to become `\[id\]` (according to [Fish docs on escaping](https://fishshell.com/docs/current/language.html#escaping-characters))?

**Comment by jonlabelle** [comment]
@JGJP: Try again for me... [this latest update](https://github.com/jonlabelle/SublimeJsPrettier/pull/302/commits/b6c306fc7f29b49828713040ef0ef1aa733999f8) might fix it.

**Comment by JGJP** [comment]
@jonlabelle wow interesting fix, I didn't know that the filepath doesn't even matter. This fix worked for me!

**Comment by JGJP** [comment]
I think it will break still if the config or ignore file are inside a route group, but that will probably never happen

**Comment by JGJP** [comment]
Regarding the escaping, I'm sure that it wasn't running the command through fish because single quotes cause parentheses etc to be ignored and would have worked
