### ISSUE TITLE
[Bug] Prettier is not ignoring indentation

### ISSUE THREAD

**Issue by karchung0930** [jonlabelle/SublimeJsPrettier#304]
### Explain the issue

I need Prettier to ignore some part of my code since it is not supporting Django template.
I already insert the comment `<!-- prettier-ignore -->` but it still indents:

```
<!-- prettier-ignore -->
{% if titles %}
<ul class="hi">
    {% for row in titles %}
    <li>
        <button
            class="button-title"
            type="button"
            data-id="{{ row.id }}"
        >
            {{ row.title }}
        </button>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Kindly start a new chat.</p>
{% endif %}
```

Expected result should be:
```<!-- prettier-ignore -->
{% if titles %}
    <ul class="hi">
        {% for row in titles %}
        <li>
            <button
                class="button-title"
                type="button"
                data-id="{{ row.id }}"
            >
                {{ row.title }}
            </button>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Kindly start a new chat.</p>
{% endif %}
```

I've also tried to put the ignore comment above the `ul` but it still not working.

### Prettier version

3.4.1

### JsPrettier plugin version

1.68.3

### Platform

Windows

### SublimeText version

4

### Prettier config

```json
{
    "auto_format_on_save": true,
    "prettier_options": {
        "printWidth": 120,
        "tabWidth": 4,
        "singleQuote": true,
        "singleAttributePerLine": true
    }
}
```

### Steps to reproduce

1. Just save the file to trigger auto format on save
2. You will see Prettier is still doing the indentation

### Reproducible outside of SublimeText?

No

### Attach a minimal project

[test.zip](https://github.com/user-attachments/files/18002237/test.zip)

**Comment by jonlabelle** [comment]
Hi @karchung0930. So you'll probably want to open an [issue](https://github.com/prettier/prettier/issues) with Prettier on this topic. The plugin (JsPrettier) doesn't control what is/isn't formatted.
