### ISSUE TITLE
doesn't respect my syntax-specific tab_size setting

### ISSUE THREAD

**Issue by tmaybe** [jonlabelle/SublimeJsPrettier#33]
**Prettier version**

    $ prettier --version
    1.1.0

**JsPrettier version** (package.json)

    "name": "sublime-js-prettier",
    "version": "1.7.4",

**Prettier command line arguments** (enable the `debug` setting and open the ST console)

    /usr/local/bin/prettier --stdin --color=false --print-width 80 --single-quote=false --trailing-comma none --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 4 --use-tabs=false

Is the same behavior observed when **run against Prettier directly** from the
command line? For example, to pass the contents of file `path_to_js_file.js` to
Prettier from the command line.

    Yes, but the issue is with what's being sent, not the output.

**Steps to reproduce** the behavior

    1. Open a JavaScript file. Under the Sublime Text menu, select Preferences then Settings – Syntax Specific
    2. Set or verify tab_size equal to 2
    3. Under Sublime Text Default or User settings, verify that tab_size is equal to a value other than 2.
    4. Run the JsPrettier sublime command on the JavaScript file from the command palette
    5. The tab_size value from the default/user settings is used instead of the value from the syntax specific settings.

**Comment by jonlabelle** [comment]
Worked perfectly me for me. I was immediately able to see the tab size difference when toggling the `tab_size` in my `JavaScript.sublime-settings` file and then running JsPrettier. I changed between sizes `4` and `8`.

Here's the contents of my **JavaScript.sublime-settings** syntax file:

 **tab_size: 4**

```json
{
	"ensure_newline_at_eof_on_save": true,
	"extensions":
	[
		"coffee",
		"ts"
	],
	"tab_size": 4,
	"translate_tabs_to_spaces": true,
	"trim_automatic_white_space": true
}
```

 **tab_size: 8**

```json
{
	"ensure_newline_at_eof_on_save": true,
	"extensions":
	[
		"coffee",
		"ts"
	],
	"tab_size": 8,
	"translate_tabs_to_spaces": true,
	"trim_automatic_white_space": true
}
```

Can you post yours please?

**Comment by tmaybe** [comment]
I uninstalled and reinstalled the plug-in and it seems to be working. My apologies for the inconvenience; thank you for taking the time to check.
