### ISSUE TITLE
[Errno 24] Too many open files

### ISSUE THREAD

**Issue by elliotdavies** [jonlabelle/SublimeJsPrettier#37]
**Explain the issue**

JsPrettier sometimes throws an error that there are too many open files.

**Explain the issue with as much detail as possible...**

The issue seems to happen after Sublime has been open for a while, and after I have opened / saved / closed a lot of files, though I couldn't say exactly how long it takes for the error to occur.

The error presents as a pop-up window:

<img width="424" alt="screen shot 2017-05-19 at 12 24 00" src="https://cloud.githubusercontent.com/assets/1190303/26245929/893e7e9c-3c8e-11e7-8c13-25b9f42b1c84.png">

Once the error has occurred, Prettier will not run again (the error will happen every time) until Sublime has been restarted.

**Prettier version** (command line)

    1.1.0

**JsPrettier version** (package.json)

    "name": "sublime-js-prettier",
    "version": "1.7.8",

**Platform details**

    - Sublime Text Version: 3
    - Sublime Text Build: 3126
    - Operating System Name: Mac OS X
    - Operating System Version: 10.12.5 (issue also observed on 10.10.x)

**Prettier arguments**

    "auto_format_on_save": true,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true

Otherwise I use the defaults.

**Is the same behavior observed when run against Prettier directly?**

N/A

**Steps to reproduce the behavior**

1. Use JsPrettier for a while, ensuring it runs on lots of files in the same session (?)

**Debug output**

```

-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/Users/edavies/npm-global/bin/prettier --stdin --color=false --print-width 80 --single-quote=true --trailing-comma es5 --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 2 --use-tabs=false
error: JsPrettier - [Errno 24] Too many open files
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/edavies/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 192, in run
    source, node_path, prettier_cli_path, prettier_args)
  File "/Users/edavies/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 271, in run_prettier
    shell=self.is_windows())
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 1281, in _get_handles
OSError: [Errno 24] Too many open files
```

**Comment by jonlabelle** [comment]
@elliotdavies First lets make sure you're running the latest version Sublime Text 3, which as of today (June 2, 2017) is **Build 3133**, released June 2, 2017. The version you're currently running (Build 3126, released December 23, 2016) is quite dated.

Also, there was a specific fix in *Build 3127*, which *may* address your issue...

**Sublime Text 3 Changelog** 
*Build 3127, Released April 12, 2017*

```
- Improved sidebar performance when folders contain thousands of files
```

**Comment by elliotdavies** [comment]
@jonlabelle Good point; I think 3126 is the most recent 'stable' build but I hadn't spotted the more recent dev builds. I'll upgrade and let you know if the issue continues to occur. Thanks!

**Comment by iRinku** [comment]
I find the same error building in Python 3 :/

I'm working in  Version 3.2.1 Build 3207
![Screen Shot 2019-07-05 at 12 52 50 PM](https://user-images.githubusercontent.com/45241620/60738410-e10e6700-9f23-11e9-9f29-90480bb98ce7.png)
![Screen Shot 2019-07-05 at 12 53 46 PM](https://user-images.githubusercontent.com/45241620/60738448-fb484500-9f23-11e9-80e4-8492542f2131.png)
