### ISSUE TITLE
Request: configurable file extensions for autosave formatting

### ISSUE THREAD

**Issue by vincentwoo** [jonlabelle/SublimeJsPrettier#39]
Right now, JsPrettier only formats files that end in `.js` or `.jsx`. That's totally cool for probably most people, but a good chunk of those in the Rails community are using jsx with interpolated ERB, still. Such filenames look like `component.js.jsx.erb`. ERB doesn't affect prettier's ability to format the code at all, and it works completely out of the box. In my project, I run something like:

`prettier --write "app/assets/javascripts/components/*.jsx*"` to format exactly the files in question.

Would it be possible to allow an option to pick which file extensions are formatted on save to JsPrettier?

**Comment by jonlabelle** [comment]
Though it may not be exactly what you're looking for... you can enable the [allow_inline_formatting](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L77) setting to enable formatting in essentially any file type.

Though I would suggest if your working file contains multiple syntaxes/languages (e.g: PHP and JavaScript), you'll want to be sure only the appropriate JavaScript sections are highlighted in your cursor(s) to avoid prettier barfing with errors.

**Comment by vincentwoo** [comment]
Hm, in that scenario, what will happen if I hit save in a file of a completely different language?

**Comment by jonlabelle** [comment]
You can have `allow_inline_formatting` turned on, though [auto_format_on_save](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L67) will only format .js and .jsx files (see [docs](https://github.com/jonlabelle/SublimeJsPrettier#sublime-text-settings)).

**Comment by jonlabelle** [comment]
Now available... since [v1.8.0](https://github.com/jonlabelle/SublimeJsPrettier/commit/15fd6ffabe999aaedf494384365ebd318dfc84c6).

**Comment by vincentwoo** [comment]
Thank you!
