### ISSUE TITLE
Less aggressive error reporting?

### ISSUE THREAD

**Issue by pjm17971** [jonlabelle/SublimeJsPrettier#4]
Firstly, thank you for jumping on making prettier work with sublime. Much appreciated!

However, currently if there is something that can't be parsed in the source file then this package will throw up a dialog with the entire prettier traceback. That traceback is largely useless to understand where the code doesn't parse, but pretty annoying, especially when the package is set to run prettier on save. I'm wondering if there's a more subtle alternative?

**Comment by jonlabelle** [comment]
I've never really found node.js stack traces to be very useful at all. However, I don't think it's necessarily a node.js problem. It's weeding through the exceptions bubbled up from the package dependency chain; you better have some to kill. At least in my experience.

I'll leave it open for suggestions. And thanks for the feedback!

**Comment by pjm17971** [comment]
I suppose my suggestion would be, if possible, take the top line of the traceback (or "Prettier failed to parse file") and display it in the status bar at the bottom of the screen and let it fail basically silently. It's not mission critical to have prettier always succeed and linting can show where the actual failure is.
