### ISSUE TITLE
TypeScript & CSS

### ISSUE THREAD

**Issue by icholy** [jonlabelle/SublimeJsPrettier#40]
The newest release of prettier added support for typescript and css files. https://github.com/prettier/prettier/releases/tag/1.4.0

Currently, it's only possible to execute the JsPrettier command in javascript files.

**Comment by jonlabelle** [comment]
Now available... since [v1.8.0](https://github.com/jonlabelle/SublimeJsPrettier/commit/15fd6ffabe999aaedf494384365ebd318dfc84c6).

**Comment by icholy** [comment]
You da man
