### ISSUE TITLE
Request: file size limit for auto formatting

### ISSUE THREAD

**Issue by fritz-c** [jonlabelle/SublimeJsPrettier#41]
I have `auto_format_on_save` enabled in one of my projects, and was tweaking a transpiled `bundle.js` file, only to find that prettier (unsurprisingly) choked on the 300,000 line file. While such cases are rare, they are not nonexistent.
I would propose a solution along the lines of that found in the `Trailing Spaces` package's [`trailing_spaces_file_max_size`](https://github.com/SublimeText/TrailingSpaces#disabled-for-large-files) option. Please consider it if you have some time.

**Comment by jonlabelle** [comment]
[Done](https://github.com/jonlabelle/SublimeJsPrettier/commit/e06422bf9f14d1afd55bca78963f646f70561eef)... available since v1.1.0

Just note that this setting is disabled by default.

**Comment by fritz-c** [comment]
Wow, thanks for the speedy response!
