### ISSUE TITLE
Formatting JavaScript empties file

### ISSUE THREAD

**Issue by kleinfreund** [jonlabelle/SublimeJsPrettier#42]
### Example

**Explain the issue**

Running `Format JavaScript` empties file.

**Prettier version** (command line)

    $ prettier --version
    1.4.2

**JsPrettier version** (package.json)

    ...
    "name": "sublime-js-prettier",
    "version": "1.4.2",
    ...

**Platform details**

    - Sublime Text Version: 3
    - Sublime Text Build: 3133
    - Sublime Text Architecture: What is this?
    - Operating System Name: Ubuntu
    - Operating System Version: 16.04
    - Operating System Architecture: 64bit

**Prettier command line arguments** (enable the [debug setting] and open the Sublime Text console to view the cli args passed to Prettier)

```
/usr/bin/nodejs /home/phil/.npm-global/lib/node_modules/prettier \
    --stdin \
    --color=false \
    --print-width 80 \
    --single-quote=false \
    --trailing-comma none \
    --bracket-spacing=true \
    --jsx-bracket-same-line=false \
    --parser babylon \
    --semi=true \
    --tab-width 4 \
    --use-tabs=false
```

**Is the same behavior observed when run against Prettier directly?** For example, to pass the contents of file `path_to_js_file.js` to Prettier from the command line.

No, nothing happens. The file is not transformed at all.

**Steps to reproduce the behavior**

A file `x.js` containing the following will be emptied upon formatting.

```
function hello() {
    console.log("x")
}
```

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L9

**Comment by jonlabelle** [comment]
Are there any errors reported in the Sublime Text Console?

**Comment by kleinfreund** [comment]
jsPrettier.sublime-settings

```
{
    "debug": true,
    "prettier_cli_path": "/home/phil/.npm-global/lib/node_modules/prettier",
    "node_path": "/usr/bin/nodejs",
    "node_modules_path": "/home/phil/.npm-global/lib/node_modules"
}
```

I needed to tinker around with the settings a bit, because the plugin wasn’t working right out of the box.

There is no sublime project configuration active at the moment.

**Comment by jonlabelle** [comment]
And if your [Prettier](https://github.com/prettier/prettier) install isn't working... it goes without saying that the Sublime Text integration will not work. You definitely need to get Prettier working from the command-line first.

Though it is curious that the file is being emptied... and with no error indication and plug-in 

Also... `node_modules_path` is not a valid [JsPrettier setting](https://github.com/jonlabelle/SublimeJsPrettier#sublime-text-settings).

**Comment by kleinfreund** [comment]
@jonlabelle I see. Prettier itself does work, though.

```
prettier --stdin --color=false --print-width 80 --single-quote=false --trailing-comma none --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 4 --use-tabs=false < ~/Desktop/x.js
```

Not setting `prettier_cli_path` results in `The path to the Prettier cli executable could not be found!`.

Setting `prettier_cli_path` to `/home/phil/.npm-global/lib/node_modules/prettier` solves that error but results in `[Errno 13] Permission denied`. Do the files within `~/.config/sublime-text-3/Packages/JsPrettier` require any special permissions?

**Comment by jonlabelle** [comment]
@kleinfreund _Do the files within ~/.config/sublime-text-3/Packages/JsPrettier require any special permissions?_

 not at all.

**Comment by jonlabelle** [comment]
I did add additional sanity check to always ensure content is returned from stdout before replacing the source text.

**Comment by kleinfreund** [comment]
I get it to work pointing the CLI path to the `prettier.js` file directly.

With this setting I don’t need to specify the `node_path` anymore. I also removed the invalid key from my configuration.

```
{
    "prettier_cli_path": "/home/phil/.npm-global/lib/node_modules/prettier/bin/prettier.js"
}
```

Is this supposed to be like that?

**Comment by jt3k** [comment]
@kleinfreund I think so should not be. 
sublime-js-prettier should work out of the box as well as from the console.

I have the same problem, and I also have a directory with global modules in the home directory `~/.npm-global/`

Once again I run into difficulties setting up jsPrettier on every new Mac.
