### ISSUE TITLE
JSPrettier doesn't automatically infer Typescript parsing

### ISSUE THREAD

**Issue by bholtbholt** [jonlabelle/SublimeJsPrettier#43]
### Explain the issue
When working in TypeScript, with `auto_format_on_save` on, the Prettier plugin has a hard time formatting certain lines of my code. For example:
```
require<any>('version-sort');
```
becomes 
```
require < any > 'version-sort';
```
which then throws compiler errors.

When I add `"parser": "typescript",`, the issue is fixed, but I expected it to automatically know it was a Typescript file because of:
> Prettier automatically infers the parser from the input file path, so you shouldn't have to change this setting. -- [from Parser Options](https://github.com/prettier/prettier#options)

### Prettier version
`prettier@1.4.2`

### JsPrettier Plug-in Version
`1.10.0`

### Platform Details
    - Sublime Text Version: 3
    - Sublime Text Build: 3126
    - Operating System Name: macOS Sierra 
    - Operating System Version: 10.12.5

### The contents of your `<project_name>.sublime-project` file (if applicable)

```
        "prettier_cli_path": "node_modules/.bin/prettier",
        "js_prettier": {
            "auto_format_on_save": true,
            "prettier_options": {
                "printWidth": 120,
                "singleQuote": true,
                "trailingComma": "all",
            }
        }
```

### Steps to reproduce the behavior

1. Use the same settings as above
1. Create a typescript file
1. Write an inline type, like `require<any>('version-sort');`
1. Save the file

```
require<any>('version-sort');
```
becomes 
```
require < any > 'version-sort';
```
when it should have stayed the same

**Comment by jonlabelle** [comment]
[Done](https://github.com/jonlabelle/SublimeJsPrettier/commit/01eef706c3d71ec931cf1e195363d2f68feda658).
