### ISSUE TITLE
Disabling CSS/SASS support

### ISSUE THREAD

**Issue by Overload119** [jonlabelle/SublimeJsPrettier#44]
The recent support for CSS has made this plugin unusable for me. I have custom .SASS files and it's formatting them incorrectly. I only want it to run on JS and JSX but that apparently isn't an option now.

**Comment by Overload119** [comment]
Based on the release notes, SASS isn't even supported by Prettier.

https://github.com/prettier/prettier/releases/tag/1.4.0

"Unfortunately, postcss right now doesn't parse Sass nor Stylus. We'd be happy to support them if someone is willing to do the work of printing them."

**Comment by Overload119** [comment]
I think that you should let the user specify which file_extensions should be valid.
I've work on that here: https://github.com/Overload119/SublimeJsPrettier

**Comment by jonlabelle** [comment]
So why are you trying to format them at all if it isn't formatting them correctly?

**Comment by Overload119** [comment]
I have "run_on_save" and I was using it on .js and .jsx which were working correctly.
I pretty much can't edit my .sass files now because they break as soon as I save.

**Comment by asumaran** [comment]
Any way to disable auto format on SCSS files?
