### ISSUE TITLE
JsPrettier - [Errno 13] Permission denied

### ISSUE THREAD

**Issue by StormNetwork** [jonlabelle/SublimeJsPrettier#46]
After installation on a MacOSX with Sublime Text 3, also using NVM the following errors appears:
https://www.dropbox.com/s/gugnk094gph6s1o/Captura%20de%20tela%202017-06-18%2002.01.58.png?dl=0

I tried to install prettier using sudo, changing the permissions folder... no success.

**Comment by jonlabelle** [comment]
Please see the [instructions](https://github.com/jonlabelle/SublimeJsPrettier#sublime-text-settings) for setting your `prettier_cli_path` and `node_path` when running nvm.

**Comment by patbegg** [comment]
This may help someone coming across the same problem. I had to ensure the `node_path` ended in '.../bin/node' not just '.../bin' (which `$npm bin -g` returns).
I'm using MacOS Sierra, NVM and Sublime Text 3.
