### ISSUE TITLE
support formatting json with --parser json

### ISSUE THREAD

**Issue by PatrickRoumanoff** [jonlabelle/SublimeJsPrettier#47]
With prettier 1.5.2 we can now format json by using `--parser json`

It would be great if this fantastic plugin could support formatting json files through prettier by using the `--parser json` option

### Explain the issue

As a user, I want my json files to be formatted to the same standard as my js files

### Prettier version
1.5.2

### JsPrettier Plug-in Version
1.10.12

**Comment by jonlabelle** [comment]
I'll try and work on this tonight. In the meantime... you can just add the new option to the [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L145) setting.

**Comment by jonlabelle** [comment]
Thanks @PatrickRoumanoff.
