### ISSUE TITLE
Add support for nvm

### ISSUE THREAD

**Issue by danreeves** [jonlabelle/SublimeJsPrettier#5]
Currently figuring out where I should point "node_path", but thinking that needing to update that whenever I wanted to switch node versions seems pretty annoying. 

Any reason it can't just pick up `prettier` from my current `$PATH`?

**Comment by jonlabelle** [comment]
Yea, that would make sense. Just curious, what platform/os are you running?

**Comment by danreeves** [comment]
mac OS Sierra: 10.12.2

nvm puts your versions of node into separate dirs with paths like `/Users/[user]/.nvm/versions/node/v6.9.3/bin/node` and adds a bit of setup to your `.rc` file like

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```

**Comment by cmmartin** [comment]
Is anyone able to get this to work with .nvm at all? I don't mind changing the path when I change node versions, but I can't get it to run at all. Even when I point directly to my `prettier` executable in settings, I get...

```
------------------
 JsPrettier Error 
------------------

Prettier Error Code: 127

env: node: No such file or directory
```

**Comment by jonlabelle** [comment]
Moving enhancement over to closed/archive since there hasn't been any activity on the topic in 30-days, and no pull-requests.

**Comment by sgregson** [comment]
I'm planning on looking into this.

As a reference, SublimeLinter handles `nvm` node modules, so there's something different about how their [util.which](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/util.py#L691) function gets modules from $PATH.

And for anyone landing here, you'll need to invoke the NVM script from your `.profile` or `.zprofile` in order for sublime to use nvm. Currently, as I have .zprofile set that way, SublimeJsPrettier doesn't find the module. See related https://github.com/SublimeLinter/SublimeLinter3/issues/128#issuecomment-268929866

**Comment by mcpengelly** [comment]
@sgregson answer works, I was using my .zshrc file for invoking my nvm script and it wasnt working, dropped it into my .zprofile and it worked like a charm after resetting sublime text. Thanks!

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
