### ISSUE TITLE
Enhancement: Exclude folders from `auto_format_on_save`

### ISSUE THREAD

**Issue by kenvunz** [jonlabelle/SublimeJsPrettier#50]
## Use case

Sometimes I have to dive into the `node_modules`, placing `console.log` commands to debug. Having the `auto_format_on_save` to `true` will format that file  which is somewhat undesirable.

Alternatively, an `include` option would also work too. 

Cheers! 👍

**Comment by Marinolinderhof** [comment]
if this is merged https://github.com/jonlabelle/SublimeJsPrettier/pull/52 you can exclude folders on the auto_format_on_save. 

the way it work is when:
```auto_format_on_save = true ```
it will also check auto_format_on_save_excludes. 
``"auto_format_on_save_excludes": ["*.json", "*/node_modules/*", "*/file.js", "*.json""],```

**Comment by jonlabelle** [comment]
Thanks @Marinolinderhof!
