### ISSUE TITLE
Feature request: Workspace configuration support

### ISSUE THREAD

**Issue by fritz-c** [jonlabelle/SublimeJsPrettier#53]
Prettier will soon have support for workspace configuration with files like `.prettierrc` and a couple other configuration methods described here:
https://github.com/prettier/prettier#configuration-file
The merged pull request is here: https://github.com/prettier/prettier/pull/2434
However it hasn't been released yet.

Could you make any modifications necessary such that the SublimeJsPrettier settings will have a lower priority than the workspace configs?

**Comment by jonlabelle** [comment]
Will revisit once the enhancement is released, and at least stable.
