### ISSUE TITLE
Add an option to include files with auto save

### ISSUE THREAD

**Issue by fatfisz** [jonlabelle/SublimeJsPrettier#54]
I'd like to propose a new option to include files (e.g. `auto_format_on_save_includes`).

In the case of a project I'm working on it would be more convenient to have an opt-in behavior instead of the currently available opt-out `auto_format_on_save_excludes`.

As using prettier has a potentially destructive behavior, I would feel safer if I could add a file to prettier on save when I notice it's not being prettified.

In case this option is not specified, the behavior would be as it is currently - all supported files would be autosaved.

**Comment by jonlabelle** [comment]
Hmmm. I'll leave this up for debate for a while. Personally, it seems a bit unecessary... though I can't think of use case.
