### ISSUE TITLE
There's no option to silence pop-up errors

### ISSUE THREAD

**Issue by bholtbholt** [jonlabelle/SublimeJsPrettier#57]
<img width="592" alt="jsprettier-error" src="https://user-images.githubusercontent.com/4933622/29185834-67bbd9be-7dbf-11e7-86d3-21fd785453e0.png">

With a project without prettier installed, and `auto_format_on_save: true` I get pop-ups every time I save until I set `auto_format_on_save: false`. I understand the errors are helpful when debugging, but I'd rather have them appear in the console bar, hidden entirely, or somewhere less intrusive.

Is it possible to add an option to silence errors?

Maybe:
```
error_volume: dialog|console|silent
```

### Versions
```
Prettier version: 1.5.3
JS Prettier version: 1.12.0
Sublime: Stable Channel, Build 3126
OS: Mac: Sierra 10.12.6
```

### Project Settings:
```
	"js_prettier":
	{
		"auto_format_on_save": true,
		"prettier_options":
		{
			"printWidth": 120,
			"singleQuote": true,
			"trailingComma": "all"
		}
	},
```

### Steps to reproduce:
1. Set `auto_format_on_save: true`
1. Don't include prettier in your project
1. Save a JS file

**Comment by jonlabelle** [comment]
Thanks for the feedback @bholtbholt. But doesn't configuring the `auto_format_on_save` to `false` setting require the same amount effort if you were to configure the proposed `error_volume` setting?

You can also configure the [auto_format_on_save_excludes](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L107) setting to ignore auto formatting of particular files/paths.
