### ISSUE TITLE
Support upcoming prettier cosmiconfig

### ISSUE THREAD

**Issue by benjixx** [jonlabelle/SublimeJsPrettier#58]
First of all, thanks for integrating prettier in Sublime Text.

As it turns out prettier is going to support (not released as of today) its own editor-independent configuration soon: prettier/prettier#2434

Would be great if SublimeJsPrettier would support this as its main configuration source. Thus the prettier configuration that should apply for a project would only need to be defined in a single place and it would not be necessary for each developer to configure its own editor/IDE to use prettier with the right options (e.g. not every developer might use Sublime Text).

I'm not sure though how this would be best implemented in SublimeJsPrettier.
Not sure if doing a backwards-incompatible change of only using prettier's config would be a possible way to go. Would probably be the easiest way in the long run as it would involve less maintenance on SublimeJsPrettier side (e.g. when new prettier options are introduced).

**Comment by jonlabelle** [comment]
Hi @benjixx... seems the config file feature is still an on-going discussion, and how it should be implemented. But [again](https://github.com/jonlabelle/SublimeJsPrettier/issues/53), once it's published into an official release, there's no sense of coding towards a particular pull-request; or at least I don't have the time.
