### ISSUE TITLE
Doesn't work with prettier 1.6

### ISSUE THREAD

**Issue by Remchi** [jonlabelle/SublimeJsPrettier#59]
Doesn't work with the latest 1.6.0 version of Prettier (works great with previous versions). 

Here is the error in ST console: 

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error:

Ignored unknown option: --single-quote=false
Ignored unknown option: --bracket-spacing=true
Ignored unknown option: --jsx-bracket-same-line=false
Ignored unknown option: --semi=true
Ignored unknown option: --use-tabs=false
```

Thank you very much for your work.

**Comment by Joshuaf91** [comment]
I'm getting the same error.

Just freshly installed sublime and JSPrettier

**Comment by kyleshevlin** [comment]
Have you tried it with 1.6.1? I just did at it worked for me. I think the bug was in Prettier itself.

**Comment by Remchi** [comment]
Yep, that's prettier's issue. Updating to 1.6.1 fixed it. Thanks!

**Comment by vijayst** [comment]
I have the same problem in 1.8.2.
