### ISSUE TITLE
Not reading node_path

### ISSUE THREAD

**Issue by rawcreative** [jonlabelle/SublimeJsPrettier#6]
When trying to run the plugin it appears that the plugin is not reading the node_path in the settings to retrieve the correct location of node (I'm using nvm). I get the same message whether I put the location in the default, or user settings file. I also get the same error when the node_path field is left empty. 

OS: macOS 10.11.6
Sublime build: 3126

 For reference, the node_path value is:

```json
 "node_path": ":/Users/Tim/.nvm/versions/node/v6.4.0/bin"
```

Here is the error output in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/Tim/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 50, in run
    if not self.is_global_prettier_installed():
  File "/Users/Tim/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 148, in is_global_prettier_installed
    if which('prettier', self.get_node_path()) is None:
  File "/Users/Tim/Library/Application Support/Sublime Text 3/Packages/JsPrettier/JsPrettier.py", line 142, in get_node_path
    if os.path.isdir(node_path):
  File "./python3.3/genericpath.py", line 41, in isdir
TypeError: can't specify None for path argument
```

**Comment by jonlabelle** [comment]
I really need to change (or add) the "node_path" variable name to read "prettier_path"... since the `prettier` executable resolves the path internally to node. Except for cases when installing prettier locally, in the Sublime Text Package directory.

**Comment by rawcreative** [comment]
Same result.. prettier is installed globally so it's in the same bin dir as node, i.e. the setting is the same. But it looks like it's just not even reading the settings file since it's saying that the node_path variable getting passed to isdir() is None, which is set here: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L127

**Comment by rawcreative** [comment]
After looking at the code again, I noticed that the node_path is never actually set if it's defined in the settings file, and even the defaults don't get set if node_path is set to anything other than false in the settings (the default is just an empty string). There are checks to see if it is defined, but it doesn't actually assign the defined value to the node_path variable. https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L138-L141

**Comment by jonlabelle** [comment]
@rawcreative: I just promoted [v1.0.0](https://github.com/jonlabelle/SublimeJsPrettier/tree/1.1.0). Let me know if this resolves your issue.

**Comment by rawcreative** [comment]
Nope, while it looks like it's finding the prettier cli binary, for whatever reason it's throwing an env error that node cannot be found:

```
env: node: No such file or directory
```

**Comment by jonlabelle** [comment]
Closing. since it directly relates to #5... and #5 comes before #6.

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
