### ISSUE TITLE
ignored unknown options

### ISSUE THREAD

**Issue by paOol** [jonlabelle/SublimeJsPrettier#61]
node v 7.10.1
npm 5.3

ubuntu 16.04

sublime 3, latest build

> 
> -----------------------------------------
>  JsPrettier DEBUG - Prettier CLI Command 
> -----------------------------------------
> 
> /usr/bin/prettier --stdin --print-width 80 --single-quote=false --trailing-comma none --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 2 --use-tabs=false
> 
> ------------------
>  JsPrettier ERROR 
> ------------------
> 
> Prettier reported the following error:
> 
> Ignored unknown option: --single-quote=false
> 
> Ignored unknown option: --bracket-spacing=true
> 
> Ignored unknown option: --jsx-bracket-same-line=false
> 
> Ignored unknown option: --semi=true
> 
> Ignored unknown option: --use-tabs=false
> 
> 
> Process finished with exit code 0

**Comment by dangh** [comment]
Should be fixed in prettier 1.6.1

https://github.com/prettier/prettier/issues/2683

**Comment by laugri** [comment]
Updating to 1.6.1 fixed it for me.
