### ISSUE TITLE
Support prettier config file

### ISSUE THREAD

**Issue by jamesgarfield** [jonlabelle/SublimeJsPrettier#62]
**Issue:**
`prettier` version 1.6.1 now officially supports `cosmiconfig` for config files (https://github.com/prettier/prettier#configuration-file), both by automatically traversing project directories, as well as with the `--config` option. However, the way that `JsPrettier` invokes `prettier` (by always including options flags) prevents the config file from being used (even when supplying the --config flag through `additional-cli-args`).

**Prettier Version:** 1.6.1
**JsPrettier Version:** 1.12.12

**Platform Details**
OS: OSX 10.12.6
Sublime Text Version: 3126

**Generated Prettier command line arguments**
```
/usr/local/opt/node@5/bin/node /path/to/project/node_modules/prettier/bin/prettier.js --stdin --print-width 80 --single-quote=false --trailing-comma none --bracket-spacing=true --jsx-bracket-same-line=false --parser babylon --semi=true --tab-width 4 --use-tabs=false --config /path/to/project/.prettierrc
```
**Is the same behavior observed when run against Prettier directly?**
No, when I run prettier directly I can omit all the options flags.
When I run prettier directly I can either provide the `--config` flag to point at my config file, or allow `cosmiconfig` to find it for me and get the correct results.

**The contents of your** `User/JsPrettier.sublime-settings` **file**
```
{
	"debug": true,
	"auto_format_on_save": true,
	"prettier_cli_path": "/path/to/project/node_modules/prettier/bin/prettier.js",
	"node_path": "/usr/local/opt/node@5/bin/node",
	"additional_cli_args":  {
		"--config": "/path/to/project/.prettierrc"
	},
}
```

Ideally this could be fixed by providing a way to run `prettier` "bare" (i.e. no formatting flags specified) such that it will automatically pick up any relevant config files.

An alternative would be to add support for the `--config` flag, that, when specified, cause JsPrettier to no longer use any of the `prettier-options` in either the default or user Sublime settings.

**Comment by goldo** [comment]
it uses prettier configuration file correclty for me

**Comment by jamesgarfield** [comment]
@goldo Can you please share what your configuration looks like and what resulting executed command looks like when you save?

**Comment by goldo** [comment]
my bad, used the wrong config file, you're right, it's not working for now. removing my comment

**Comment by jonlabelle** [comment]
[Now available](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L158) in v1.13.0.

**Comment by jamesgarfield** [comment]
Awesome, thank you!

**Comment by jonlabelle** [comment]
**Update:** Prettier config files are now automatically detected (since [v1.14](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/CHANGELOG.md#1140)), and the previous [`use_prettier_config_files`](https://github.com/jonlabelle/SublimeJsPrettier/blob/1.13.2/JsPrettier.sublime-settings#L185) setting is no longer necessary, and has been deprecated.

**Comment by selrond** [comment]
Using it in Sublime, it doesn't decet my `.prettierrc` config file, even though manually executing `prettier --find-config-path .` finds it. What can be wrong?

**Comment by selrond** [comment]
My bad. Used comment in the `.prettierrc` file. Working now.

**Comment by btholt** [comment]
@jonlabelle Seems related to this issue but happy to make another if appropriate.

Is there a notion of a `auto-format-on-save-if-config-detected` property with JSPrettier? That would be magic for at least my workflow.

**Comment by GriffinSauce** [comment]
^ yes this would save my config too! Right now it's all or nothing while my projects are not all prettier'd.
