### ISSUE TITLE
Ignored unknown option: --no-config

### ISSUE THREAD

**Issue by sidati** [jonlabelle/SublimeJsPrettier#64]
Hi, after the last update this error shows up and im no longer able to pretify the code, i suppose the new Prettier CLi has an issue with a flag : 
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error:

Ignored unknown option: --no-config

Process finished with exit code 0

**Comment by sidati** [comment]
**RESOLVED**
just make sure you update Prettier to the latest as mention in the changlog 😄 
`npm i prettier -g`

**Comment by glennr** [comment]
see https://github.com/jonlabelle/SublimeJsPrettier/issues/63
