### ISSUE TITLE
HTML formatter creates self closing <script> tags

### ISSUE THREAD

**Issue by PaulPineda** [jonlabelle/SublimeJsPrettier#65]
---
Just wanted to say that this is my first issue submission to GitHub.  I've chosen to omit a fair amount of suggested issue inclusions because it seems like this issue may be caused by the inclusion of the HTML formatter and as such not the core functionality of this plugin.

### The issue

I decided to make use of `auto_format_on_save: true` but then noticed that my test project broke after amended an HTML file.

So:
    
    <div id="some-id"></div>
    <script src="bundle.js"></script>

Becomes:

    <div id="some-id" />

    <script src="dist/bundle.js" />

**_The HTML formatter created self closing `<script>` tags which is a problem because `<script>` tags cannot be self closing._**

I'm guessing this may be an issue with the inclusion of the undocumented HTML formatter that was introduced.  I do not have any knowledge of Python so for now I have excluded HTML files from being formatted in this test project but I would not mind having a look-see to see if I could make this work somehow.

**Comment by jonlabelle** [comment]
Hi @PaulPineda, thanks for the feedback. I went ahead and pulled the Html formatter feature out (too early). You should be good to go now.

**Comment by PaulPineda** [comment]
Excellent, thanks!  Going forward, would you be open to me researching a way to include an HTML formatter back in?  Again it'll be the first time I properly contribute to a project but it'd a cool way for me to start...
