### ISSUE TITLE
Prettier config in package.json is ignored

### ISSUE THREAD

**Issue by sgaestel** [jonlabelle/SublimeJsPrettier#66]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [x] **Explain the issue**
- [x] **Prettier version**
- [x] **JsPrettier Plug-in Version**
- [x] **Platform Details**
- [x] **Generated Prettier command line arguments**
- [x] **Is the same behavior observed when run against Prettier directly?**
- [x] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [x] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [x] **Steps to reproduce the behavior**

---

### Explain the issue

I have a project with a `package.json` file, in which I am declaring my `prettier` configuration.
Running `prettier myFile.js` works like a charm, however, using JsPrettier ignores my configuration.
Looks like it is due to this https://github.com/prettier/prettier/issues/2704
It appears when detecting configuration, JsPrettier is using `--config package.json` argument for launching prettier. However, this is unecessary as prettier has detected configuration file by itself.
I suggest not providing the `--config` argument as soon as the configuration has been detected by prettier itself and the `--no-config` has not been set.

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.6.1

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.15.0",
    ...

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3
    - Sublime Text Build: 3126

### Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command 
    -----------------------------------------

    /usr/local/bin/prettier                  \
        --stdin                                    \
        --config=../package.json        \
        --tab-width 4                          \
        --use-tabs=true
        
### Is the same behavior observed when run against Prettier directly?
Same behavior providing same arguments, but no issue if omiting `--config` one

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, and exclude the comments.

{
    "debug": true,
    "auto_format_on_save": true
}

    
### The contents of your `<project_name>.sublime-project` file (if applicable)
No `.sublime-project` file

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Create a `package.json` file with a prettier config inside
    2. Add a `.js` file in a subfolder
    3. Try formatting the file with JsPrettier

**Comment by jonlabelle** [comment]
Hi @sgaestel. The reasoning behind the plug-in explicitly setting the `--config <path>`, when *Prettier* finds a config file and a Prettier config file is not specified, is to [reduce the performance cost](https://github.com/prettier/prettier#--find-config-path-and---config) of multiple attempts (2) of Prettier config path discovery when formatting.

On first run, and if the `--no-config` or `--config <path>` [additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier#custom-prettier-config-file-path) are not specified, the plug-in executes Prettier's [--find-config-path](https://github.com/prettier/prettier#--find-config-path-and---config) to locate an appropriate config file. If the attempt fails (no config file found), Prettier will no longer attempt to perform config file discovery when the actual formatting is performed.

Also, by setting the `--config <path>` explicitly when `--find-config-path` resolves a config, it lets the plug-in know to longer parse Prettier options specified in Sublime Text settings files. With the exception of `parser`, `tabWidth` and `useTabs`... which are all auto-detected based on the current file or selection being formatted.

**Comment by rexxars** [comment]
Huh. Unless there is some weird, undocumented behaviour, it seems to me that there is a bug in prettier.
If I specify my prettier configuration in `package.json` and run `prettier somefile.js`, it correctly resolves the configuration and formats the file. If I explicitly tell it to use `package.json`, eg: `prettier --config package.json somefile.js`, it doesn't actually use the configuration.

**Comment by rexxars** [comment]
Seems this was addressed in https://github.com/prettier/prettier/pull/2733 with the new `--config-precedence` flag.

Guess it will need integration into this plugin as well in order to work.

**Comment by alistair-hmh** [comment]
@rexxars are you sure there are options that allow the package.json options to take precedence? I don't seem to be able to replicate that behavior.
