### ISSUE TITLE
JsPrettier ERROR

### ISSUE THREAD

**Issue by kumarsatish876** [jonlabelle/SublimeJsPrettier#68]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- JsPrettier flags this in sublime 3.
          JsPrettier ERROR 
Prettier reported the following error:
Ignored unknown option: --no-config
Process finished with exit code 0 
- [ 1.6.1] **Prettier version**
- [ 1.15.2] **JsPrettier Plug-in Version**
- [{
    "auto_format_on_save": true,

    "prettier_options": {  
"printWidth": 140,
"singleQuote": true,
"trailingComma": "none",
"bracketSpacing": true,
"semi": true
    }
}] **The contents of your** `User/JsPrettier.sublime-settings` **file**

### Generated Prettier command line arguments

   JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier 
--stdin 
--no-config 
--print-width 140
 --single-quote true
 --trailing-comma none
 --bracket-spacing true
 --jsx-bracket-same-line false
 --parser babylon
 --semi true
 --tab-width 2
 --use-tabs true

**Comment by chrislaue** [comment]
@kumarsatish876: I was experiencing the exact same thing - found this issue. 

I've actually solved the issue in my environment -  I uninstalled prettier globally (I was running 1.5.3 initially) - reinstalled globally (1.6.1) - attempted a format and file formatted as expected.

Should note that I also uninstalled and reinstalled JSPrettier in sublime - but that did _not_ solve the issue. 

As an experiment - I just downgraded to 1.5.3, and I can replicate the issue. Upgrading prettier to 1.6.0 and above... the problem disappears. 

Maybe this is helpful 🤷‍♂️
