### ISSUE TITLE
Allow option to wrap single argument with parentheses

### ISSUE THREAD

**Issue by pthieu** [jonlabelle/SublimeJsPrettier#69]
## Reporting an Issue

When [reporting an issue](https://github.com/jonlabelle/SublimeJsPrettier/issues), please include the following information in your post:

- [ ] **Explain the issue**
- [ ] **Prettier version**
- [ ] **JsPrettier Plug-in Version**
- [ ] **Platform Details**
- [ ] **Generated Prettier command line arguments**
- [ ] **Is the same behavior observed when run against Prettier directly?**
- [ ] **The contents of your** `User/JsPrettier.sublime-settings` **file**
- [ ] **The contents of your** `<project_name>.sublime-project` **file (if applicable)**
- [ ] **Steps to reproduce the behavior**

---

### Explain the issue

```
const foo = (arg) => {
  ...
}
```

changes to:

```
const foo = arg => {
  ...
}
```

but in the case of more than 1 arg, it will remain `(arg1, arg2)`.

### Prettier version
`1.6.1`

### JsPrettier Plug-in Version

`1.15.6`

### Platform Details

Provide your Sublime Text version and Platform details.

    - Sublime Text Version: 3
    - Sublime Text Build: 3126
    - Sublime Text Architecture: not sure, 3?
    - Operating System Name: macOS Sierra
    - Operating System Version: 10.12.5
    - Operating System Architecture: not sure, 64 bit?

### Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

**Example**

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command 
    -----------------------------------------

    /usr/local/bin/prettier           \
      --stdin \
      --no-config \
      --print-width 80 \
      --single-quote true \
      --trailing-comma es5 \
      --bracket-spacing true \
      --jsx-bracket-same-line false \
      --parser babylon \
      --semi true \
      --tab-width 2 \
      --use-tabs false 

### Is the same behavior observed when run against Prettier directly?

Yes

### The contents of your `User/JsPrettier.sublime-settings` file

I did not overwrite, file is empty, I'm using default.
    
### The contents of your `<project_name>.sublime-project` file (if applicable)

The entire contents of your ***User*** overridden JsPretter Project-level Settings, and exclude the comments.

    {
        "folders": [
            {
                "path": "."
            }
        ],
    }

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. `npm install --save-dev prettier`
    2. Install JsPrettier
    3. Use prettier in sublime

----------

Upon further investigation, this may be an option for prettier, not so much JsPrettier

**Comment by jonlabelle** [comment]
Hi @pthieu. Please open your enhancement request on the main [Prettier Issue board](https://github.com/prettier/prettier/issues).
