### ISSUE TITLE
Option for format on save?

### ISSUE THREAD

**Issue by benfrain** [jonlabelle/SublimeJsPrettier#7]
Thanks for creating this plugin 👍

I wonder if a future release might have a format on save option?

**Comment by oeb25** [comment]
Looks like there already is one! Have a look in the settings for JsPrettier!

**Comment by jonlabelle** [comment]
[It's there](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L23)... just set the `auto_format_on_save`  value to `true` in your `User`/[JsPrettier.sublime-settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings) file.

**Comment by benfrain** [comment]
👍
