### ISSUE TITLE
Make the --no-config flag conditional?

### ISSUE THREAD

**Issue by markalfred** [jonlabelle/SublimeJsPrettier#72]
As reported in #63 #64 #67 #68, upgrading this package to v1.15 breaks prettier unless we upgrade to prettier@1.6 as well. The issue with this is that a prettier upgrade has the potential to result in thousands of lines of code changes, so there may be reasons not to do it, or at least to delay doing it.

The other workaround is to manually install and lock down the version of this package to v1.15. This is the route I'm going to take personally, but it's hard to ask a team of any significant size to each take this manual step.

Does it seem feasible to conditionalize the arguments passed to prettier, or at least to allow them to be manually overridden, if a project's currently-installed version of prettier doesn't support them?

____

**Update:** According to Prettier, it should throw a **warning**, not an **error** when given invalid options. (see: https://github.com/prettier/prettier/issues/2735)

This means that, even if stderr has content, that shouldn't halt execution. The only thing that should halt execution is a non-zero exit code. In the case of the `--no-config` issue, the error code is 0. The warning should be logged but execution should continue.

https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.py#L372 — This line should be changed from
```py
if stderr or proc.returncode != 0:
```
to
```
if proc.returncode != 0:
```

And a new mechanism to log messages to the console, without causing `self.has_error` to return `True` should be implemented.

**Comment by jonlabelle** [comment]
Help me understand why upgrading Prettier would "change thousands of lines of code..."?

**Comment by markalfred** [comment]
One tiny example:

Formatted with 1.5:
```jsx
<div>
  {shouldShow &&
    <p>
      Showing this thing
    </p>}
</div>
```

Formatted with 1.6:
```jsx
<div>
  {shouldShow && (
    <p>Showing this thing</p>
  )}
</div>
```

In a codebase of any decent size, there are many many changes of this type across the entire thing. While none of them should be functional changes, they make `git blame` and `git bisect` less effective, cause lots of merge conflicts, etc.

**Comment by markalfred** [comment]
For a potential solution, I updated `format_code` to this:

```py
if proc.returncode != 0:
    self.format_error_message(stderr.decode('utf-8'), str(proc.returncode))
    return None
if stderr:
    print(stderr.decode('utf-8'))
return stdout.decode('utf-8')
```

and this functions correctly. In short, stderr content should be logged, but shouldn't affect execution at all — only the status code should affect execution. I'm happy to open a PR with this change, but I imagine you may want it to be formatted slightly differently. Let me know what you think.

**Comment by jonlabelle** [comment]
Your *potential solution* seems feasible. Go ahead and make a PR. I should be able review it more closely, and merge it in within the next couple days.

**Comment by markalfred** [comment]
👍 thanks @jonlabelle — I'll open it today. If I have the bandwidth, I'll flesh out the formatting a bit more as well.
