### ISSUE TITLE
Support "prettier" key in package.json?

### ISSUE THREAD

**Issue by bebbi** [jonlabelle/SublimeJsPrettier#74]
Extending #62, is there any way to support the "prettier" key in package.json as prettier itself does?

In a way that it auto-discovers the package.json at the root of the project?

**Comment by jonlabelle** [comment]
This should be the current behavior... and if not specifying an addition cli arg for `--config <path>`, and letting [prettier auto-discover an appropriate path](https://github.com/prettier/prettier/releases/tag/1.6.0).

**Comment by bebbi** [comment]
Ah, thanks for the confirm. I notice that adding a `prettier` key to `package.json` changes its defaults behaviour. I have `semi: true`, and `singleQuote: false` in sublime default settings, but strangely, when I add anything inside that key, it always prettifies with `singleQuote: false` and `semi: true` no matter what values I give:

    "prettier": {
      "semi": false,
      "singleQuote": true
    }

I'm probably doing something wrong.

**Comment by bebbi** [comment]
same for any sublime default config, actually. It works per config, but above block changes it back to semicolons and no single-quote, independent of the bools in the block.

**Comment by jonlabelle** [comment]
What does your generated Prettier CLI command look like?

> NOTE: To view the generated Prettier CLI command, change the `debug` setting to `true` in `User/JsPrettier.sublime-settings`, then open the Sublime Text Console.

**Comment by bebbi** [comment]
without package.json key:

```
/path/to/node /path/to/app/.node_modules/.bin/prettier --stdin --no-config --print-width 80 --single-quote true --trailing-comma none --bracket-spacing true --jsx-bracket-same-line false --parser babylon --semi false --tab-width 2 --use-tabs false
```

with package.json key:

```
/path/to/node /path/to/app/.node_modules/.bin/prettier --stdin --config ../../../package.json --tab-width 2 --use-tabs false
SublimeLinter: eslint: index.js ['/path/to/app/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@']
```

**Comment by jonlabelle** [comment]
So I was able to reproduce your issue... both from the command-line itself, and through Sublime Text (via JsPrettier plug-in).

Here's my **package.json** file:

```json
{
  "name": "prettier-config-pkg-json",
  "version": "1.0.0",
  "description": "test",
  "dependencies": {
    "prettier": "latest"
  },
  "prettier": {
    "singleQuote": true
  }
}
```

Installed Prettier **version**:

```bash
$ prettier --version
1.7.0
```

Here's my **command**:

```bash
/usr/local/bin/prettier --stdin --config package.json --tab-width 2 --use-tabs false --config-precedence file-override < test-file.js
```

> **NOTE:** I tried both w/ and w/out the `--config-precedence file-override` option, but both produced the same result output, ignoring the `singleQuote` `true` option defined in my `package.json` file.

I would suggest opening the [issue w/ Prettier](https://github.com/prettier/prettier/issues)... if one doesn't already exist.
