### ISSUE TITLE
SublimeJsPrettier passes Sublime's tab_size setting instead of respecting .prettierrc tabWidth

### ISSUE THREAD

**Issue by jkdf2** [jonlabelle/SublimeJsPrettier#76]
The command line argument to format on save is: `<project_dir>/node_modules/.bin/prettier --stdin --config ../../.prettierrc --tab-width <SUBLIME TAB_SIZE> --use-tabs true`

This is unexpected if a `.pretttierrc` has a `tabWidth` specified as this tab width should be the master across all collaborators rather than the collaborators having to sync up their editors to have the same `tab_size` config.

## Versions

Prettier: `1.7.0`
JsPrettier version: `1.16.1`

**Comment by jonlabelle** [comment]
Please add the following setting to your [`additional_cli_args`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L189) if you prefer config files to override options passed from the CLI.

```
"--config-precedence": "file-override"
```
