### ISSUE TITLE
ignores "overrides" from prettier

### ISSUE THREAD

**Issue by patlux** [jonlabelle/SublimeJsPrettier#77]
### Explain the issue

This plugin ignores the "overrides" option from prettier specified in the .prettierrc file.
See: https://github.com/prettier/prettier#configuration-overrides

My .prettierrc.json:

    {
      "semi": false,
      "tabWidth": 2,
      "useTabs": false,
      "printWidth": 100,
      // "singleQuote": true, <-- is working
      "overrides": [
        {
          "files": "*.js",
          "options": {
            "semi": true,
            "trailingComma": "es5",
            "bracketSpacing": true,
            "singleQuote": true, // <-- is not working
            "requirePragma": false
          }
        },
        {
          "files": ".prettierrc",
          "options": { "parser": "json" }
        }
      ]
    }

### Prettier version

    $ prettier --version
    1.7.2

### JsPrettier Plug-in Version

    1.16.1

### Platform Details

    - Sublime Text Version: 3
    - Sublime Text Build: 3144
    - Sublime Text Architecture: x86_64
    - Operating System Name: archlinux
    - Operating System Version: latest
    - Operating System Architecture: x86_64

### Generated Prettier command line arguments

    /home/patrick/.n/bin/prettier --stdin --config ../../../.prettierrc.json --tab-width 2 --use-tabs false --config-precedence file-override

### The contents of your `User/JsPrettier.sublime-settings` file

    {
        "debug": true,
        "auto_format_on_save": true,
        "additional_cli_args": { "--config-precedence": "file-override" }
    }

### Steps to reproduce the behavior

Use my prettier configuration file above.

**Comment by jonlabelle** [comment]
I'm not sure how this could be an issue w/ the plug-in. Again, the plug-in just passes what ever file/selection your editing to Prettier; indicated by your command:

```
/home/patrick/.n/bin/prettier --stdin --config ../../../.prettierrc.json --tab-width 2 --use-tabs false --config-precedence file-override
```

Have tried running the command above directly from the CLI?

**Comment by jonlabelle** [comment]
@patlux Try setting your `--config-precedence` ([additional_cli_args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L189) setting) to `prefer-file`.

Let me know.

**Comment by patlux** [comment]
Nope, it doesn't change anything.

But I know now why: Because of `--stdin`. It's only working if I pass the file directly:


    prettier --config ../../../.prettierrc.json --tab-width 2 --use-tabs false configure-store.js

It's kind of logical ¯\\_(ツ)_/¯

Is there a way to change this in your plugin?

**Comment by jonlabelle** [comment]
It really needs to be fixed in [Prettier](https://github.com/prettier/prettier/issues). Because their documentation doesn't align with actual behavior.

**Comment by patlux** [comment]
@jonlabelle: It was fixed with prettier v1.7.4. But you have to add `--stdin-filepath` to the generated cli output to fix it in SublimeJsPrettier.
See: https://github.com/prettier/prettier/pull/2948

**Comment by ghedsouza** [comment]
@patlux I'm experiencing the same issue (now in 2019), and was wondering if you came up with a work-around? I tried following the threads here and I'm not sure if this is an underlying problem in the SublimeText plugin or prettier itself.

For reference, VS Code seems to do the right thing without any special configuration i.e. it correctly uses the override files when prettierfying specific file types.

**Comment by Trippnology** [comment]
I'm experiencing the same issue - overrides set in JSPrettier user settings are still ignored. Is there a way to enable them?
