### ISSUE TITLE
Single file name format for auto_format_on_save_excludes doesn't work.

### ISSUE THREAD

**Issue by ruffin--** [jonlabelle/SublimeJsPrettier#79]
### Explain the issue

* Example for `auto_format_on_save_excludes` for a single file says `"*/file.js",`
* When I use `"*/temp.js"`, a file living in `C:\temp\temp.js` is still processed by JSPrettier
* Using `"*temp.js"` in my config and it's not.

See screencast here: [https://www.youtube.com/watch?v=3Rmr1uTE8_w](https://www.youtube.com/watch?v=3Rmr1uTE8_w)

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.7.0

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.16.8"
    ...

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3.0
    - Sublime Text Build: 3143
    - Sublime Text Architecture: x64
    - Operating System Name: Windows 10
    - Operating System Version: 1703, OS Build 15063.632
    - Operating System Architecture: x64

### Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

    --stdin --no-config --print-width 150 --single-quote false --trailing-comma none --bracket-spacing true --jsx-bracket-same-line false --parser babylon --semi true --require-pragma false --tab-width 2 --use-tabs false

        
### Is the same behavior observed when run against Prettier directly?

N/A

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, and exclude the comments.

    {
        "auto_format_on_save": true,
        "auto_format_on_save_excludes": [
            "*/node_modules/*",
            "*/.git/*",
            // "*temp.js", // this is the line that I've added that works. See above.
            "*.css"
        ],
    
    //"debug":true,    // for previous step. not used when run.
    
        "prettier_options": {
            "printWidth": 150,
            "tabWidth": 2,
            "singleQuote": false,
            "trailingComma": "none",
            "bracketSpacing": true,
            "jsxBracketSameLine": false,
            "parser": "babylon",
            "semi": true,
            "lastProp":true
        }
    }

    
### The contents of your `<project_name>.sublime-project` file (if applicable)

N/A

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

1. Create file called `C:\temp\temp.js` in Sublime Text 3.
2. Insert this code into temp.js: 
    * `config.chatProtocol.active = (isEdge || isIE) ? 1 : 2;`
3. Save temp.js.
    * Note that Prettier will remove parens: 
    * `config.chatProtocol.active = isEdge || isIE ? 1 : 2;`
4. Undo change to temp.js so that parens are back.
5. Open JsPrettier.sublime-settings file. Ensure it matches the above file contents.
    * Preferences >>> Package Settings >>> JsPrettier >>> Settings - User
6. Add `"*/temp.js",` before `"*.css"` under `auto_format_on_save_excludes`.
    * This matches the example in JsPrettier's comments: `"*/file.js",`
7. Save settings.
8. Save temp.js again. File *is* processed. 
    * Incorrect behavior.
9. Undo save so that parens are back in temp.js
10. Edit JsPrettier file so that line added with `"*/temp.js",` is `"*temp.js",` 
11. Save preferences.
12. Save temp.js. File *IS NOT* processed.
    * Correct behavior for both this value and the previous.

**Comment by jonlabelle** [comment]
Looks like in *Windows*, you'll have to use back slashes, instead of forward slashes. Also the back slashes need to be escaped.

For example, instead of `*/file.js` in POSIX (macOS and Linux), the same pattern in Windows would be `*\\temp.js`

I will also get this updated in the docs.

**Comment by ruffin--** [comment]
That stinks for JsPrettier's default settings. Are you against standardizing on `/`, or is that something you'd consider in the future?

Thanks for taking a look.

**Comment by jonlabelle** [comment]
I'm actually going to take out the defaults in light of this discovery, and leave it completely upon the user to define the appropriate values, according to their platform.

**Comment by jonlabelle** [comment]
Just a quick update on this issue.

I made a [change](https://github.com/jonlabelle/SublimeJsPrettier/commit/a11343e7d0dba6d7cef54b1ce12306f390466dba) so you no longer have to specify platform specific paths in your ignore rules.
