### ISSUE TITLE
Wacky formatting on windows using prettier 0.11.0. 0.0.10 works fine

### ISSUE THREAD

**Issue by viankakrisna** [jonlabelle/SublimeJsPrettier#8]
![image](https://cloud.githubusercontent.com/assets/9636410/22296766/c78eeee2-e34d-11e6-92e6-e9cf8d14ca56.png)
Anybody having this issue on windows?  I'm using 0.11.0. Linux works fine.

when I use it via cli prettier works normally. So I think it's the issue with the plugin. Haven't tested with clean installation of sublime though

**Comment by benfrain** [comment]
See similar problem in OS X. Sample file formats fine in the online demo area: http://jlongster.com/A-Prettier-Formatter but via the Sublime plugin it really screws it up.

**Comment by viankakrisna** [comment]
I think it's an issue with prettier 0.11.0. downgrading to 0.0.10 fixes the problem

**Comment by jonlabelle** [comment]
Closing for now... [does not seem to be](https://github.com/jlongster/prettier/issues/17#issuecomment-275161303) directly to the [Sublime Text plug-in](https://packagecontrol.io/packages/JsPrettier).
