### ISSUE TITLE
Prettier errors on JSON files

### ISSUE THREAD

**Issue by willsoto** [jonlabelle/SublimeJsPrettier#80]
### Explain the issue

Currently unable to run `prettier` on JSON files.

### Prettier version

```
npx prettier --version
1.7.4
```

Prettier is **not installed globally**

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "v1.16.9",
    ...

### Platform Details

    - Sublime Text Version: 3
    - Sublime Text Build: 3144
    - Sublime Text Architecture: 64bit
    - Operating System Name: MacOS
    - Operating System Version: Sierra
    - Operating System Architecture: 64bit

### Generated Prettier command line arguments

To view the generated prettier command line arguments you need to enable JsPrettier's [debug setting] and open the Sublime Text Console after a file/section formatting attempt.

**Example**

    -----------------------------------------
     JsPrettier DEBUG - Prettier CLI Command 
    -----------------------------------------

```sh
code/path/to/project/node_modules/.bin/prettier --stdin --config .prettierrc --config-precedence prefer-file --parser json --tab-width 2 --use-tabs false
```

### Is the same behavior observed when run against Prettier directly?

No. I can run prettier directly on the file and it will format correctly.

```sh
npx prettier --config .prettierrc --config-precedence prefer-file --parser json --tab-width 2 --use-tabs false scratch.json
```

### The contents of your `User/JsPrettier.sublime-settings` file

The entire contents of your ***User*** overridden JsPrettier Settings, and exclude the comments.

```js
{
  "auto_format_on_save" : false,
  "prettier_options": {
    "printWidth": 120,
    "singleQuote": true,
    "trailingComma": "none",
    "bracketSpacing": true,
    "parser": "babylon"
  }
}
```
    
### The contents of your `<project_name>.sublime-project` file (if applicable)

```json
{
  "folders":
  [
    {
      "path": "server",
      "folder_exclude_patterns": [".yardoc", ".byebug_history", "node_modules", "doc", "tmp", "vendor", "public", "log"]
    },
    {
      "path": "client",
      "folder_exclude_patterns": ["node_modules", ".nyc_output", "coverage", "*.log"]
    }
  ],
  "settings":
  {
    "js_prettier":
    {
      "debug": true,
      "auto_format_on_save": true,
      "auto_format_on_save_excludes": ["*/node_modules/*", "*/.git/*", "*/package.json", "*/package-lock.json"]
    }
  }
}
```

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Create a file ending with `.json`
    2. Paste some valid JSON
    3. Run Prettier (through command palette or on save)
    
Example JSON to generate error (although many others have crashed as well)

```json
{
  "value": "import",
  "scopes": ["js", "constant"],
  "selectors": ["syntax--js syntax--babel", "syntax--constant"]
}
```

**Comment by jonlabelle** [comment]
What is the error that is generated?

**Comment by jonlabelle** [comment]
Also, your prettier paths are different when run from sublime text, and through the cli directly. They need to be the same in order to troubleshoot.

**Comment by willsoto** [comment]
Here is the error:

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

stdin: SyntaxError: Unexpected token, expected ; (2:12)
  1 | {
> 2 |   "folders":
    |            ^
  3 |   [
  4 |     {
  5 |       "path": "server",

Process finished with exit code 2
```

The prettier paths are the same, `npx` just uses whatever is in the local `node_modules`. But Here is the full command, same output:

```
❯ code/path/to/project/node_modules/.bin/prettier --config .prettierrc --config-precedence prefer-file --parser json --tab-width 2 --use-tabs false scratch.json
{
  "folders": [
    {
      "path": "server",
      "folder_exclude_patterns": [".yardoc", ".byebug_history", "node_modules", "doc", "tmp", "vendor", "public", "log"]
    },
    {
      "path": "client",
      "folder_exclude_patterns": ["node_modules", ".nyc_output", "coverage", "*.log"]
    }
  ],
  "settings": {
    "js_prettier": {
      "debug": true,
      "auto_format_on_save": true,
      "auto_format_on_save_excludes": ["*/node_modules/*", "*/.git/*", "*/package.json", "*/package-lock.json"]
    }
  }
}
```

**Comment by jonlabelle** [comment]
Try adding to your [`additional_cli_args`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L200) setting...

```
"additional_cli_args": {
    "--config-precedence": "cli-override"
}

Let me know the result.
```

**Comment by willsoto** [comment]
That fixes it. Here is the command it issued:

```sh
node_modules/.bin/prettier --stdin --config prettier.config.js --parser json --tab-width 2 --use-tabs false --config-precedence cli-override
```

**Comment by willsoto** [comment]
Thank you!
