### ISSUE TITLE
How to setup auto formatting on save?

### ISSUE THREAD

**Issue by nikitavoloboev** [jonlabelle/SublimeJsPrettier#81]
I tried to set this line in my preferences : 

```Bash
"auto_format_on_save": true,
```

However it didn't work. Not quite sure why.

Thank you for any help.

**Comment by jonlabelle** [comment]
Hi @nikitavoloboev . I'm going to need more details in order to troubleshoot.

For starters, please follow the instructions outlined in the [ISSUE TEMPLATE](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md), and post back your results.
