### ISSUE TITLE
Only format on save if config present

### ISSUE THREAD

**Issue by einarlove** [jonlabelle/SublimeJsPrettier#82]
Hi,
Would it be possible to configure jsPrettier to only format on save if it detects a prettier config file—.prettierrc, prettier.config.js, package.json—and disabled if not. Bonus if I could format current file manually regardless.

Maybe the `"auto_format_on_save"` could take `false | true | "config-present"`?

**Comment by jonlabelle** [comment]
Seems a bit obscure, though I'm not exactly sure what you're trying to accomplish.

See the [Usage](https://github.com/jonlabelle/SublimeJsPrettier#usage) for guidance on the different ways you can manually format the current file.
