### ISSUE TITLE
Option to hide alert message

### ISSUE THREAD

**Issue by jahvi** [jonlabelle/SublimeJsPrettier#83]
Is it possible to hide the alert message that shows up when you try to run prettier and it hasn't been found in the path?

<img width="448" alt="screen shot 2017-10-18 at 16 12 16" src="https://user-images.githubusercontent.com/661330/31726453-f331af60-b41e-11e7-8163-e60af51c65b0.png">

My use case is that in some projects prettier is not used so my idea was to keep the `auto_format_on_save` option as `true` and not install it globally, so if prettier was found on the sites `node_modules` folder it would run automatically and if not it would not run. This works at the moment but I get that alert every time I try to save.

**Comment by jonlabelle** [comment]
ehh... probably an edge case at best. But if comes again, I’m not saying no :).
