### ISSUE TITLE
`--ignore-path` in `additional_cli_args` is not working

### ISSUE THREAD

**Issue by pswai** [jonlabelle/SublimeJsPrettier#87]
### Explain the Issue and Expected Behavior

I have some JSON files that I prefer not to be formatted by Prettier. In my `.prettierignore` file, I have `**/files/` configured. By right all files in that folder should be ignored, however it is not the case (they are still formatted).

With the same configurations, it is working with VSCode and Atom.

### Prettier version

To show the currently installed prettier version, run the following command:

    $ prettier --version
    1.8.1

### JsPrettier Plug-in Version

The JsPrettier Sublime Text Plug-in version is located in the `package.json` file.

    ...
    "name": "sublime-js-prettier",
    "version": "1.17.0",
    ...

### Platform Details

    - Sublime Text Version: 3
    - Sublime Text Build: 3143
    - Sublime Text Architecture: 64bit
    - Operating System Name: Mac OSX
    - Operating System Version: El Capitan 10.11.6
    - Operating System Architecture: 64bit

### Generated Prettier command line arguments
```
/Users/pwai/.nvm/versions/node/v6.10.2/bin/node /Users/pwai/.nvm/versions/node/v6.10.2/bin/prettier --stdin --config ../../../../.prettierrc --parser json --tab-width 4 --use-tabs false --stdin-filepath /Users/pwai/Dev/FrontEnd/a-folder/files/an-app/another-folder/the-file.json --config-precedence prefer-file --ignore-path /Users/pwai/Dev/FrontEnd/.prettierignore
```

### Is the same behavior observed when run against Prettier directly?

No. When running `prettier /Users/pwai/Dev/FrontEnd/a-folder/files/an-app/another-folder/the-file.json` even without specifying `--ignore-path`, the file is ignored properly.

### The contents of your `User/JsPrettier.sublime-settings` file

    {
        "debug": true,
        "prettier_cli_path": "/Users/pwai/.nvm/versions/node/v6.10.2/bin/prettier",
        "node_path": "/Users/pwai/.nvm/versions/node/v6.10.2/bin/node",
        "auto_format_on_save": true,
        "additional_cli_args": {
            "--config-precedence": "prefer-file",
            "--ignore-path": "/Users/pwai/Dev/FrontEnd/.prettierignore"
        }
    }

### The contents of your `<project_name>.sublime-project` file (if applicable)

NA

### Steps to reproduce the behavior

Open a non-formatted file, hit Save :)

**Comment by jonlabelle** [comment]
You will need to open this on the [Prettier issue board](https://github.com/prettier/prettier/issues).

**Comment by pswai** [comment]
@jonlabelle Sorry if my issue report isn't clear, `--ignore-path` works if I run the command in terminal. I also tested it with VSCode and Atom plugins before creating this issue so I think there is something we can do here.

One thing I can think of is to merge the values in `.prettierignore` to `auto_format_on_save_excludes` config. There are definitely better ways that you can advise.

**Comment by P8TRO** [comment]
running to the same issue :(

**Comment by jonlabelle** [comment]
@P8TRO, @pswai: Are you both running [NVM](https://github.com/creationix/nvm)?

**Comment by pswai** [comment]
Yes I am. My colleagues that are facing this issue are running nvm too.

Sent from my iPhone

On 8 Dec 2017, at 16:58, Jon LaBelle <notifications@github.com<mailto:notifications@github.com>> wrote:


@P8TRO<https://github.com/p8tro>, @pswai<https://github.com/pswai>: Are you both running NVM<https://github.com/creationix/nvm>?

**Comment by jonlabelle** [comment]
Can you reply back w/ the contents of your `.prettierignore` file? Thanks.

**Comment by pswai** [comment]
@jonlabelle Sure, here you go :)

```
node_modules/
bower_components/
vendors/
vendor/
tmp/
dist/
dist-dev/
dist-test/
coverage/
.cache/
_FrontEndBuildOutput/
_FrontEndTestBuildOutput/
**/translations/
prototypes/
**/blueprints/**/files/

# For LESS/CSS, we format only UI-Kit 2.0, since it is the behaviour now.
# Note that we still format JS, JSON and MD.

bittitan-css/**/*.css
bittitan-css/**/*.less
!bittitan-css/lib/bittitan-ui-kit/2.0

```

Just in case, the empty line at the end is intentional. There is an empty line before EOF.

**Comment by jonlabelle** [comment]
The behavior was the same in my tests (files specified in `.prettierignore` were not ignored) ... from the command-line and through the plug-in.

**Test Subject**

```javascript
(function () {console.log('test');}());
```

**JsPrettier Settings**

```json
{
  "debug": true,
  "prettier_cli_path": "",
  "node_path": "",
  "auto_format_on_save": false,
  "auto_format_on_save_excludes": [],
  "allow_inline_formatting": false,
  "custom_file_extensions": [],
  "max_file_size_limit": -1,
  "additional_cli_args": {
    "--ignore-path": "/Users/jon/tmp/SublimeJsPrettier-issue-87/.prettierignore"
  },
  "prettier_options": {
    "printWidth": 80,
    "singleQuote": false,
    "trailingComma": "none",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "parser": "babylon",
    "semi": true,
    "requirePragma": false,
    "proseWrap": "preserve",
    "arrowParens": "avoid"
  }
}
```

**.prettierignore file contents**

```
/Users/jon/tmp/SublimeJsPrettier-issue-87/ignore_path/temp.js
```

**CLI Command**

```bash
/usr/local/bin/prettier \
    --stdin \
    --no-config \
    --print-width 80 \
    --single-quote false \
    --trailing-comma none \
    --bracket-spacing true \
    --jsx-bracket-same-line false \
    --parser babylon \
    --semi true \
    --require-pragma false \
    --prose-wrap preserve \
    --arrow-parens avoid \
    --tab-width 4 \
    --use-tabs false \
    --ignore-path /Users/jon/tmp/SublimeJsPrettier-issue-87/.prettierignore \
< /Users/jon/tmp/SublimeJsPrettier-issue-87/ignore_path/temp.js
```

**Test Subject Output**

```javascript
(function() {
    console.log("test");
})();
```
