### ISSUE TITLE
Prettier 1.9 doesn't work

### ISSUE THREAD

**Issue by hudochenkov** [jonlabelle/SublimeJsPrettier#88]
### Explain the Issue and Expected Behavior

[Prettier 1.9](https://github.com/prettier/prettier/releases/tag/1.9.0) introduced breaking change to `proseWrap` option. Default value for this option in this plugin is now incorrect and throws this error:

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] Invalid option for --prose-wrap.
[error] Expected "always", "never" or "preserve", but received: "true"

Process finished with exit code 2
```

### Prettier version

1.9.0

### JsPrettier Plug-in Version

1.17.1

### Platform Details

Doesn't matter.

### Generated Prettier command line arguments

```
-----------------------------------------
 JsPrettier DEBUG - Prettier CLI Command 
-----------------------------------------

/usr/local/bin/prettier --stdin --no-config --print-width 100 --single-quote true --trailing-comma es5 --bracket-spacing true --jsx-bracket-same-line false --parser json --semi true --require-pragma false --prose-wrap true --tab-width 4 --use-tabs false --stdin-filepath /Users/aleks/Downloads/performance.json
```

### Is the same behavior observed when run against Prettier directly?

Yes.

### The contents of your `User/JsPrettier.sublime-settings` file

```json
{
	"debug": true,
	"allow_inline_formatting": true,
	"prettier_options": {
		"useTabs": true,
		"printWidth": 100,
		"singleQuote": true,
		"trailingComma": "es5"
	}
}
```
    
### The contents of your `<project_name>.sublime-project` file (if applicable)

None.

### Steps to reproduce the behavior

Update Prettier to 1.9.0. Try to run plugin.

**Comment by mattbrictson** [comment]
I discovered this workaround (in JsPrettier user settings or project settings):

```json
"prettier_options": {
  "proseWrap": "always"
}
```
