### ISSUE TITLE
The default configuration has an invalid value of "proseWrap": true

### ISSUE THREAD

**Issue by Juni4567** [jonlabelle/SublimeJsPrettier#90]
### Explain the Issue and Expected Behavior

I downloaded the latest version of prettier through package control and I get an error when I run the 
 "JsPrettier:format Code" the error message says: 
`JsPrettier: Format faild! Open the console window to view error details.`
![screenshot_8](https://user-images.githubusercontent.com/9845119/33648173-78098cd6-da7a-11e7-873f-0b2e09e29663.png)

```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error(s):

[error] Invalid option for --prose-wrap.
[error] Expected "always", "never" or "preserve", but received: "true"

Process finished with exit code 2

```

### Prettier version

5.5.1

### Platform Details

Provide your Sublime Text version and Platform details.

**Example**

    - Sublime Text Version: 3
    - Sublime Text Build: 3143
    - Sublime Text Architecture: <SUBLIME_TEXT_ARCHITECTURE>
    - Operating System Name: Windows
    - Operating System Version: 8.1
    - Operating System Architecture: <OS_ARCHITECTURE>

### The contents of your `User/JsPrettier.sublime-settings` file
empty

### Steps to reproduce the behavior

The steps one would take to reproduce and observe the problem.

    1. Install JsPrettier via package controll -> install package.
    2. Open any supported files (e.g. a js file and run "JsPrettier:format Code".
    3. See the error in bottom left side of sublime text.
    
    The issue can be resolved by editing the JSPrettier.sublime.settings file and changing it to any of the expected parameters `Expected "always", "never" or "preserve", but received: "true"`

[debug setting]: https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L14

**Comment by jjahr** [comment]
Copy-paste version of Juni4567's solution:

1. Go to `Preferences > Package Settings > JSPrettier > Settings - User`.
2. Add this:
```
"prettier_options": {
	"proseWrap": "always"  // always, never, or preserve
}
```
