### ISSUE TITLE
Does not support Prettier 1.9 new arrowParens option

### ISSUE THREAD

**Issue by lucsky** [jonlabelle/SublimeJsPrettier#91]
Prettier 1.9 introduces the `arrowParens` option (https://prettier.io/docs/en/options.html#arrow-function-parentheses), as of SublimeJSPrettier 1.17.3 this does not seem to be supported.

**Comment by lucsky** [comment]
Dayum, that was fast 😄  Thanks!

**Comment by rbrlortie** [comment]
I have changed my preferences to use arrowParens but it doesn't seem to work correctly. I've even tried to pass the cli arg manually:
```
{
	"additional_cli_args": {
		"--arrow-parens": "always"
	},
	"prettier_options": {

		"singleQuote": true,
		"arrowParens": "always"

	}
}
```

This snippet still gets its parenthesis removed.
```
__.$body.on('click', '.project-write-remove-button', (event) => {
	event.preventDefault();
	$(event.target).closest('.card').remove();
});
```

It becomes:
```
__.$body.on('click', '.project-write-remove-button', event => {
	event.preventDefault();
	$(event.target)
		.closest('.card')
		.remove();
});
```
