### ISSUE TITLE
Preserve indentation when formatting selection

### ISSUE THREAD

**Issue by kvcrawford** [jonlabelle/SublimeJsPrettier#92]
Request for enhancement: utilize `--range-start` and `--range-end` options to preserve indentation when formatting selection.

See https://github.com/prettier/prettier/pull/1609

**Comment by jonlabelle** [comment]
I guess the only possible issue/conflict/complexity I can foresee if using Prettier's "--range-start" and "--range-end" options; is when a selection is made, and the entire content of the file is sent to stdin, which can contain more than one formattable syntaxes (e.g.: HTML files with JavaScript and CSS blocks), how Prettier determines the appropriate indention?
