### ISSUE TITLE
requireConfig setting

### ISSUE THREAD

**Issue by dliuzzi** [jonlabelle/SublimeJsPrettier#96]
I have auto format on save turned on in both Sublime Text and VSCode. This works great for new files (i.e. files that already comply to Prettier's style) but older files are a pain: saving those results in literally _hundreds_ of changes that I have to undo. With [prettier-vscode](https://github.com/prettier/prettier-vscode), setting `"prettier.requireConfig": true` fixes this problem rather neatly ([relevant PR](https://github.com/prettier/prettier-vscode/pull/283)).

Unless I'm missing something, a similar option doesn't seem to exist in SublimeJsPrettier. So what I end up doing is (1) disabling SublimeJsPrettier, (2) saving, and (3) re-enabling SublimeJsPrettier. This of course gets old really quick.

Are there any plans to bring this setting to SublimeJsPrettier? Thanks!

**Comment by rodri042** [comment]
+1

**Comment by jonlabelle** [comment]
@dliuzzi I read through the vs-code [discussions on the topic](https://github.com/prettier/prettier-vscode/issues/199). And I'm of the opinion (at least for now) that such a setting, adding a `prettier.requireConfig` (or similarly named) preference isn't indicative ~~~enough~~~ of the suggested intention and behavior - ignore all files when auto-format on save is turned on... and a prettier config file is NOT discovered.

That said, I'm not ruling out as future enhancement.

**Comment by ianstormtaylor** [comment]
Just ran into this exact issue. @jonlabelle are you just opposed to the naming? Or to the feature itself?

I'm unsure how to ever make use of the `auto_format_on_save` feature unless you also have the `require_config` feature to go with it. Otherwise this plugin can only ever be used in code you have control over, because editing codebases that don't have pretty will result in crazy changes that muck things up.

Would you reconsider?

**Comment by ianstormtaylor** [comment]
Further, this feature has been requested in 4 different issues in this plugin already, so there is a clear want for the functionality from users:

- https://github.com/jonlabelle/SublimeJsPrettier/issues/24
- https://github.com/jonlabelle/SublimeJsPrettier/issues/82
- https://github.com/jonlabelle/SublimeJsPrettier/issues/96
- https://github.com/jonlabelle/SublimeJsPrettier/issues/101

And the equivalent [VS Code issue](https://github.com/prettier/prettier-vscode/issues/199) even further shows that this helps a lot of people.

**Comment by jonlabelle** [comment]
Okay, I'm sold. Will work on introducing it this weekend.

**Comment by jonlabelle** [comment]
**Question...** can I assume a valid path to Prettier exists in the current environment, or specified in [JsPretter Settings](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L50)?

Just trying to avoid introducing a considerable amount of bloat trying to resolve Prettier config locations (and changes/additions to the [config spec](https://prettier.io/docs/en/configuration.html)) - and simply run the native [config resolve command](https://prettier.io/docs/en/cli.html#find-config-path-and-config) (which is the current behavior of the plug-in).

**Comment by ianstormtaylor** [comment]
@jonlabelle honestly I'm not sure. Seems like it would be nice and simple if so though.

**Comment by antoinerousseau** [comment]
there is a typo in the setting name (`conifg` => `config`).

also, it seems to ignore my prettier settings now. for example I have `semi: false` and suddenly some semicolons are added on save. i just upgraded the plugin.

**Comment by jonlabelle** [comment]
Typo [fixed](https://github.com/jonlabelle/SublimeJsPrettier/commit/a63e47430fa18c3354e9ea6cc23b81297ac69cf1).
