### ISSUE TITLE
Support of .prettierignore

### ISSUE THREAD

**Issue by rodri042** [jonlabelle/SublimeJsPrettier#97]
## Reporting an Issue

**Issue**:
With `"auto_format_on_save": true`, if I save a file that is in the `.prettierignore`, it formats the file.
**I cannot configure `additional_cli_args` with `--ignore-path` because I have multiple projects**

**Expected Behavior**:
Not formatting the file, as the `prettier` CLI does.

**Prettier version**:
1.10.2

**Platform Details**:
Sublime Text 3 Build 3126, Linux.

**Is the same behavior observed when run against Prettier directly?**
No. Prettier just ignores the file.

 **The contents of your** `User/JsPrettier.sublime-settings` **file**
```json
{
  "auto_format_on_save": true
}
```

**Steps to reproduce the behavior**
Create a node project with `prettier`, a `.prettierignore` file with some path, enable autosaving in the plugin, and save the ignored file.

**Comment by rodri042** [comment]
Also it would be great if autoformat only runs when a `.prettierrc` is define. I use Sublime Text with a lot of projects and many of them don't use Prettier, so currently every time I switch between projects I have to go to the settings file to disable/enable autoformat

**Comment by jonlabelle** [comment]
@rodri042 Can you please post the contents of your `.prettierignore` file... thanks.

**Comment by rodri042** [comment]
> @rodri042 Can you please post the contents of your .prettierignore file... thanks.

```
src/some_dir
```

When I save files under `src/some_dir` they get transformed by prettier

**Comment by jonlabelle** [comment]
Now I remember. This is actually a [dupe issue](https://github.com/jonlabelle/SublimeJsPrettier/issues/87).

**Comment by rodri042** [comment]
@jonlabelle not really. This issue is about reading `.prettierignore` automatically from the project root directory.

I woudln't like to add a path for a `.prettierignore` file for each project I have, in the plugin's configuration. I think the most intuitive decision would be reading it automatically, like Prettier CLI does.

Thanks!

**Comment by jonlabelle** [comment]
[Give it a whirl](https://github.com/jonlabelle/SublimeJsPrettier/commit/e4caf8786dbea15fddeee81579e2c1d13a673648)... 

Doc update is [here](https://github.com/jonlabelle/SublimeJsPrettier#auto-detection-of-prettierignore-in-project-root).

**Comment by PanMan** [comment]
I'm fairly sure this is on my end, but I can't get this to work?
I have a JS project, and whatever I put in the `.prettierignore` it keeps formatting on save.
I want this whole project to not be auto-formatted.
