### ISSUE TITLE
[Request] Support for 'Standard'

### ISSUE THREAD

**Issue by mesqueeb** [jonlabelle/SublimeJsPrettier#98]
I heard this app can be edited to support 'Standard'
https://github.com/standard/standard

> change prettier_cli_path to prettier-standard

I'm not sure yet how to do this.
Will there come native support for 'Standard' ?

**Comment by trongthanh** [comment]
I'm not the maintainer, but happen to use this plugin with a custom `prettier_d`. So I set the `prettier_cli_path` in this plugin's user settings to the custom prettier executable like so:
``` json
{
  "prettier_cli_path": "/usr/local/bin/prettier_d"
}
```
Maybe you can do the same with `prettier-standard`

**Comment by mesqueeb** [comment]
This worked.

Maybe I should add the instructions to the readme?
What do you think?

### Use with Standard ruleset

It's possible to use this plugin with ['standard'](https://github.com/standard/standard) ruleset instead of the 'prettier' ruleset.

1. Install ['prettier-standard'](https://github.com/sheerun/prettier-standard) globally according to the installation instructions.
2. Find the location of your installed executable file.
On a unix based system (like MacOS):
```curl
$ which prettier-standard
```
3. Copy the location. (e.g. `/usr/local/bin/prettier-standard`)
4. Install SublimeJsPrettier according to the installation instructions above.
5. Open the default settings in Sublime and copy the line: `"prettier_cli_path": ""`
6. Open the user settings in Sublime and add the line with the correct location of the 'prettier-standard' executable.
```json
{
  "prettier_cli_path": "/usr/local/bin/prettier-standard",
}
```

You can now use 'prettier-standard' in Sublime Text 3 by opening the **Command Palette** (super + shift + p) and typing `JsPrettier: Format Code`. This will format your code to the 'standard' ruleset.

**Comment by jonlabelle** [comment]
Thanks @mesqueeb. I'll try to get this worked in.
