### ISSUE TITLE
Add support for `prettier_d`

### ISSUE THREAD

**Issue by trongthanh** [jonlabelle/SublimeJsPrettier#99]
I'd really like this plugin to support the global CLI [`prettier_d`](https://www.npmjs.com/package/prettier_d) which is an on-going service for `prettier`. By using `prettier_d`, format on save executes much faster.

Right now, I have to set the `prettier_cli_path` in user settings:

```json
{
  "prettier_cli_path": "/usr/local/bin/prettier_d"
}
```

However, once I reconfigure the `prettier_cli_path` to `prettier_d`, the Prettier options in user's .sublime-settings don't apply. Even the `--config file` argument won't apply, so I ended up adding each options as CLI argument like so:

```json
"additional_cli_args": {
  "--single-quote": "",
  "--print-width": "120",
  "--trailing-comma": "es5",
  "--prose-wrap": "preserve"
}
```

**Comment by jonlabelle** [comment]
Does `prettier_d` support/expose Prettier's [CLI config options](https://prettier.io/docs/en/cli.html#find-config-path-and-config)?

**Comment by trongthanh** [comment]
prettier_d expose the same cli options as mainstream  prettier. 

Is this enhancement working yet? Or at least this plugin should not override .prettierrc if prettier_cli_path is not default.
